### ISSUE TITLE
Change angular2-meteor Npm build process from Gulp to Webpack

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#105]

**Comment by Urigo** [comment]
@dotansimha please reference the commits

**Comment by dotansimha** [comment]
https://github.com/Urigo/angular2-meteor/commit/67e3154b5604ce3688353dae26dbcea9e4339e00
https://github.com/Urigo/angular2-meteor/commit/8234bd4a4adcd5fe603ab49fd5d93ec51f48b184
https://github.com/Urigo/angular2-meteor/commit/a727b28441222923ffe574d1f4efc448bba7fa06
https://github.com/Urigo/angular2-meteor/commit/e047bc38a00df714d1e6f1627acde788a6168730
