### ISSUE TITLE
Deprecate typings of TSD

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#117]
Check about typings instead of TSD (npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information)

**Comment by barbatus** [comment]
Is any specific reason you marked it for 0.5.0 milestone and Meteor 1.3?
I believe most NPM will have built-in typings; this issue is more about current version of the package and tutorial.

**Comment by Urigo** [comment]
good point, I will it to the milestone to make sure your change also goes in that branch as well
