### ISSUE TITLE
Expose angular2-meteor in Npm

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#122]

**Comment by denodaeus** [comment]
Any progress on this yet?  Now that the functionality has been changed to remove meteor add support, there's no "easy" way to install the current package with Meteor 1.3.

**Comment by Hongbo-Miao** [comment]
I have same question now about how to start using angular2-meteor in Meteor 1.3.
Since SystemJS is removed, if updated directly, it will show `Cannot read property 'System' of undefined`.

**Comment by Hongbo-Miao** [comment]
@denodaeus it has been updated!
check [here](https://github.com/Urigo/angular2-meteor) `Quick Start` section

**Comment by sclausen** [comment]
Wouldn't it be nicer, to remove the install part of the quickstart chapter in the readme, to prevent confusion? Or at least marking it as currently not working?

**Comment by omeid** [comment]
`0.5.0-beta.1` is now on atmosphere, any chance we could give this a try with `1.3`?

**Comment by barbatus** [comment]
README has been corrected. Please install NPM directly from the current repo. When the repo finally gets published, it'll be outlined in the README as well.
