### ISSUE TITLE
Figure out why zone.js >= 0.5.11 does not work with Meteor

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular2-meteor#125]
"zone.js": "0.5.10" works great
"zone.js" >= "0.5.11" cause error - trying to run `addTask` from undefined.

The only difference between them is that AngularJS team used WebPack now to build zone.js

**Comment by dotansimha** [comment]
Related: https://github.com/angular/zone.js/issues/244

**Comment by barbatus** [comment]
Just updated to 0.5.11 in the current package version, haven't found any issue.
If I am not wrong `addTask` method just appeared in 0.5.11 version and absent in 0.5.10.
You might be still using  0.5.10 version somehow with Angular2 beta-3.

**Comment by barbatus** [comment]
I wonder if you tried `angular2-polyfill.js` script?

**Comment by dotansimha** [comment]
@barbatus 
I used angular beta 2, with the latest zone.js.
Tried the polyfills but it did not make any difference.

Just noticed that @mhevery make some changes in beta3 that might related (https://github.com/angular/angular/commit/3211938), what do you think?
I will try it later today...

**Comment by dotansimha** [comment]
@barbatus Fixed in beta3. works with zone 0.5.11.
