### ISSUE TITLE
Socially 2.0 with Meteor 1.3

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular2-meteor#126]

**Comment by dotansimha** [comment]
Created a single JS file with bootstrap4 alpha2: https://github.com/dotansimha/bootstrap4-webpack-package
No other choice until Meteor will resolve the assets issue here: https://github.com/meteor/meteor/issues/6098
@Urigo

**Comment by Urigo** [comment]
@dotansimha please reference the commits

**Comment by Hongbo-Miao** [comment]
@dotansimha can u let me know why not choose creating a single JS file for [ng2-bootstrap](http://valor-software.com/ng2-bootstrap/)? Because ng2-bootstrap has already done so much work.

Does [bootstrap4-webpack-package](https://github.com/dotansimha/bootstrap4-webpack-package) also have those similar functions like Alerts, Typeahead, Rating?

Thanks

**Comment by dotansimha** [comment]
No reason. You actually right..  It is just a temporary workaround until Meteor 1.3 will support importing assets from node modules and then we can use the original package.

**Comment by Hongbo-Miao** [comment]
@dotansimha thanks, hope meteor 1.3 and angular 0.5 will come out soon.

**Comment by Hongbo-Miao** [comment]
@dotansimha would you mind offering some help about how to repackaging when you have time? Thanks

The links below are same thing:
https://github.com/Urigo/angular-meteor/issues/1211
https://github.com/valor-software/ng2-bootstrap/issues/129
https://github.com/valor-software/ng2-file-upload/issues/49

**Comment by valorkin** [comment]
@Hongbo-Miao as far as I understood, meteor 1.3beta is able to consume npm packages,
please try it :)

**Comment by Hongbo-Miao** [comment]
@valorkin yeah, you are right! I am kind of excited.

**Comment by Hongbo-Miao** [comment]
@valorkin yeah, you are right! I am kind of excited. It opens a big door to all packages. :)

**Comment by Hongbo-Miao** [comment]
@valorkin yeah, you are right! I am quite excited. It opens a big door to all packages. :)

**Comment by Urigo** [comment]
done and deployed
