### ISSUE TITLE
Test out Angular2's new router with React

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#136]
If we could get into a single router for both the Angular and React, it would be a great win for all communities and will make the transitions much easier.
It could be the same router but also different routers with the same syntax

**Comment by Tallyb** [comment]
Shouldn't we start by testing it with Angular2?

**Comment by MichaelSolati** [comment]
![102122-300-this-is-madness](https://cloud.githubusercontent.com/assets/11811422/17027931/e4d82a94-4f33-11e6-862a-71e9e10e8f88.gif)

**Comment by dotansimha** [comment]
This issue was moved to Urigo/angular-meteor#1477
