### ISSUE TITLE
SCSS codes do not run well in styles: [...]

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#138]
I am not sure this belongs to Angular2 or angular2-meteor problem. If it is not because of angular2-meteor, let me know please. I will report on Angular2's github. Thanks

I am using [Sass for Meteor](https://github.com/fourseven/meteor-scss/)

The SCSS codes in styles: [...], Sass for Meteor won't compile it.

There are two solutions, both work:

 1. create another file **XXX.scss**, and change to use `styleUrls: ['XXX.scss']`

 1. use CSS instead of SCSS codes in `styles: [...]`.

The original post about this problem is here:
http://stackoverflow.com/questions/35275461/cannot-change-the-color-of-the-cell-of-table-when-hover/35283046#35283046

**Comment by barbatus** [comment]
I think it's not possible and likely won't be. Meteor can't compiler SCSS contained in any other file, so does Angular2 and likely won't be able by other means in the future. Though, you could ask on Angular2 repo for just in case.
Only external files for SCSS now, but I don't see any problem in it.

**Comment by Hongbo-Miao** [comment]
Thanks!
