### ISSUE TITLE
loginServicesConfigured missing from Meteor typings file

### ISSUE THREAD

**Issue by allanlundhansen** [Urigo/angular2-meteor#139]
Not really a showstopper by any means. Was not sure if I should add the issue here or on definitelytyped ?

**Comment by barbatus** [comment]
Yes, it's missing, but it needs to add a PR here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/meteor/meteor.d.ts,
could you do that?

**Comment by barbatus** [comment]
PR for this issue https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8232
