### ISSUE TITLE
Adding blaze template support

### ISSUE THREAD

**Issue by smirnovigor** [Urigo/angular2-meteor#14]
During socially tutorial, I have added meteor's accounts-ui package, 
since html file passing barbatus:angular2 compiling only, the template `{{> loginButtons}}` wasn't compiled. I think Blaze templates should be supported

**Comment by dalcib** [comment]
There is a project that start to convert the templete of Account-UI from Blaze to Angular2.
[https://github.com/ShMcK/NG2-Accounts-Ui](https://github.com/ShMcK/NG2-Accounts-Ui)

**Comment by smirnovigor** [comment]
What about other meteor packages with templates?

**Comment by barbatus** [comment]
@smirnovigor it's already answered here #9.
Angular2 is supposed to be main UI library in this package. You'll be able to add two HTML-processors at the same time in future versions of Meteor.

**Comment by Urigo** [comment]
We plan to do that plus adding a migration tutorial from Blaze to Angular 2.0.

Probably we will release a separate package with a compilation plugin that moves the template compilation of Angular 2 from html to ng.html and adds blaze-html-templates like we do in Angular 1.x with angular-with-blaze.

Would love some help with that until we get to it

**Comment by Stivfk** [comment]
I can help with the migration tutorial. Let me know where we are.

**Comment by Urigo** [comment]
First thing is to write something similar to `urigo:angular-blaze-template` and `angular-with-blaze` to Angular 2.0.
Try running a first app using both Angular 2.0 and Blaze and let's start from there

**Comment by allanlundhansen** [comment]
any updates on this issue? We have a somewhat decent sized app written in blaze and would love to be able to do gradual incremental migration.

**Comment by Urigo** [comment]
I'm glad to announce that now, thanks to @dotansimha , there is a tutorial on how to use Blaze and Angular 2.0 together so you could migrate gradually to Angular 2.0 or just use them both forever - http://www.angular-meteor.com/migration/angular2/intro
