### ISSUE TITLE
Using @InjectUser(), cannot get all fields of this.user during ngOnInit() when refresh the page 

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#141]
I have custom fields for users. I am trying to get all fields of this.user during `ngOnInit()` using `@InjectUser()`

```
ngOnInit()  // constructor, ngAfterContentInit, ngAfterViewInit are here all same result
{
    console.log("this.user", this.user);   // Meteor.user() is same result too
}
```
Every time I refresh the page, it can only get emails and profile fields info.

If I want to get all fields of this.user, I have to go to another component(page) and back tho this component(page) or use a button to read this.user value.

**Comment by Hongbo-Miao** [comment]
If I use publish and subscribe, I can get all fields of the user (myself) in the ngOnInit().

@InjectUser() way can only get emails and profile of the user (myself) in the ngOnInit().

**Comment by Hongbo-Miao** [comment]
If I use traditional way,` Meteor.publish` and `this.subscribe` with `this.autorun` inside, I can get all fields of the user (myself) in the ngOnInit().

`@InjectUser()` way can only get emails and profile of the user (myself) during ngOnInit().

**Comment by barbatus** [comment]
According to the docs only `username, emails and profile` published by default when `autopubish` removed (check out http://docs.meteor.com/#/full/meteor_users). if you need more fields, you'll need to set them explicitly.

**Comment by Hongbo-Miao** [comment]
Oh, thanks, it was my mistake, I published user info in Meteor.publishComposite's children. But I forgot that, which makes me think `this.user` from meteor-angular2 will publish all fields of this user.
