### ISSUE TITLE
Rename / split MeteorComponent

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular2-meteor#142]
**Background:**
MeteorComponent provides some features:
- Subscribe
- Autorun
- Binding to ngZone

**Why split?**
Some feature are also should be available for other types of classes, such as Pipe, Service and so on. 
By putting the actual logic of some features outside and provide them as one single unit of code, it is possible to use it as a puzzle and get only what you need. 
MeteorComponent will remain a class that uses all the pieces in one place.

**Why rename?**
Meteor**Component** gives that sense that you need to use and extend it only when you write components, but in fact, you can also run Pipes or Services that uses the logic it provides.

**Comment by barbatus** [comment]
How do you see a unit of code? Is it a class, a method or anything else?
MeteorComponent was partly created to handle onDestroy and make cleanups. 
So without wrapping, for example, `subscribe` in the zone and handling cleanups, bare `Meteor.subscribe` is left.

**Comment by barbatus** [comment]
Agreed on renaming. Not sure though how to name it otherwise. `Meteorized` - all I was able to come up with so far.

**Comment by Urigo** [comment]
latest API is the result of this discussion
