### ISSUE TITLE
TypeScript imports marks Meteor 1.3 import from Atmosphere package as error

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular2-meteor#144]
Tracks this: https://github.com/meteor/meteor/issues/6177

**Comment by barbatus** [comment]
@dotansimha the solution with fake typings seems to solve the issue only halfway?
Every package will need a full definition file anyways, otherwise it just will curse on any imported class from that package.

**Comment by barbatus** [comment]
Like if I am an author of some package foo, I just do a definition:

```
declare module "meteor/foo" {
  export = fooPackage;
}
```

"meteor/foo" won't be underlined red after.

**Comment by dotansimha** [comment]
@barbatus yeah its a nice solution... but it is not possible to create a typings to this and maintain it... too much packages in use... I think that Meteor should provide a solution for that because those imports are workarounds for working with NPM and Atmosphere packages together.

**Comment by barbatus** [comment]
ok, like mentioned before in a expression  `import {some_api} from 'meteor/some_package'`  after Meteor potential fix, ` from 'meteor/some_package'` will work fine, that't right. But other `import {some_api}` won't  work. It still will be cursing.

**Comment by bySabi** [comment]
@barbatus modules mapping is on Typescript nightly build right now and on 2.0 roadmap.
Could you create a new beta compiler to test 'modules' mapping??
 
see this thread: https://github.com/meteor/meteor/issues/6177

**Comment by tomitrescak** [comment]
@barbatus are you sure it works?
Doing:

```

**Comment by barbatus** [comment]
The first one is to import what Accounts itself exports

**Comment by barbatus** [comment]
Since it's quite clear now that Meteor adds Atmosphere packages as virtual NPMs w/o any real stubs, the  right way (if not only one possible) to fix current issue will be to add a repo with some package's typings  to the meteor typings registry here https://github.com/meteor-typings. It could be done by  either packages authors or any volunteer.
