### ISSUE TITLE
Importing npm packages to client

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular2-meteor#146]
Hello, 

Is it possible, at this stage, to import a NPM package to client?
Namely, I want to import [angular2-materialize](https://github.com/InfomediaLtd/angular2-materialize) and use it in my templates and components.
Or should we wait for Meteor 1.3 and see how it turns out with NPM imports?

**Comment by barbatus** [comment]
NPM is never been a problem if converted to a Meteor package.
