### ISSUE TITLE
Please add a unit testing chapter in the tutorial

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#147]
Right now, there is not too much info about unit-testing for angular-meteor project, let alone angular2-meteor project.

If possible, please add a unit testing chapter in the tutorial! It will help a lot.

Thanks

**Comment by barbatus** [comment]
These tutorials are considered for beginners. Unit testing is a more advanced and big topic that is certainly not required to build an example app like Socially. For those who wants more, we could provide links to resources - there are also bunch of articles and other types of information online how to test Angular and Meteor particularly. @Urigo what do you think?

**Comment by Hongbo-Miao** [comment]
Meteor is using Velocity, Angular 2 is using Jasmine. So really needs some guide for which one I should use.

**Comment by Urigo** [comment]
I think this is a good idea.
a lot of people want this and with Meteor 1.3 it became a lot better.
I've already added it to simple-todos-angular (Angular 1.x) so I hope we can get it soon to Socially 2.0.
Would love help with that of course

**Comment by Hongbo-Miao** [comment]
Moved to [angular-meteor-docs](https://github.com/Urigo/angular-meteor-docs/issues/79).
