### ISSUE TITLE
Please add a more detailed section for the folder structure

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#148]
Right now the [Step 7 - Folder structure](http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure) for actual file structure does not describe too much, only says "server" and "client" from meteor side in general.

But if the project it big, what would the folder structure look like from angular2-meteor side?

**For client part:**
```
client/
----- styles/
---------- main.css
----- lib/
---------- calendar.pipe.ts
---------- truncate.pipe.ts
----- services/
---------- alert.service.ts
----- components/
---------- home/
--------------- home.component.ts
--------------- home.component.html
--------------- home.component.css
--------------- home.service.ts
---------- about/
--------------- about.component.ts
--------------- about.component.html
--------------- about.component.css
--------------- about.service.ts
----- app.ts
```

or 

```
client/
----- styles/
---------- main.css
----- lib/
---------- calendar.pipe.ts
---------- truncate.pipe.ts
----- services/
---------- alert.service.ts
----- home/
---------- components/
--------------- home.component.ts
--------------- home.component.html
--------------- home.component.css
--------------- home.service.ts
----- about/
---------- components/
--------------- about.component.ts
--------------- about.component.html
--------------- about.component.css
--------------- about.service.ts
----- app.ts
```

or something else.
Also, right now socially does not have services, if it has, where it should be.

**For other parts:**
```
server/
----- main.ts
collections/
----- methods.ts
public/
----- img/
```

Some sources:
https://github.com/mgechev/angular2-seed
https://scotch.io/tutorials/angularjs-best-practices-directory-structure
http://meteortips.com/first-meteor-tutorial/structure/

**Comment by u0m3** [comment]
There is also a style guide by John Papa https://github.com/johnpapa/angular-styleguide/blob/master/a2/README.md

Although the test files can not be in the client directory as they get picked up by the compiler and a mess emerges (or at least that was the case last time I checked); you need to place them in *imports* according to https://www.meteor.com/tutorials/blaze/testing and http://guide.meteor.com/testing.html#introduction

**Comment by barbatus** [comment]
@Hongbo-Miao Can you pls move it here https://github.com/Urigo/angular-meteor-docs?

**Comment by Hongbo-Miao** [comment]
Sure!
