### ISSUE TITLE
Stop a MeteorComponent autorun

### ISSUE THREAD

**Issue by twastvedt** [Urigo/angular2-meteor#149]
In regular Meteor I can do something like:
```
Tracker.autorun((c) => {
  if (someSubscriptionHandle.ready() && someOtherSubscriptionHandle.ready()) {
    doSomething();
    c.stop();
  }
}
```
How would I do something similar with the MeteorComponent autorun method? The function doesn't take a Tracker.Computation argument, instead the autorun method returns the computation object.

Alternatively, is there an angular2-meteor way to add an onready function to a subscription handle?

This is most likely an issue with my understanding rather than an issue with angular2-meteor.

**Comment by barbatus** [comment]
MeteorComponent is supposed to stop all computations/subscriptions on the component destroy.
But right, computation param should be passed additionally.

**Comment by twastvedt** [comment]
Wow, thanks! I've loved using angular2-meteor, and your speedy response to requests is awesome.
