### ISSUE TITLE
Drop-down list in a form is not working in EDGE and Firefox (v 44)  (using Angular2-Meteor 0.4.2 from atmosphere)

### ISSUE THREAD

**Issue by parau** [Urigo/angular2-meteor#150]
I´m using a drop-down list in my form. When I test using the Chrome browser everything is OK. In EDGE and Firefox (tested on version 44.0) the form does not update the binding (only for the <select> field - <input> field works fine).

I tried to replicate this problem using the tutorial's Socially app and got the sampe problem. In my test I changed the form from:
...
  <label>Location</label>
  <input type="text" ngControl="location">
...
to
...
  <label>Location</label>
  <select ngControl="location">
    <option value="NY">New York</option>
    <option value="LA">Los Angeles</option>
  </select>
...

Any idea of what is going on?

**Comment by barbatus** [comment]
a dup of https://github.com/angular/angular/issues/6573
