### ISSUE TITLE
Angular2 and Blaze side by side?

### ISSUE THREAD

**Issue by tuxbear** [Urigo/angular2-meteor#152]
Like angular-with-blaze, is it possible to have Blaze working side by side with Angular2?

**Comment by barbatus** [comment]
Yes, it's possible. You'll need to create a package wrapper that wraps Blaze templates internally into Angular 2 components and expose them. A an example, take a look at https://github.com/Urigo/angular2-meteor/tree/master/packages/ng2-accounts-ui. There was a plan to simplify Blaze usage or/and to make upgrade path Blaze->Angular2 clearer (see https://github.com/Urigo/angular2-meteor/issues/14). But now it likely will happen for Meteor 1.3, if it's still going to have sense.
