### ISSUE TITLE
use external js function 

### ISSUE THREAD

**Issue by skyboys22** [Urigo/angular2-meteor#153]
Hello,

i'm using angular2-meteor -v0.3.9 with Materialize, and my probleme is how to call external function javascript or Jquery from ts file?
i found **declare function xxx()**; but it's not resolve my probleme :/

my need is to initialise function, i tried to do that inside html file but no success.

any idea?

thank you

**Comment by skyboys22** [comment]
maybe i can resolve it by something like : 
**Template.nametemplete.onrendred**
what's equivalent to this function in angular2-meteor?

**Comment by skyboys22** [comment]
i need something like Template.name.**onrendred** but in jquery

**Comment by MilosStanic** [comment]
I am currently trying to repackage https://github.com/InfomediaLtd/angular2-materialize for Meteor. I'm having some problems, but as soon as I finish, I will let you know so you can add it to your packages and use it.

**Comment by derekkite** [comment]
declare var _ : any;
declare var Papa: any;
declare var lodash: any;

**Comment by skyboys22** [comment]
@MilosStanic thank u
@derekkite i did it but im getting: No Directive annotation found

**Comment by barbatus** [comment]
It's not clear from your description what are you trying to reach.
If you need typings for Materialize, there was added some at DefinitelyTyped, https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/materialize-css

Otherwise using Materialize is pretty straightforward since its API doesn't come in ES6 modules, so you are using it in the same as for any other (not Angular2 and TypeScript) app.

**Comment by skyboys22** [comment]
thank you for reply @barbatus, i think it's what i need.
in meteor i added package materialize : materialize, and i don't have probleme with css.
but with component like collapsible must be initialized and i couldn't did it until now. i saw what you send me and i found that component is initialized. i'm trying to fixe probleme with import like jquery.
sorry for my english

**Comment by skyboys22** [comment]
how can i include it

**Comment by skyboys22** [comment]
thank you, fixed :D (y)

**Comment by atcheri** [comment]
@skyboys22 hi.
Could you please provide a code snipet of how to made it work ?
I'm also trying to call collapsible inside of the main.ts under ngAfterViewInit, but __still doesn't work__
```
ngAfterViewInit() {
    jQuery('.collapsible').collapsible({accordion : false});
}
```
the ngAfterViewInit is called, and when I also 
```
console( jQuery('.collapsible').collapsible({accordion : false}) );
```
it properly returns the jquery object.

Thanks

**Comment by skyboys22** [comment]
sorry @atcheri, i forget to reply !
i used this https://github.com/skyboys22/DefinitelyTyped/tree/master/materialize-css ;) so you will not use jquery
you will do something like:         Materialize.showStaggeredList('#slide-out');
