### ISSUE TITLE
Template compilation

### ISSUE THREAD

**Issue by hlehmann** [Urigo/angular2-meteor#156]
Currently when we open a page for the first time it is very slow because it download the file, compile then execute.
Is it possible to have template caching or something like https://github.com/ludohenin/gulp-inline-ng2-template ?

I heard that angular2 will allow template compilation during the build process, but hard to find any information.

**Comment by barbatus** [comment]
Meteor 1.3 will provide this functionality or we'll have to implement it themselves.
But what  does prevent you to use this Gulp plugin now? (you can reach same functionality with help of Webpack as well)

**Comment by hlehmann** [comment]
According to the angular team (http://angularjs.blogspot.fr/2016/02/angular-2-templates-will-it-parse.html), angular will provide offline template compilation. Reducing size and load time by moving template parsing to the build process.

Therefore, angular templates shouldn't be considerate as assets.

**Comment by hlehmann** [comment]
Somethings like React and jsx :
https://docs.google.com/document/d/11r8IuS4xDyhVSEBp7fDYo7aiLYsLEXKs4lPd36umUGM/edit
