### ISSUE TITLE
Apps are not working when minified

### ISSUE THREAD

**Issue by Isigiel** [Urigo/angular2-meteor#157]
Before you open up an issue, please check if the issue already exists or have been closed before.

#### My app
When running my ap locally with `meteor`everything works fine. After uploading it works as well, but once I click a routed Link I get `EXCEPTION: Error during evaluation of "click"`. When deploying it with `--debug`everything works well.
#### Your app
Of course you can't replicate this, so I tried with the tutorial app at step 6. It deosn't even display something but gives me `EXCEPTION: RangeError: Maximum call stack size exceeded`. Again it works fine when deployed in debug mode.

As I'm only getting started with angular2 I'd be glad for input on how to resolve this issue.

##### Used Versions
Both apps use `angular2-meteor: 0.4.2`

**Comment by barbatus** [comment]
A dup of https://github.com/Urigo/meteor-angular2.0-socially/issues/36, https://github.com/angular/angular/issues/6380.
Please check out Angular2 repo 's issues for the suspicious issues first.

**Comment by Isigiel** [comment]
Thanks, @barbatus I subscribed to that issue and will look there next time.
