### ISSUE TITLE
Router html5 mode is not working

### ISSUE THREAD

**Issue by Isigiel** [Urigo/angular2-meteor#158]
When using the router as instructed it defaults to the angular html5 mode. I assume a problem with meteor prevents it from showing the right route after reloading. It seems that this only applies to nested child routes.
The hash mode works fine though.

**Comment by derekkite** [comment]
This is the developer guide from Angular2. I'd suggest working through that.

https://angular.io/docs/ts/latest/guide/router.html

**Comment by barbatus** [comment]
@Isigiel A lot of people faced similar issues if their `templateUrl` were not exactly right.
See, for example, https://github.com/Urigo/angular2-meteor/issues/161.
Please, check out one more time, if it's still there, then I'll need a repo to reproduce.
Also, you could check out Socially app - it works fine with nested links.
