### ISSUE TITLE
[ng2-meteor-accounts] emit event on authetication changes

### ISSUE THREAD

**Issue by Isigiel** [Urigo/angular2-meteor#160]
It'd be nice to get an event if the authentication status changes, so users can be redirected to other routes if they now are not allowed to view it anymore.

**Comment by Hongbo-Miao** [comment]
@Isigiel right now I am using this way, you can also use this way:

 // app.ts
import { Component, View } from 'angular2/core';
import { InjectUser } from 'meteor-accounts';
import { AuthRouterOutlet } from 'client/auth-router-outlet.directive';

@Component({
  selector: 'app'
})
@View({
  directives: [AuthRouterOutlet],
  template: `
    <auth-router-outlet></auth-router-outlet>
  `
})
@InjectUser()
class App extends MeteorComponent {
  constructor() {
    super();
  }

  ngOnInit() {
    // 1) for the user who just sign in
    Accounts.onLogin(() => {
      // do something if need
    });

    // 2) for the user who signed in and went back to the page
    if (this.user) {
      // do something if need
    }

    // When users sign out
    this.autorun(() => {
      if (!this.user) {
        // do something if need
      }
    });
  }
}


// client/auth-router-outlet.directive.ts
import { ElementRef, DynamicComponentLoader, Directive, Input } from 'angular2/core';
import { Router, RouterOutlet, ComponentInstruction } from 'angular2/router';

@Directive({
  selector: 'auth-router-outlet'
})
export class AuthRouterOutlet extends RouterOutlet {
  private router: Router;
  publicRoutes: Array<string> = [];

  constructor(_elementRef: ElementRef, _loader: DynamicComponentLoader, _parentRouter: Router, @Input('name') nameAttr: string) {
    super(_elementRef, _loader, _parentRouter, nameAttr);

    this.router = _parentRouter;

    this.publicRoutes = [
      '', 'reset-identify'
    ];
  }

  activate(instruction: ComponentInstruction) {
    let url = instruction.urlPath;

    if (_.indexOf(this.publicRoutes, url) !== -1) {
      // here you cannot inject and use this.user, because at this moment, this.user has no value
      if (Meteor.user()) {
        this.router.navigate(['Home']);
      } else {
        return super.activate(instruction);
      }
    } else {
      if (Meteor.user()) {
        return super.activate(instruction);
      } else {
        this.router.navigate(['Landing']);
      }
    }
  }
}

**Comment by dotansimha** [comment]
This issue was moved to Urigo/angular-meteor#1476
