### ISSUE TITLE
Deep linking with angular2 

### ISSUE THREAD

**Issue by GuyAvraham** [Urigo/angular2-meteor#161]
The angular 2 router works for one level of a route but fails to refresh for a deeper link (returns empty page).
for example, I open http://localhost:3020/home
A click on a link brings me to http://localhost:3020/onboarding/new
A refresh on the last brings empty page

**Comment by barbatus** [comment]
There is nothing specific in Angular2-Meteor that could affect routing with deeper links. People usually face similar issue (empty page) if they forget to add the absolute URL to a component's template (which starts with `/`). Please check out once more. Otherwise I'll need a repo with an example to reproduce it.

**Comment by GuyAvraham** [comment]
Iv'e checked the component's templates, and they all start with /
I cannot add the repo, cause its not public

After reading here:
https://angular.io/docs/ts/latest/guide/router.html#base-href
We saw that we did not defined <base href="/" />  

so adding index.html with the following fixed the issue
```
<head>
    <base href="/"/>
</head>
<body>
<app></app>
<script>System.import('client/app');</script>
</body>
```

**Comment by barbatus** [comment]
@GuyAvraham Ok, you can reach same functionality also by adding a provider `provide(APP_BASE_HREF, { useValue: '/' })`. After, you can remove index.html if it's not supposed to contain more info then mentioned above.

**Comment by GuyAvraham** [comment]
thanks.
on app.ts we already has that one
`bootstrap(Simulator, [ROUTER_PROVIDERS, provide(APP_BASE_HREF, { useValue : '/' })]);
`but it did not work.

**Comment by barbatus** [comment]
@GuyAvraham Socially app uses it. it works fine there at least...

**Comment by andyrue** [comment]
I have experienced this too and @GuyAvraham solution worked. I also already had the provider as @barbatus suggested.
