### ISSUE TITLE
Package version not in catalog: barbatus:angular2

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#162]
I followed [this tutorial](http://justmeteor.com/blog/deploy-to-production-on-heroku/) to deploy my app on Heroku.

When I am doing the sixth step: `git push heroku master`, I got the error 

> => Errors while initializing project:
> remote: While selecting package versions:
> remote: error: Package version not in catalog: barbatus:angular2 0.8.7
> remote: While refreshing package catalog to resolve previous errors:
> remote: error: DDP disconnected while connection in progress
> remote:  !     Push rejected, failed to compile Node.js app

I didn't find any info online. Is this error because Heroku's side that they do not have the `barbatus:angular2` package? Thanks

**Comment by Hongbo-Miao** [comment]
I got response from Heroku Support...

> I'm afraid that there isn't much help we can offer in this case. 3rd party buildpacks are out of our control and we can't maintain them. I would suggest reaching out to the maintainers of the buildpack and seeing if they have any suggestions for you.

**Comment by Urigo** [comment]
@Hongbo-Miao looks like it might be a problem with the connection or that you need to create a new, clean Meteor install.
Can you try that?

**Comment by Hongbo-Miao** [comment]
@Urigo thanks, I will let you know once I tried

**Comment by Hongbo-Miao** [comment]
@Urigo I used [heroku-buildpack-meteor](https://github.com/jordansissel/heroku-buildpack-meteor) succeed to deploy. Now I met two other problems:

1. EXCEPTION: No Directive annotation found on e

  https://github.com/Urigo/meteor-angular2.0-socially/issues/36

1. ngDoCheck is not a function when using minified bundles

  https://github.com/angular/angular/issues/6380

But right now I don't have a good way to solve them.
