### ISSUE TITLE
No provider for t! (t -> t) in production mode

### ISSUE THREAD

**Issue by hlehmann** [Urigo/angular2-meteor#166]
I'm using meteor 1.3-beta.12 and I have no problem in dev mode. But I cannot "build" the app, the DI doesn't work.

This issue occur even for a minimalist app
```
@App({...})
class MyApp {
   constructor(){}
   } 
```

Does it work well for you ?

**Comment by hlehmann** [comment]
Apparently it's due to Ionic directives, I keep searching.

**Comment by barbatus** [comment]
duplicated to https://github.com/Urigo/meteor-angular2.0-socially/issues/36
