### ISSUE TITLE
Plugin is not defined

### ISSUE THREAD

**Issue by derekkite** [Urigo/angular2-meteor#168]
This showed up. Meteor 1.3 beta, angular2 from npm, and git angular2-meteor. It seems to be a version mismatch in the compiler setup somewhere.

W20160303-20:27:03.156(-8)? (STDERR) /home/derek/.meteor/packages/meteor-tool/.1.1.13-beta.11.1rfo3gq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267                                                     
W20160303-20:27:03.156(-8)? (STDERR)                                            throw(ex);
W20160303-20:27:03.157(-8)? (STDERR)                                                  ^
W20160303-20:27:03.185(-8)? (STDERR) ReferenceError: Plugin is not defined
W20160303-20:27:03.185(-8)? (STDERR)     at meteorInstall.node_modules.meteor.caching-compiler.caching-compiler.js (packages/caching-compiler/caching-compiler.js:1:12)                                                                                                       
W20160303-20:27:03.185(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
W20160303-20:27:03.185(-8)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160303-20:27:03.185(-8)? (STDERR)     at /home/derek/meteor/triggers/.meteor/local/build/programs/server/packages/caching-compiler.js:828:1                                                                                                                                
W20160303-20:27:03.185(-8)? (STDERR)     at /home/derek/meteor/triggers/.meteor/local/build/programs/server/packages/caching-compiler.js:841:3                                                                                                                                
W20160303-20:27:03.186(-8)? (STDERR)     at /home/derek/meteor/triggers/.meteor/local/build/programs/server/boot.js:245:10
W20160303-20:27:03.186(-8)? (STDERR)     at Array.forEach (native)
W20160303-20:27:03.186(-8)? (STDERR)     at Function._.each._.forEach (/home/derek/.meteor/packages/meteor-tool/.1.1.13-beta.11.1rfo3gq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)        
W20160303-20:27:03.186(-8)? (STDERR)     at /home/derek/meteor/triggers/.meteor/local/build/programs/server/boot.js:140:5

**Comment by sclausen** [comment]
+1

**Comment by MilosStanic** [comment]
similar, meteor-1.3-beta.16, angular2-meteor-0.5.0-beta.1 from git

```
W20160315-11:37:05.933(1)? (STDERR) ReferenceError: Plugin is not defined
W20160315-11:37:05.933(1)? (STDERR)     at meteorInstall.node_modules.meteor.caching-compiler.caching-compiler.js (packages/caching-compiler/caching-compiler.js:1:12)
W20160315-11:37:05.933(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:180:1)
W20160315-11:37:05.934(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
W20160315-11:37:05.934(1)? (STDERR)     at /home/milos/devel/mcalc2/.meteor/local/build/programs/server/packages/caching-compiler.js:830:1
W20160315-11:37:05.934(1)? (STDERR)     at /home/milos/devel/mcalc2/.meteor/local/build/programs/server/packages/caching-compiler.js:843:3
W20160315-11:37:05.934(1)? (STDERR)     at /home/milos/devel/mcalc2/.meteor/local/build/programs/server/boot.js:272:10
W20160315-11:37:05.935(1)? (STDERR)     at Array.forEach (native)
W20160315-11:37:05.935(1)? (STDERR)     at Function._.each._.forEach (/home/milos/.meteor/packages/meteor-tool/.1.1.13-beta.16.1eywn4o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160315-11:37:05.936(1)? (STDERR)     at /home/milos/devel/mcalc2/.meteor/local/build/programs/server/boot.js:133:5
```

**Comment by barbatus** [comment]
Can you guys please try with `angular2-compilers` once more? I just tested it and didn't find this issue.

**Comment by derekkite** [comment]
Fixed. Thanks.
