### ISSUE TITLE
After invoking angular meteor  browser error

### ISSUE THREAD

**Issue by freemansystems** [Urigo/angular2-meteor#169]
for this function inside modules/meteor_component.js    

**    function isCallbacksObject(callbacks) {                                                                         //
        return callbacks && subscribeEvents.some((event) => {                                                       //
            return _.isFunction(callbacks[event]);                                                                  //
        });                                                                                                         //
    } 
**
throwing:  Uncaught syntax error: missing ) after argument list

Not sure after that point as to the impact if any.

**Comment by barbatus** [comment]
What is modules/meteor_component.js? There is no files with js-extension in this repo.
Check that your IDE doesn't generate js-files. Otherwise, elaborate what your problem is about, and re-open this issue.
