### ISSUE TITLE
Angular2 Module Http for REST Services not found

### ISSUE THREAD

**Issue by hege088** [Urigo/angular2-meteor#172]
When I'm using Meteor and Angular like it's described in the tutorial there is no Angular2 Module called Http to user REST Services.

I used this tutorial from Meteor: http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

When I want to import:

``` import {Http, HTTP_PROVIDERS} from 'angular2/http'; ```
and I start meteor, I get this Error Message:

``` [web.browser] client/app.ts (5, 36): Cannot find module 'angular2/http'. ```

**Comment by Hongbo-Miao** [comment]
Same here, `http` is not in it is not in `typings/angular2` folder.
