### ISSUE TITLE
Heads up, major breaking change in Angular2. @View removed

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular2-meteor#173]
There's been a breaking change just introduced to Angular2. 
https://github.com/angular/angular/pull/7495
@View annotation has just been completely removed. It has been optional so far, but now it's gone.
I see that the tutorial for angular2-meteor uses @View heavily. So it has to be removed now.

**Comment by barbatus** [comment]
Thanks. There is a separate issue for making Angular2-Meteor tutorial aligned with Meteor 1.2 and latest Angular2. Let's reference this issue there https://github.com/Urigo/angular2-meteor/issues/115.
