### ISSUE TITLE
Using ng2-translate with Meteor v1.2.1

### ISSUE THREAD

**Issue by mjwheatley** [Urigo/angular2-meteor#174]
Will it ever be possible to use the [ng2-translate](https://github.com/ocombe/ng2-translate) npm module with Meteor v1.2.1 or will we need to wait for Meteor 1.3 to use npm modules on the client?

**Comment by barbatus** [comment]
It has bundled version based on SystemJS https://github.com/ocombe/ng2-translate/blob/master/bundles/ng2-translate.js. So I don't see any problem to move it to Atmosphere.
Look at how Angular2 NPM itself converted here https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/angular2 and repeat.
