### ISSUE TITLE
Subscriptions updated twice after update in method

### ISSUE THREAD

**Issue by activeperception** [Urigo/angular2-meteor#175]
Hi guys,

my code looks like
```javascript
this.subscribe('subscriptionName', somekindofId, () => {
    this.autorun(() => {
        this.clientObject = SomeCollection.findOne(somekindofId);
        console.log('updated!')
    }, true) 
}
```

and I noticed that when I invoke a method that triggers an update (i.e. SomeCollection.update...) the body of this.autorun **is called twice**. 

I assume it's because of latency compensation that runs the 'update()' twice (on client and server). If that had to be the case would it be possible not to call the autorun the second time if values sets by server coincide with client values? It would be a nice optimisation not to force the app to run through change detection again (with the same values).

Thanks,
 Raffaele

**Comment by barbatus** [comment]
I don't see how this relates to the Angular2 package, sorry. It'll likely require changes to the Meteor core (in case it's really an issue). Though, you could post it to the Meteor repo if you consider it as a problem for you.

**Comment by activeperception** [comment]
for some reasons I thought it was related to the glue (if there is any) between meteor and angular2 (MeteorComponent). I'll post in the meteor core.

Thanks
