### ISSUE TITLE
In urigo:angular2-meteor@0.4.5_1, angular2-meteor.d.ts is gone

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#176]
After updating from `urigo:angular2-meteor@0.4.4` to `urigo:angular2-meteor@0.4.5_1`,
the file `typings/angular2-meteor/angular2-meteor.d.ts` is not downloaded and added.

**Comment by omeid** [comment]
Same problem. Further more, the angular2 typings add are broken too.
