### ISSUE TITLE
Creating app with Meteor 1.3 and Angular2 gives 'reflect-metadata shim is required when using class decorators'

### ISSUE THREAD

**Issue by masterdude** [Urigo/angular2-meteor#177]
I was trying to create a project using Meteor 1.3 and Angular, but I can't get it to work.

The documentation isn't ready for this new stack, I used the descriptions from the README.md from this repo and the angular2-meteor-auto-bootstrap repo.
It's tested with angular2@^2.0.0-beta.6 and angular2@^2.0.0-beta.10

This are the steps I followed:

Creating the project
```javascript
meteor create meteor-1.3-test-2 --release 1.3-rc.2
cd meteor-1.3-test-2/

npm install angular2 --save
npm install https://github.com/Urigo/angular2-meteor --save
npm install https://github.com/Urigo/angular2-meteor-auto-bootstrap --save
npm install es6-promise@^3.0.2 es6-shim@^0.33.3 reflect-metadata@0.1.2 rxjs@5.0.0-beta.2 zone.js@^0.6.4 --save

meteor remove blaze-html-templates
meteor add angular2-compilers
```

client/app.ts
```ts
import {Component} from 'angular2/core';
//import {bootstrap} from 'angular2/bootstrap';
import {bootstrap} from 'angular2-meteor-auto-bootstrap/bootstrap';

@Component({
    selector: 'socially',
    template: "<p>Hello World!</p>"
})
export class Socially {}

bootstrap(Socially);
```

client/index.html:
```html
    <head>
        <meta charset="UTF-8">
        <title>meteor 1.3 test</title>
    </head>
    <body>
    <socially>Doesn't work jet</socially>
    </body>
```

Running the app:
```
meteor
```
Console log :
```
Uncaught reflect-metadata shim is required when using class decorators    -->   modules.js?hash=74bb7a2…:9809
```

**Comment by barbatus** [comment]
yes, you'll need to `import 'reflect-metadata'` yourself.
Also change to `import {bootstrap} from 'angular2-meteor-auto-bootstrap'`.

**Comment by sclausen** [comment]
``` bash
meteor create meteor-angular2-test --release 1.3-rc.4
cd meteor-angular2-test
npm install https://github.com/Urigo/angular2-meteor --save
npm install https://github.com/Urigo/angular2-meteor-auto-bootstrap --save
meteor remove blaze-html-templates
meteor add angular2-compilers
npm install angular2@2.0.0-beta.11 es6-promise@3.1.2 es6-shim@0.35.0 \ 
  reflect-metadata@0.1.2 rxjs@5.0.0-beta.2 zone.js@0.6.4
```

``` html
<head>
  <meta charset="UTF-8">
  <title>meteor 1.3 test</title>
</head>
<body>
  <socially>Doesn't work jet</socially>
</body>
```
``` typescript
import 'reflect-metadata';
import {bootstrap} from 'angular2-meteor-auto-bootstrap'
import {Component} from 'angular2/core';

@Component({
  selector: 'socially',
  template: `<p>Hello World!</p>`
})
class Socially { }

bootstrap(Socially);
```

now its `Uncaught ReferenceError: Zone is not defined` for me :-/

**Comment by masterdude** [comment]
Hi sciausen,
I think you need to install Angular2.

npm install angular2 --save

**Comment by sclausen** [comment]
@masterdude That's the first module I stated in npm install.

**Comment by masterdude** [comment]
@sciausan You are right I missed that.

When I follow your steps on a new project I get the zone error too.
When I upgrade my project using the same dependency versions I stil get the reflect-metadata shim error.
When I changed the order of the imports from this:
```
import {Component} from 'angular2/core';
import 'reflect-metadata';
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
```
to this:
```
import 'reflect-metadata';
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
```
Then I get the zone error to on my old project too.

**Comment by hlehmann** [comment]
To fix that I have an import file in a lib directory with that

```
import 'moment';
import 'zone.js';
import 'reflect-metadata';
import 'rxjs';
```

It have to be loaded before any call to angular

**Comment by rbaradari** [comment]
@hlehmann But then you are importing the modules on the server too. Which crashes the server. Besides you get this during compilation: 

> Exported external package typings file 'node_modules/zone.js/dist/zone.js.d.ts' is not a module.


I tried a `lib/dependencies.js` with 
```
if (Meteor.isClient) {
    require('zone.js');
    require('reflect-metadata');
    require('rxjs');
}
```

But then I'm stuck with: `compiler.ts:8 Uncaught Error: ZoneSpec required!`

**Comment by hlehmann** [comment]
try the imports in client/lib/dependencies.js
make sure you have the `modules` package installed

**Comment by masterdude** [comment]
@hlehmann 
Still the same results.
I have added the client/lib/dependencies.js with the content from @rbaradari .
Modules package is part of the angular2-meteor package and was already present in `./.meteor/local/build/programs/web.browser/packages`
I have also tried it after installing `modules` package via npm myself, but still the same result.

**Comment by barbatus** [comment]
I added all dependencies and polyfills required by Angular2 in a separate package called angular2-runtime that goes as part of angular2-compilers now. Just update angular2-compilers (when new version is published), and it should free you from requiring dependencies like reflect-metadata etc directly.

**Comment by u0m3** [comment]
How does one force meteor to update a package when running `meteor update angular2-compilers` responds with `The specified packages are at their latest compatible versions.` and yet running `meteor update` yields
```
Not updating the release, because this app is at a newer release (METEOR@1.3) than the latest recommended release (METEOR@1.2.1).
Your top-level dependencies are at their latest compatible versions.

The following top-level dependencies were not updated to the very latest version available:
 * angular2-compilers 0.5.0 (0.5.4 is available)

Newer versions of the following indirect dependencies are available:
 * barbatus:typescript 0.2.0-beta.8 (0.2.0 is available)
 * barbatus:typescript-compiler 0.5.0-beta.14 (0.5.0-beta.15 is available)
To update one or more of these packages, pass their names to `meteor update`.
```
?

**Comment by Urigo** [comment]
@u0m3 can you try doing `meteor update barbatus:typescript@0.2.0`?
or maybe even just `meteor update barbatus:typescript` should work?

**Comment by u0m3** [comment]
@Urigo unfortunately no
```
C:\git\meteor1.3-angular2.0-socially [master +7 ~0 -0 !]> meteor update barbatus:typescript
The specified packages are at their latest compatible versions.
C:\git\meteor1.3-angular2.0-socially [master +7 ~0 -0 !]> meteor update barbatus:typescript@0.2.0
=> Errors while upgrading packages:

While selecting package versions:
error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "@".
```
