### ISSUE TITLE
The steps to create an angular2-meteor1.3 project

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#180]
(This just helps people save some time to create an angular2-meteor1.3 project. Feel free to close it when the document is ready.)

1. Update your meteor globally (If you already updated, then no need to do it again. And go [here](https://github.com/meteor/meteor/releases) to check if there is a new version).
`meteor update --release 1.3-rc.12`

1. To create a new angular2-meteor1.3 project, run these in your terminal:
 ```bash
meteor create --release 1.3-rc.12 hello
cd hello
npm install angular2-meteor --save
npm install angular2-meteor-auto-bootstrap --save
meteor remove blaze-html-templates
meteor add angular2-compilers
 ```

1. Remove **main.js**, **main.html**, **main.css** files in the client folder.

1. Then create these two files in your **client folder**:

    **// app.ts**
    ```typescript
    // import 'reflect-metadata';, no need if you use angular2-compilers@0.5.1 or newer
    import { bootstrap } from 'angular2-meteor-auto-bootstrap'
    import { Component } from 'angular2/core';

    @Component({
      selector: 'app',
      template: `<p>Hello World!</p>`
    })
    class App {}
    bootstrap(App);
    ```
    ~~Make sure you put `import 'reflect-metadata';` first line before other import, otherwise it won't work.~~

    **// index.html**
    ```html
    <body>
    <app></app>
    </body>
```

1. At last, run `meteor` in the terminal and go to `http://localhost:3000` to check your app.

**Comment by jaxon** [comment]
## Error: Missing Required Dependencies

### TL:DR

After running `meteor` in step 5, I had to install `angular2` and it's peer dependencies:

```
npm install angular2@2.0.0-beta.9 --save
npm install es6-promise@^3.0.2 --save
npm install es6-shim@^0.33.3 --save
npm install reflect-metadata@0.1.2 --save
npm install  rxjs@5.0.0-beta.2 --save
npm install zone.js@0.5.15 --save
npm install angular2@2.0.0-beta.9 --save
```

### Details

Running `meteor` in step 5 threw this error:
`client/app.ts (3, 27): Cannot find module 'angular2/core'.`

Running `npm install angular2@2.0.0-beta.9 --save`  threw these warnings:

```
eom@ /home/jaxon/Projects/eom
├── angular2@2.0.0-beta.9 
├── UNMET PEER DEPENDENCY es6-promise@^3.0.2
├── UNMET PEER DEPENDENCY es6-shim@^0.33.3
├── UNMET PEER DEPENDENCY reflect-metadata@0.1.2
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.2
└── UNMET PEER DEPENDENCY zone.js@0.5.15
```

Running `meteor` after installing peer dependencies ran without issue. 


Thanks to @Hongbo-Miao for a great tutorial.

**Comment by barbatus** [comment]
@jaxon I added Angular2's peer dependencies to the `package.json`, and verified that running `npm install https://github.com/Urigo/angular2-meteor --save` should be enough now.
@Hongbo-Miao if you update to latest `angular2-compilers` you'll have `angular2-runtime` package which has now all polyfills required Angular2. So `import 'reflect-metadata'`is not needed and from now on will confuse people. Otherwise, consider closing this issue since all information given here are repeated in the README.

**Comment by MilosStanic** [comment]
I just tested this, it appears `import 'reflect-metadata'` is still needed.
I didn't encounter problems that @jaxon had.

**Comment by barbatus** [comment]
It shouldn't be needed, verify that you have angular2-compilers version 0.2.1

**Comment by MilosStanic** [comment]
You're right (I suppose you mean 0.5.1): 
```
milos@milos-N73Jn:~/devel/m13test$ meteor update
Not updating the release, because this app is at a newer release
(METEOR@1.3-rc.5) than the latest recommended release (METEOR@1.2.1).
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest
version available:
 * angular2-compilers 0.5.0 (0.5.1 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * barbatus:typescript 0.2.0-beta.8 (0.2.0-beta.10 is available)
To update one or more of these packages, pass their names to `meteor update`.
milos@milos-N73Jn:~/devel/m13test$ meteor update angular2-compilers
The specified packages are at their latest compatible versions.
```
but it refuses to update

**Comment by Devidian** [comment]
Try "meteor add angular2-compilers@0.5.1" this worked fine for me

meteor add angular2-compilers@0.5.1
Currently using angular2-compilers without any version constraint.
The version constraint will be changed to 0.5.1.

Changes to your project's package version selections:

angular2-compilers         upgraded from 0.5.0 to 0.5.1
barbatus:angular2-runtime  added, version 0.2.1
barbatus:typescript+       upgraded from 0.2.0-beta.9 to 0.2.0-beta.10

My Problem: Several days now i try to get/find a working example with ng2-material (https://justindujardin.github.io/ng2-material/) included, i always end up some mysterious problems like "Zone is not defined" or something else.

**Comment by MilosStanic** [comment]
@Devidian
I'm also trying to do `ng2-material` and having same problems. Please refer to https://github.com/Urigo/angular2-meteor/issues/171 , let's discuss it there.

**Comment by MilosStanic** [comment]
I just put `angular2-compilers@0.5.1` to my `.meteor/packages` file, and the app crashes with: 
```
meteor
[[[[[ ~/devel/m13test ]]]]]                   

=> Started proxy.                             
=> Started MongoDB.                           
                                                                                   
/home/milos/.meteor/packages/meteor-tool/.1.2.4-rc.5.egs93i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: false == true
    at new NodeModulesDirectory (/tools/isobuild/bundler.js:230:12)
    at add (/tools/isobuild/bundler.js:352:9)
    at Function.readDirsFromJSON (/tools/isobuild/bundler.js:358:7)
    at /tools/isobuild/bundler.js:1926:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/milos/.meteor/packages/meteor-tool/.1.2.4-rc.5.egs93i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Function.readFromDisk (/tools/isobuild/bundler.js:1918:7)
    at Object.readJsImage (/tools/isobuild/bundler.js:2790:18)
    at /tools/isobuild/isopack.js:957:28
    at Array.forEach (native)
    at Function._.each._.forEach (/home/milos/.meteor/packages/meteor-tool/.1.2.4-rc.5.egs93i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:954:7)
    at /tools/packaging/tropohouse.js:514:19
    at Array.forEach (native)
    at Function._.each._.forEach (/home/milos/.meteor/packages/meteor-tool/.1.2.4-rc.5.egs93i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/tropohouse.js:513:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:448:20)
    at /tools/packaging/tropohouse.js:606:18
    at /tools/utils/buildmessage.js:565:21
    at /home/milos/.meteor/packages/meteor-tool/.1.2.4-rc.5.egs93i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:33:40
```

**Comment by barbatus** [comment]
@Devidian ng2-material's page says that it's `Compatible with: angular2@>=2.0.0-beta.11`.
Current version of Angular2 tested for this repos is beta.9, which means Angular2 polyfills in angular2-compilers might be specific to this version. Angular2 beta.11 is coming soon.

@MilosStanic what would be if you run `meteor --release METEOR@1.3-rc.4`?

**Comment by MilosStanic** [comment]
@barbatus yes, it works with `rc.4` and without `import 'reflect-metadata';`

**Comment by omeid** [comment]
The error mentioned is fixed in rc.6.

**Comment by MilosStanic** [comment]
I can verify all works fine with rc.6
