### ISSUE TITLE
Issue using collections from the collections folder.

### ISSUE THREAD

**Issue by studiollama** [Urigo/angular2-meteor#183]
I am having an issue with the 1.3 version of angular2 where it says in the tutorial to put export var paties = new Mongo.Collection('parties'); in a file named parties in a folder named collections.  This is the error that I get:

W20160321-23:40:57.115(-7)? (STDERR)
W20160321-23:40:57.116(-7)? (STDERR) C:\Users\Matt\AppData\Local\.meteor\packages\meteor-tool\1.2.4-rc.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160321-23:40:57.116(-7)? (STDERR)                                            throw(ex);
W20160321-23:40:57.116(-7)? (STDERR)                                                  ^
W20160321-23:40:57.116(-7)? (STDERR) Error: A method named '/parties/insert' is already defined
W20160321-23:40:57.117(-7)? (STDERR)     at packages/ddp-server/livedata_server.js:1545:15
W20160321-23:40:57.117(-7)? (STDERR)     at Function._.each._.forEach (E:\Users\Matt\Documents\Meteor\socially\socially\.meteor\local\build\programs\server\packages\underscore.js:147:22)
W20160321-23:40:57.117(-7)? (STDERR)     at Server.methods (packages/ddp-server/livedata_server.js:1541:7)
W20160321-23:40:57.117(-7)? (STDERR)     at packages/allow-deny/allow-deny.js:191:24
W20160321-23:40:57.117(-7)? (STDERR)     at [object Object].CollectionPrototype._defineMutationMethods (packages/allow-deny/allow-deny.js:190:5)
W20160321-23:40:57.118(-7)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:226:8)
W20160321-23:40:57.118(-7)? (STDERR)     at meteorInstall.lib.parties.ts (lib/parties.ts:1:23)
W20160321-23:40:57.118(-7)? (STDERR)     at fileEvaluate (E:\Users\Matt\Documents\Meteor\socially\socially\.meteor\local\build\programs\server\packages\modules-runtime.js:158:9)
W20160321-23:40:57.119(-7)? (STDERR)     at require (E:\Users\Matt\Documents\Meteor\socially\socially\.meteor\local\build\programs\server\packages\modules-runtime.js:92:16)
W20160321-23:40:57.119(-7)? (STDERR)     at lib/parties.ts:19:2

However, if I move it to the app file, the server starts, but I get this in  the chrome console: 
collection.js:220 Uncaught Error: There is already a collection named 'parties'

**Comment by barbatus** [comment]
I just tried this and had no any error. Make sure you updated your project to the latest versions. Otherwise, I need a repo to reproduce.
Also, the tutorial is for the version based on Meteor 1.2.

**Comment by studiollama** [comment]
I was able to figure out what the issue was and its not documented anywhere so it might be helpful to remind people.  Since meteor is compiling the typescript code and I assume minifying it.  If your IDE is auto compiling code it will have duplicates of the js files on the server.

**Comment by akhmetgali** [comment]
I don't know why but it's really a problem. I worked this project on WS and catched this errors. Now I'm working in Atom editor and problem was solved.

**Comment by gr4h4n** [comment]
@studiollama Do you know how I can resolve this problem with the Atom IDE ?

**Comment by studiollama** [comment]
@gr4h4n I think you could try adding "compileOnSave": false to you tsconfig file.  Here is where I found this: https://atom.io/packages/atom-typescript

I don't use Atom IDE so I can't confirm if this works or not.

**Comment by gr4h4n** [comment]
@studiollama Thank you, your tip works. I also had to delete all auto compiled .js and js.map files.

**Comment by hayk94** [comment]
@gr4h4n where did you find the auto compiled files?

**Comment by gr4h4n** [comment]
They were located in my working directory. 
So for example when compiling 'hello.ts' -->  'hello.js' and 'hello.js.map' were located in the same directory as 'hello.ts'.

**Comment by hayk94** [comment]
I cannot find them in my working directory thus unable to resolve this problem. Does anybody know where else can these compiled files be?

**Comment by richardmarais** [comment]
hayk94, I have the same problem, did you find where the compiled files are?
