### ISSUE TITLE
Is a version of this package now available under npm?

### ISSUE THREAD

**Issue by rvetere** [Urigo/angular2-meteor#184]
Hi there, i'm trying to teach myself how all of this is working under meteor1.3 with the latest version of the package. So far, i got it running by:

* creating a new project directly with meteor1.3-rc.4
* adding the npm-version of this package by making a github link to the branch #feature/meteor1.3
* adding all the native angular2 packages to the project
* adding the meteor package "angular2-compilers" and removing "blaze-html-templates"

Now, my app will startup fine and ng2 starts to work - and i'm stuck in the next point. I'm trying to separate my UI code from the main project as a package, pretty much the same architecture like the socially demo app will use to build a web.browser client and another ionic one.

My problem is - when i try to define my package with my ng2 code in it. I can't get it running..? When i compare it to the current package written in the socially app, i guess that:

* i don't need a system_config.js anymore, because meteor1.3 together with urigo:anguarl2-meteor is not using system-js anymore, because it switched to webpack internally, right?
* how can i get the "addFiles" running again with .ts files inside?

The main problem i'm struggling right now is, that i need to define a dependency in my package.js like this:

`api.use('urigo:angular2-meteor')`

At this exact point, meteor goes into atmosphere and pulls down the currently released package version which is the one supporting meteor1.2.1, and not the newest one supporting 1.3.

Then i tried to make an `Npm.depends({ 'angular2-meteor': 'github-url' })` - but he complains that it is an unsupported url format - meteor can't use github url's on this level...

So i'm afraid that my setup will only be possible to run, when the angular2-meteor package is available on npm - so i can make i direct dependency in my package.js to this npm package version and it should compile again... am i right?

**Comment by Urigo** [comment]
@rvetere I guess you closed it after you saw the new docs.
Thanks for opening and I hope everything is clear now.

**Comment by rvetere** [comment]
Hi @Urigo, thanks for answering anyway. Oh, i did not see the new docs yet ^^ But i found a different workaround for my problem as i'm working now with a submodule rather than a meteor-package.. and by including the submodule project as hidden folder, i can link exactly the folders i need into my client folder with symlinks - the setup works like a charm now :)

So now i have to look for the new docs..
