### ISSUE TITLE
Move build process (build.sh) to Gulp

### ISSUE THREAD

**Issue by barbatus** [Urigo/angular2-meteor#186]
Reasons: make it neater, make it available for Windows

**Comment by omeid** [comment]
Okay, so it was initially gulp but moved to webpack and now back to gulp? which begs the question of why at this stage, angular2-meteor isn't focused on being a solid angular2 client for meteor that can be installed with npm and used like any other angular2 service?

**Comment by barbatus** [comment]
@omeid Angular2-meteor didn't use gulp before. Look if you don't know difference between gulp and webpack, it's your problem. Second, please avoid asking superficial questions so boldly, have respect for the work of others.

**Comment by rvetere** [comment]
Is it possible to utilize the underlaying webpack (or then gulp in the future :)) config for my specific build needs? Actually i'm wondering how i could have something like the webpack-provide plugin to include jQuery in all my modules during building.. ;)

**Comment by barbatus** [comment]
@rvetere not sure what you mean since Meteor apps have (and will have) jQuery installed by default

**Comment by rvetere** [comment]
@barbatus ah wow, i wasn't aware of that - well more specifically i'm trying to provide "tether" for all my modules since i'm trying to integrate bootstrap 4 alpha.2 ;) i've explained it a little bit more detailed on a stackoverflow thread i just opened today ;)

http://stackoverflow.com/questions/36196388/how-to-provide-tether-anything-else-globally-in-my-meteor1-3-typescript-project

**Comment by barbatus** [comment]
@rvetere there are multiple ways: you could install https://atmospherejs.com/coursierprive/tether, or, 
since Meteor 1.3 prefers NPM now, you could install Tether NPM and require it before you use bootstrap 4, or, if you want more control and modularity, you could create own local package (in the packages folder) with all dependencies (added from NPMs) you need including Tether (similar to the way angular2-runtime done in this repo).

**Comment by rvetere** [comment]
@barbatus awesome! this will definitely help me out with my prototype, thx a lot - now i'm looking forward for my easter hackathon weekend ^^

**Comment by rvetere** [comment]
cool seems to start working now... just another stupid question if i may ask.. in my ng2 prototype, i was just importing css/scss like so:

`import '../../../../../node_modules/dragula/dist/dragula.min.css'`

now meteor1.3 is complaining about "could not find module: ...dragula.min.css" - it seems like there is no loader configured for css in the underlaying webpack..? what is the desired way to implement css/sass in meteor1.3?

**Comment by barbatus** [comment]
@rvetere Current Meteor can't load resources like CSS from installed NPMs. Here is reference to the issue about that https://github.com/Urigo/angular2-meteor/issues/79. It's under development now, and a solution will likely appear in one of the next Meteor releases.
The only way now to fix your issue is copy resources from NPM into one of your app's folder. You can though avoid any effort for copying files manually by automating your build process. As an example, take a look at how one of the users solved similar issues with ng2-material's Sass resources. https://github.com/Urigo/angular2-meteor/issues/171#issuecomment-200299659

**Comment by rvetere** [comment]
cool, thx for all the resources :) one last thing to ask right now: is it possible to have a

`require('./app.html')`

in my code? under my existing webpack build that was no problem, but meteor1.3 is complaing "cannot find module".. sry for the off-topic stuff i'm asking here..

**Comment by Urigo** [comment]
@omeid I'm sorry for @barbatus response.
This is not the way we should respond to question and comments by users.
As for your question, we used webpack but for a different task, now we use gulp for another.
also, we are being focused on release Angular2Meteor as an Npm package, and we acctually did it thanks to @barbatus great work - https://www.npmjs.com/package/angular2-meteor
With the new Meteor 1.3 you will see that your experience would be very similar to the rest of the Javascript community.
Please feel free to keep asking whatever questions you like.

**Comment by omeid** [comment]
Hey @Urigo, You don’t need to apologize for other people’s character, or lack thereof. :)

Thanks for your detailed answer. My impression of the build initially being gulp and moved to webpack was based on #105. I wasn’t quite sure of what this issue entailed from the initial 

> Move build process to Gulp

title and thus the question and the subsequent suggestion.

Let me clarify on my suggestion, while it is possible to install Angular2-Meteor with npm, it stil assumes to be used within a Meteor application. What I think would be ideal is to break the Angular2 Meteor integration, basically the glue between Meteor Client and Angular2, into a separate package that one can install like any other angular2 service, but I understand that it would require to include the Meteor Client library (including minimongo) and other as well for this to work, basically something along the lines of [idanwe/meteor-client-side](https://github.com/idanwe/meteor-client-side).

This would also make it possible to use angular2-meteor with ionic apps, which is mostly what I want out of this. :)

Thoughts?

**Comment by Urigo** [comment]
@rvetere it is not yet possible for the same reason as issue #79 .
I hope it will be solved soon in Meteor 1.3.1

@omeid that's a good point. yes I really want to do that soon.
It mostly mean having a version of https://github.com/idanwe/meteor-client-side with Meteor 1.3
We will get to that but in the meantime would love help with that as everything is open source (meteor-client-side and the tutorials) and maybe someone could help with that.
Anyway, I think it's a good point and maybe you can open a separate issue so we could track that?

**Comment by omeid** [comment]
@Urigo  Done. :)
To get `ionic` hosted in meteor, I opened #225.
