### ISSUE TITLE
Step 0 - Bootstrapping docs seem to be in error

### ISSUE THREAD

**Issue by robertlight** [Urigo/angular2-meteor#188]
I'm starting out with angular2-meteor using the page:

http://ng-meteor.meteor.com/tutorials/angular2/bootstrapping

(note the "Improve this doc" link is a 404)

I found that I had to depart from the doc on the step 0.8 "Add a reference to the declaration file"

I had to use the file as:
```javascript
/// <reference path="../typings/angular2-meteor/angular2-meteor.d.ts" />

import {Component, View} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
 
@Component({
    selector: 'app'
})
@View({
    templateUrl: 'client/app.html'
})
class Socially { }
 
bootstrap(Socially);
```

In order to get things to startup without errors.

question:  Am I using the most current doc-set?  As a newbee...where should I begin?

**Comment by barbatus** [comment]
the tutorial is located here http://www.angular-meteor.com/tutorials/socially/angular2.
You are using some old test version, don't know where you found it.
The right version contains all information you need.

**Comment by robertlight** [comment]
Thank you !!

Yeah,  I finally stumbled upon the link you provided.

You should get rid of the stuff at:
http://ng-meteor.meteor.com/tutorials/angular2/bootstrapping

It'll keep causing you heart ache until it's toast.

**Comment by Urigo** [comment]
@barbatus can we remove this site or redirect it back to angular-meteor.com?
I think you are the owner?
Also, I think Meteor will remove it anyway sometime soon with the deprecation of Mother...
