### ISSUE TITLE
seems to be an error in Step 3 - 3-Way data binding

### ISSUE THREAD

**Issue by robertlight** [Urigo/angular2-meteor#189]
I am using:
http://ng-meteor.meteor.com/tutorials/angular2/3-way-data-binding

I have found that I get the error:
[web.browser] collections/parties.ts (3, 26): Cannot find name 'Mongo'.

To get rid of the error, I had to do:
npm install typings -g
typings install meteor --ambient
typings install es6-promise --ambient
typings install es6-shim --ambient

and then add the following to my file:  collections/parties.ts
`/// <reference path="../typings/main.d.ts"/>`

in order to get rid of the error message.

**Comment by barbatus** [comment]
the tutorial is located here http://www.angular-meteor.com/tutorials/socially/angular2.
You are using some old test version, don't where you found it.
The right version contains all information you need.

**Comment by Urigo** [comment]
related to https://github.com/Urigo/angular2-meteor/issues/188
