### ISSUE TITLE
Problems with *.e2e.ts and *.spec.ts files in my meteor1.3 ng2 project

### ISSUE THREAD

**Issue by rvetere** [Urigo/angular2-meteor#190]
i was using the component folder structure so far where we put also the test files directly into the component folder.

now i know you can exclude files/folders in meteor only by hiding them in the filesystem (put a . in front of the name).. it seems quirksy to me that i'll have to rename/hide all my test typescript files in my existing code so meteor won't pick them up in runtime.

my first thought was, maybe i can exclude the file pattern by the exclude option of my tsconfig.json:

`
"exclude": [
      "**/*.e2e.ts"
   ]
`

but it doesn't change anything unfortunately - that would be awesome if it could be handled like this :) or is there already another workaround?

**Comment by barbatus** [comment]
What if you put them in a folder named `tests`.

**Comment by rvetere** [comment]
yeah i solved it this way now.. i just thought it is a really neat pattern to put all into the component folder when i'm using the component folder structure anyway ;)

**Comment by barbatus** [comment]
you can put them in the `imports` folder to avoid eagerly running them (see http://guide.meteor.com/testing.html#simple-unit-test)
Guess, it's solved now.
