### ISSUE TITLE
Unable to resolve module: angular2-meteor/mongo_cursor_differ

### ISSUE THREAD

**Issue by slevr** [Urigo/angular2-meteor#193]
It appears the recent change to the build is causing some issues. angular2-meteor-auto-bootstrap is looking for mongo_cursor_differ in the rroot of /angular2-meteor where it used to be located. Now it's only under angular2-meteor/build so it's not finding it. Assuming this is a build script error not moving the files out from under build?

**Comment by barbatus** [comment]
How do you install it? Try `npm install angular2-meteor` and `npm install angular2-meteor-auto-bootstrap` instead.

**Comment by slevr** [comment]
Must be losing my mind - I guess from too many times performing an install. Files were in the appropriate place this time around.

**Comment by Devidian** [comment]
got the same error at my office after all the updates. Just removed the git links in my package.json and installed it from npm directly: Working! Thanks!
