### ISSUE TITLE
beta-12 excepts with "Cannot read property 'fork' of undefined" in NgZone

### ISSUE THREAD

**Issue by rvetere** [Urigo/angular2-meteor#195]
Ok i restarted again.. updated first my meteor project to meteor.1.3-rc.13.. then updated to the official releases of "angular2-meteor" and "angular2-meteor-auto-bootstrap", i was still using the github url variant before.. Then i've updated manually all basic packages of angular2 (es6-promise/shim, reflect, zone, rxjs)

And now it looks quite promising, the startup tells me lot more now about my package situation (i was using a meteor package auth0:lock as an experiment, he tells me i should replace it with an npm install --save call giving me all dependencies of it from npm, that's awesome!)

i only got a warning during startup of one of my integrated packages, not really a problem i guess.. and now the "mongo_cursor_differ" error is gone, but i have a new one:

https://www.dropbox.com/s/gzjuwsc4e5s4rkh/Screenshot%202016-03-28%2014.04.05.png?dl=0

In my angular2 code, the part in NgZoneImpl is excepting `this.inner.fork`:

https://www.dropbox.com/s/7rf7dkoakqckqqg/Screenshot%202016-03-28%2014.40.11.png?dl=0

**Comment by barbatus** [comment]
Make sure that you are using angular2-compilers@0.5.4 and Angular2-beta.12.

**Comment by rvetere** [comment]
Thanks for your answer - i'm slowly getting behind the problem, i'm totally sure now it is not based on the new packages of angular2-meteor or anything else npm related..  Can be closed i think ;)

**Comment by rvetere** [comment]
Ok now i got a real question. After updating my isolated ng2 project to beta.12, it was not running anymore.. that was the also the reason why my meteor project stopped working in first place.

Now i integrated all changes from the ng2 seed project i'm using, and they made some really awesome stuff lately.

They moved a part which should be globally available into a "platform" folder which is delivering basic directives and providers -> also the ones they wanna use from angular2/core.

Now, platform is just a folder with some .ts files defining some classes. The folder has a central "index.ts" which is only defining/giving all exports of the folder, or maybe a "package" now..

index.ts:
`export * from './directives';`
`export * from './pipes';`
`export * from './providers';`

And then, the main app.ts is importing all of them just by using:

`import {DIRECTIVES, PIPES, PROVIDERS} from './platform';`

So, this is working wonderfully in my isolated webpack-driven setup.. but as soon as i pack all that stuff into my meteor1.3 project, he will complain:

`Uncaught Error: Cannot find module './platform/browser'`

And i understand him... there is no module defined for this import path.. right? webpack can resolve this dynamically somehow... How can i define that for my meteor1.3 project?

**Comment by barbatus** [comment]
Yr file is `platform/browser/index`, not `platform/browser`. Import everything from it. Meteor doesn't recognize any index files. If you want to learn more about package development in Meteor 1.3, read here http://guide.meteor.com/writing-packages.html. You don't need actually specify all files now in `addFiles`,, since Meteor will be processed now all files in the package folder. Also forget about `system_config.js`, SystemJS won't be used any more from Meteor 1.3 on.

**Comment by rvetere** [comment]
Thanks for your patience and cool link, i definitely want to get more into package development. I got it working now by importing my few classes directly in the bootstrap file of my meteor1.3 package, neat enough for the moment ;)
