### ISSUE TITLE
Cannot find module 'angular2-meteor-auto-bootstrap'

### ISSUE THREAD

**Issue by derekkite** [Urigo/angular2-meteor#196]
I've installed the npm module. What typings/ file refers to this module?

**Comment by omeid** [comment]
Does your tsconfig has `moduleResolution` set to `node` for  `compilerOptions`?

**Comment by thinkrapido** [comment]
I have the same issue.
I added moduleResolution node. Issue still present.

**Comment by dotansimha** [comment]
Which IDE do you use?

**Comment by dotansimha** [comment]
Also, do you use Angular2-meteor from NPM or from Atmosphere?

**Comment by thinkrapido** [comment]
I use sublime and 

> meteor npm install --save ...

**Comment by dotansimha** [comment]
Maybe these related? 

https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/213
https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/207

I use WebStorm and everything works fine...
