### ISSUE TITLE
angular2-compilers creating .js.map and .js files when used within package.

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular2-meteor#199]
Using meteor 1.3 and angular2-meteor from npm within a package with ```angular2-compilers@0.5.4```. Every time I save a .ts file it creates a .js.map file with a .js file.

**Comment by omeid** [comment]
It is probably your code editor.

**Comment by vacarsu** [comment]
I'm using atom and it wasn't doing this with meteor 1.2 outside of a package.

**Comment by omeid** [comment]
Please create a reproduction repo if possible. I don't see such issue with `angular2-compilers@0.5.4`.

**Comment by omeid** [comment]
Try editing a ts file with some other editor and see if you have the same issue.

**Comment by vacarsu** [comment]
Updated typescript package for Atom, seems to be working properly now.
