### ISSUE TITLE
Need better error reporting.

### ISSUE THREAD

**Issue by robertlight** [Urigo/angular2-meteor#201]
I have been getting the infuriatingly terse "Uncaught SyntaxError: Unexpected token <" error.

I was doing the "socially" tutorial...

There was no error displayed to meteor's stdout and nothing was rendered to the screen.  

I finally figured it out but it's clear that either I'm not looking in the right places, or meteor is not printing out useful error information.   I've zipped up directory for later diagnosis if you need more info.  

Here goes:

In app.ts, if I use the line:

`import {PartyDetails} from 'party-details/party-details';` 

I get the error message above, and I get nothing to stdout. I also get nothing to the browser.

If I use:

`import {PartyDetails} from 'foobar/party-details/party-details';`  

I get the error message: 

> [web.browser] client/app.ts (9, 28): Cannot find module 'foobar/party-details/party-details'.

There are only three variants of that import that work...they are:

```javascript
import {PartyDetails} from 'client/party-details/party-details';
import {PartyDetails} from '/client/party-details/party-details';
import {PartyDetails} from './party-details/party-details';`
```
but the following fails:
```javascript
import {PartyDetails} from 'party-details/party-details';
```

**Comment by barbatus** [comment]
I assume you used some old version of Angular2-Meteor at the moment (probably with SystemJS), since with modules resolution set to node (in Meteor 1.3) it should always complain in situation like this.
Please update (if not already) to the latest versions.
