### ISSUE TITLE
ReferenceError: require not defined

### ISSUE THREAD

**Issue by rweng** [Urigo/angular2-meteor#202]
Hi, I am getting `app.ts:1Uncaught ReferenceError: require is not defined`, which is caused by the compiled `import {bootstrap} from "angular2/platform/browser";`

`Meteor.release` gives me `"METEOR@1.3"`. It say in the Readme, that System.import isn't necessary anymore w/ Meteor 1.3. Am I missing something?

**Comment by rweng** [comment]
`meteor add modules` solves it.

**Comment by muvic08** [comment]
Thanks rweng, meteor add modules solved it for me too.
