### ISSUE TITLE
Struggling with pre-rendering

### ISSUE THREAD

**Issue by rvetere** [Urigo/angular2-meteor#203]
Hi awesome folks of meteor.. I'm struggling a bit in a certain topic. The company i'm working for is in the decision process for a complete new stack, which is awesome and a big chance! Now, it is coming down to a setup with express, angular2/react.js and, almost most important, it must be prerendered and isomorphic.

When it comes down to isomorphism, i instantly thought on meteor - i never saw a better implementation of true isomorphism like here! But now i'm investigating in the fields of pre-rendering our angular2 prototype.

On express, this looks quite promising - there are wonderful seed projects and packages like [preboot](https://github.com/jeffwhelpley/preboot) which already supports express, or also hpi or a gulp task or whatever, but not meteor.

Now i'm just curious what the pro's here think about this topic - where will the train be heading..? I guess pre-rendering is also a big thing for the meteor community nowadays and.. i'm still at the beginning with my learning curve about meteor itself.

Then on the other side i've a cool talk about an angular2 app on express, doing a "kind-of" connected client architecture with firebase, and it feels great, reactive but has no meteor in it.. Should i give it a try..? I don't know.. i'm already a fanboy of meteor and i belive in this stack. It's only.. as far as i don't have anything to come up with in my company regarding pre-rendering, i don't have to present my meteor stack to them :D

So, i'm really curious what the community here is thinking about those parts.

**Comment by Urigo** [comment]
@rvetere yes we are on it.  you can track it here - https://github.com/Urigo/angular2-meteor/issues/82

I hope we will get to that soon.  it shouldn't be too hard though because if there is a working solution for other Node frameworks, Meteor won't be that different.
If it's something that needs to happen really soon, we would love some help pushing that forward
