### ISSUE TITLE
No provider for e! after build

### ISSUE THREAD

**Issue by Devidian** [Urigo/angular2-meteor#204]
Hey guys, i just tried to build our current project and got an error on the frontend:

`No provider for e! (e -> e) in [(isOnline && user._id) || !isOnline in e@17:15]`

This points to following code in my main app template:

`<router-outlet *ngIf="(isOnline && user._id) || !isOnline"></router-outlet>`

in development mode with `meteor` there are no problems and anything is working as expected.
The `node main.js` on the server is running without problems too, just the frontend is not.

Any Ideas ?

here is a link to my test build: http://build.ethomat.com/

**Comment by Hongbo-Miao** [comment]
Probably duplicated with https://github.com/Urigo/meteor-angular2.0-socially/issues/36

**Comment by barbatus** [comment]
That's minification issue, check out this https://github.com/Urigo/angular2-meteor#it-works-fine-locally-but-fails-to-run-in-the-production.

**Comment by Devidian** [comment]
ok thanks! I just commented `#standard-minifier-js` for now and got it working!
