### ISSUE TITLE
Module '"angular2/core"' resolves to a non-module entity and cannot be imported using this construct.

### ISSUE THREAD

**Issue by mjwheatley** [Urigo/angular2-meteor#205]
All was going fine until I imported MeteorComponent from angular2-meteor, added extends MeteorComponent to my class, and called super() in the constructor.
I am also trying to use Ionic2 and don't know if that is part of the problem or not.
Here is a [link to my project](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter)
and a code snippet.

```
import {MeteorComponent} from 'angular2-meteor';
@App({
    templateUrl: '/client/app.html',
    config: { } // http://ionicframework.com/docs/v2/api/config/Config/
})
class MyApp extends MeteorComponent {
    constructor(private app:IonicApp,
                private platform:Platform,
                private zone:NgZone) {
        super();
    }
}
```

My tsconfig.json
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "sourceMap": true
  },
  "files": [
    "typings/main.d.ts",
    "typings/angular2-meteor/angular2-meteor.d.ts"
  ]
}
```

**Comment by barbatus** [comment]
You don't need to use typings directly (like `angular2-meteor`, `angular2`) in Meteor 1.3 since they are picked by the compiler from NPMs automatically. Cleanup your typings folder and try again.

**Comment by mjwheatley** [comment]
I deleted the typings folder and removed the "files" from the tsconfig.json and I get
```
Module '"angular2/core"' resolves to a non-module entity and cannot be imported using this construct.
Cannot find name 'Meteor'
Cannot find name 'Tracker'
``` 

The compiler doesn't seem to be picking up the typings from the node modules.
Can you take a look at my [versions](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/blob/master/app/.meteor/versions) and let me know if I have any conflicts.
I am using angular2-compilers@0.5.4

Any other reason why the compiler wouldn't load the typings automatically?
