### ISSUE TITLE
angular2-meteor compilation typescript error

### ISSUE THREAD

**Issue by aelmottaki** [Urigo/angular2-meteor#207]
hiii
I have been getting somme errors when i run my angular2-meteor app and  when i searched i found that there is a defference between  compiled source code in  directory .meteor/local/build/programs/server/app.js and my real code
i noticed that the compiler keeps old version of my code 

i use compiler package barbatus:typescript-compiler@0.5.0

**Comment by MilosStanic** [comment]
Me, too. After deleting some lines reported in server console, and sever restart, I get same error reports on the line I just deleted.

**Comment by barbatus** [comment]
update to the last angular2-compilers, it should be fixed there.
