### ISSUE TITLE
Discussion: template transformer DSL for Meteor.

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular2-meteor#21]
Hello everyone,

I post this in the hope to get your ideas and to start a discussion on template transforms for Minimongo queries.

I've learned about template transforms on angular connect (see: https://www.youtube.com/watch?v=bVI5gGTEQ_U#t=914 , minute 15.10 till 21.00 ) and it seems like this would be a good fit for minimongo queries.

**Comment by barbatus** [comment]
That'd would be awesome feature. Hopefully we'll implement it soon with new Angular2 versions.

**Comment by sclausen** [comment]
Wow! Angular2 keeps impressing me again and again! This would be so amazing to see!

**Comment by pgrm** [comment]
Hi, I just found this when I was trying to find more about those awesome transformers - I assume they haven't been implemented and we can close this issue. But maybe some of you have more insights why it wasn't implemented or if it was just postponed / renamed? thx

**Comment by sebakerckhof** [comment]
TBH, that talk was from a year ago and meanwhile angular has changed so much that I don't know what parts of it are still relevant

**Comment by dotansimha** [comment]
This issue was moved to Urigo/angular-meteor#1478
