### ISSUE TITLE
examples todos-meteor-1.3 : Cannot find name 'Meteor , and a lot of errors at startup like this one

### ISSUE THREAD

**Issue by Rebolon** [Urigo/angular2-meteor#211]
I'm trying to run the examples/todos-meteor-1.3 and i have some outputs on startup even if the app seems to run correctly. Is it normal ?

Compiling main app HTML file: client/index.html
Compiling HTML template: client/components/task-list.html
Compiling HTML template: client/components/task.html
Compiling HTML template: client/app.html
client/components/task-list.ts (1, 43): Cannot find module 'angular2/core'.
client/components/task-list.ts (5, 31): Cannot find module 'angular2-meteor'.
client/components/task-list.ts (15, 10): Cannot find namespace 'Mongo'.
client/components/task-list.ts (22, 10): Property 'subscribe' does not exist on type 'TaskList'.
client/components/task.ts (1, 32): Cannot find module 'angular2/core'.
client/components/task.ts (3, 31): Cannot find module 'angular2-meteor'.
client/components/task.ts (10, 24): Cannot find name 'Task'.
client/components/task.ts (13, 10): Property 'call' does not exist on type 'TaskView'.
client/components/task.ts (18, 10): Property 'call' does not exist on type 'TaskView'.
client/components/task.ts (23, 10): Property 'call' does not exist on type 'TaskView'.
client/app.ts (1, 50): Cannot find module 'angular2/core'.
client/app.ts (7, 25): Cannot find module 'angular2-meteor-auto-bootstrap'.
tasks.ts (1, 24): Cannot find name 'Mongo'.
tasks.ts (3, 1): Cannot find name 'Meteor'.
tasks.ts (31, 5): Cannot find name 'Meteor'.
tasks.ts (32, 3): Cannot find name 'Meteor'.
tasks.ts (1, 24): Cannot find name 'Mongo'.  -
tasks.ts (3, 1): Cannot find name 'Meteor'.
tasks.ts (31, 5): Cannot find name 'Meteor'.
tasks.ts (32, 3): Cannot find name 'Meteor'.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

I did this before running the app :
 * meteor npm install  --save  angular2@2.0.0-beta.12 angular2-meteor angular2-meteor-auto-bootstrap
 * typings install meteor --ambient

**Comment by barbatus** [comment]
This only can happen if NPMs have not been installed correctly and absent in the `node_modules`.
I have no errors when I run fresh ToDo demo with `npm install`, `meteor`.
Please, verify that your NPM installation is correct before running meteor, also
update to the last typescript by running `meteor update`.

**Comment by Urigo** [comment]
As I've answeredyour question here: https://forums.meteor.com/t/meteor-angular2-import-meteor-from-meteor-meteor-cannot-find-module/20985/4?u=urigo

Please look at the end of the first chapter. it links to that gist here - https://gist.github.com/tomitrescak/8366ce98f1857e202ea813 which is an updated version of the Meteor typings for Meteor 1.3
let me know if that works for you

This is the related issue: https://github.com/meteor/meteor/issues/61777


It solved your question there so I'm closing.
Feel free to open a new issue if there is another problem
