### ISSUE TITLE
Random errors:  "Cannot find module 'angular2/core'

### ISSUE THREAD

**Issue by denodaeus** [Urigo/angular2-meteor#218]
Greetings,

When bootstrapping a new project, I commonly see these warnings:

```shell
client/app-header/app-header.component.ts (11, 27): Cannot find module 'angular2/core'.
client/app-menu/app-menu.component.ts (13, 27): Cannot find module 'angular2/core'.
client/app-menu/app-menu.component.ts (14, 28): Cannot find module 'angular2/router'.
client/footer/footer.component.ts (13, 25): Cannot find module 'angular2/core'.
```

When I actually load the app, everything seems to work just fine.  Is there any way I can get these to go away?

**Comment by denodaeus** [comment]
Things I've tried:

1) Removing all typings in the project (tic complains about not finding Meteor)
2) Installing just the meteor typings (that goes away, but still angular2 complaints)
3) Following the walkthrough on the readme step by step.

It doesn't seem to be breaking anything but my IDE support (Visual Studio Code), and it's super annoying.  This has to be around typings and not finding the angular2 ones, and the tsconfig.  Any suggestions?

**Comment by denodaeus** [comment]
It seems like this issue just keeps coming randomly back, and it's the typescript compiler that complains (not the IDE) -- when I clean all the npm packages out of my project and reinstall them, the problem magically goes away for a few hours, until my IDE breaks showing that it can't find the module due to:

'angular2/core' resolves to a non-module entity and cannot be imported using this construct

**Comment by Urigo** [comment]
@denodaeus can you share a reproduction?
also, are you using Meteor 1.3 and the latest version of the tutorial as your guideline?

**Comment by denodaeus** [comment]
I will create a branch and share it sometime tomorrow, but it's simple to reproduce:

Run the meteor command to start meteor from a subdirectory of the root of the project.  In the *old* directory structure, if I run this in /client, I immediately get a "angular2/core" not found TS error, as well as other angular2-meteor related modules (such as angular2-meteor-auto-bootstrap)

**Comment by barbatus** [comment]
@denodaeus do you run `npm install` before running meteor?

**Comment by barbatus** [comment]
There was some issue with the ts-compiler cache; and this one is likely related.
Please update to the last version, if it's not fixed - re-open.
