### ISSUE TITLE
Error: More tasks executed than were scheduled (angular2 bug)

### ISSUE THREAD

**Issue by denodaeus** [Urigo/angular2-meteor#221]
<img width="1435" alt="2016-04-07_1218" src="https://cloud.githubusercontent.com/assets/249286/14358516/48225a5a-fcbb-11e5-8715-a04eac82a7a5.png">

https://github.com/angular/angular/issues/7721

Can you guys update to angular2 beta-13 (and the fix with zone.js should come with it)

**Comment by denodaeus** [comment]
![2016-04-08_0114](https://cloud.githubusercontent.com/assets/249286/14374737/563d1d70-fd27-11e5-80a2-4a4297255897.png)

**Comment by denodaeus** [comment]
https://github.com/angular/angular/issues/7721

There are a few fixes/work around towards the bottom of the thread, but they all involve ditching angular2-polyfills and pulling the latest zone.js

**Comment by barbatus** [comment]
Fixed in zone.js v0.6.10
