### ISSUE TITLE
Bug in TypeScript compiler?

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular2-meteor#223]
First, excuse me, because I don't know if this is a right place to post this question. 

I'm working on a serverside code in TypeScript and I'm getting an error, which I shouldn't be. First I'm defining an interface like this: 
```typescript
interface myType { 
    prop1: string;
    prop2?: number;
}
```
then later in code, if I do the following: 
```typescript
let a : myType;
a.prop1 = 'somestring';
```
I get an error in server console: `cannot set property 'prop1' of undefined`
but if I rewrite it to: 
```typescript
let a: myType;
a = { prop1: 'somestring'};
```
it works without error. Is that a bug in TypeScript compiler?

**Comment by MilosStanic** [comment]
got my answer in Gitter, it's not a bug.

**Comment by Urigo** [comment]
@MilosStanic the thing I don't like about gitter is that the answer is not public...
can you please share your solution so other will be able to search on Google and find it?
thanks

**Comment by MilosStanic** [comment]
Well, it is public for people who are on Gitter. :)
In this case I did not actually have a problem, but it was my lack of knowledge of TypeScript. 

Here is the conversation from Gitter: 

Chris Glace Apr 08 17:00
In example one you did not set a equal to 'a' myType you just said that it will be of type myType

Miloš Stanić Apr 08 22:29
@cglace I'm not sure I understadn what you said. In both examples I declared a to be of type myType, and in the next line (but in the actual code, it's somewhere way later), I set the property of a named prop1 to be equal to 'somestring'. So I don't understand why the first one throws error, and the second one works. As far as I read in some tutorials, both should work.

Chris Glace Apr 08 22:30
Because you only declared that it will be that type
you did not instantiate it with an object of that type
in the second example you immediately assign an object that matches the interface of myType
let a : myType; is the same as writing var a; In both instances a will be undefined.

Miloš Stanić Apr 08 23:51
@cglace is there a way to instantiate the variable immediately upon declaration in the first example, something like let a: myType = new myType ?

Chris Glace Apr 08 23:54
@MilosStanic let a : myType = {prop1: 'someString'}; should work

Miloš Stanić Apr 08 23:55
@cglace yes, but the value of prop1 is not known until much later in the code, in my case.

Chris Glace Apr 08 23:57
oh Then what you did in example two should be fine

Miloš Stanić Apr 08 23:58
ok, thanks a lot, sorry for bothering you

Chris Glace Apr 09 00:11
@MilosStanic No problem. Any time.

Hongbo Miao Apr 09 00:35
@MilosStanic I think let a: myType = {prop1: ‘’}; then set prop1 later,
or maybe add ? in the interface
interface myType { prop1?: string; prop2?: number; }

Miloš Stanić Apr 09 00:36
@Hongbo-Miao yes, that could also be it. Can you set all props with ? questionmark?

Hongbo Miao Apr 09 00:38
or I will wait prop1 is ready, and then let a : myType = {prop1: 'someString'};
