### ISSUE TITLE
Meteor 1.3.2.1 Ionic Integration 

### ISSUE THREAD

**Issue by omeid** [Urigo/angular2-meteor#225]
Just opening this issue to share what is possible and what needs to be followed up for a clean meteor + ionic integration using this project.

Ionic 2 is released in npm under `ionic-angular`, so the first step is to install it with npm:

```
npm install ionic-angular@^2.0.0-beta.3 --save
```

Ionic 2 stylesheet's assumes the parent node is called `ion-app`, so one needs to use that as a selector for the 'App' component and include an index.html

This will do just fine:
```html
<body>
  <ion-app></ion-app>
</body>
```

Currently, as mentioned in driftyco/ionic#6078, using `@App` provided by Ionic results into an error because it bootstraps the _App_ automatically and the bootstrapping calls `ionicProviders()` which assumes DOM is ready, this could be improved, but for now, you need to do

```typescript
Meteor.startup( ()=> {
   bootstrap(App, ionicProviders());
})
```
to pass the ionic providers to your component.

The css/scss, ~~until meteor/meteor#6037 fix lands in a release~~, until driftyco/ionic#6163 is merged in, you can not use the scss files. :(
Work around is to simply create links from `client/stylesheets` to `ionic.ios.css`, `ionic.md.css`, and `ionic.wp.css` under `node_modules/ionic-angular`.

A super bare basic example:

```typescript
import {Component} from 'angular2/core';

import {Meteor} from 'meteor/meteor';

import {IonicApp, Platform} from 'ionic-angular';


import {bootstrap} from 'angular2-meteor-auto-bootstrap';
import {IONIC_DIRECTIVES, ionicProviders} from 'ionic-angular';




@Component({
    selector: 'ion-app',
    templateUrl: 'client/app.html',
    //config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
    directives: [IONIC_DIRECTIVES]
})

class App {

    constructor(
        private app: IonicApp,
        private platform: Platform
    ) {

        this.initialize();

    }

    initialize() {
        this.platform.ready().then(() => {
            console.log("Ionic Platform Ready.");
        });
    }

}


Meteor.startup( ()=> {
    bootstrap(App, ionicProviders());
})

```

 Hope this helps with the Tutorial, or anyone else who wants to get started with Ionic and Meteor.

**Comment by hlehmann** [comment]
Yes it's mostly what I have done. But it doesn't take in considerations others functions inside Ionic @App décorator, and upcoming changes.
We should create an other package with a new @App decorator following the original but overriding the bootstrap part.
I could do so but I'm not sure of the best way, @Urigo a PR here or create a new repo (meteor-ionic2) ?

**Comment by omeid** [comment]
I don't think creating yet another package is the way to go. The whole point of supporting npm in Meteor 1.3 is to avoid this wrapper packages and having to deal with their maintenance.

I think the Ionic issue needs to be addressed instead of creating a glue package.

**Comment by vohtaski** [comment]
@omeid thanks for the wrap-up! Very useful.
Do you have by chance a bit more extended example
with a couple examples? Maybe similar to ionic2 tutorial?

**Comment by shaneseaton** [comment]
@vohtaski Try this as a starter https://github.com/ntrp/meteor-ionic-angular2-starter

I found it the other day. Worked well for me.

**Comment by omeid** [comment]
@vohtaski You're welcome. Glad it was of any help.
Unfortunately, I don't have the time to study the how-to of the Tutorial and writing up the section, but @Urigo and other guys are doing a great job of it and the [official tutorial](http://www.angular-meteor.com/tutorials/socially/angular2)  is only a few steps away from Ionic integration part.

**Comment by vohtaski** [comment]
@omeid I don't really need a tutorial, the official tutorial is amazing :)
My problem is that the config you gave above works only partially with ionic.
Seems as the components/directives from ionic are not run.

For example in the tutorial from ionic site. The `ion-navbar` is replaced with `<div></div> and and `menuToggle` does not work. The navigation between pages is working well though.
Seems like components/directives are not initialized in my case.
```html
<ion-navbar *navbar>
  <button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
  <ion-title>Hello Ionic</ion-title>
</ion-navbar>


<ion-content padding class="getting-started">

  <h3>Welcome to your first Ionic app!</h3>

  <p>
    This starter project is our way of helping you get a functional app running in record time.
  </p>
  <p>
    Follow along on the tutorial section of the Ionic docs!
  </p>
  <p>
    <button primary menuToggle>Toggle Menu</button>
  </p>

</ion-content>
```

**Comment by mjwheatley** [comment]
I have a [starter project](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter) in which I successfully integrated the SCSS from the ionic-angular node module.  I also implemented internationalization into the project using ng2-translate and have a language toggle.

**Comment by Urigo** [comment]
thanks for the answers guys!
