### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by ujinv** [Urigo/angular2-meteor#227]
After update to meteor 1.3 and making all that stuff with npm (following angular-meteor guide at http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping) I always get the following error when I start meteor:
<skip all the 'Cannot find name : Meteor' and 'Cannot find module: collections/collectionname' >
`ReferenceError: exports is not defined`
This error is emitted for every source file (although compiler exits when the first one is found) that exports any object (class and interface exports are OK).
I've double checked to remove all angular2 and babel/typescript packages before running through the official guide. I've also changed proper entries in tsconfig.json.
Is there any migration guide for angular2-meteor projects around?
```
=> Exited with code: 8

C:\Users\ujin\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245

throw(ex);
      ^
ReferenceError: exports is not defined
at collections/agentscollection.ts:2:14
at collections/agentscollection.ts:2:70
at c:\Devel\!scada\.meteor\local\build\programs\server\boot.js:283:10
at Array.forEach (native)
at Function._.each._.forEach (C:\Users\ujin\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
at c:\Devel\!scada\.meteor\local\build\programs\server\boot.js:133:5
```

**Comment by barbatus** [comment]
I'll need `modules` installed, also it's added in the last version of `barbatus:typescript`.
