### ISSUE TITLE
Collection FS

### ISSUE THREAD

**Issue by janibekm** [Urigo/angular2-meteor#229]
hello! I was trying to use gridFS or collectionFS to angular2. So angular-meteor com step 20 is not written yet, when we can use collectionFS, it is possible now use angular2. If it is possible, can you explain how to use it for some example. Thank you! 
any idea!

**Comment by MilosStanic** [comment]
@janibekm hold on to that decision. CollectionFS is not being maintained any more, so angular-meteor team is looking for a viable alternative and it will be incorporated into chapter 20.

**Comment by ThomsCass** [comment]
You can use filestack is awsome and so more simple than CFS !

**Comment by barbatus** [comment]
Since NPM doors are now open, you can find now bunch of alternatives.
CollectionFS is frozen now.
