### ISSUE TITLE
Cannot find module 'angular2-meteor-auto-bootstrap

### ISSUE THREAD

**Issue by audan2009** [Urigo/angular2-meteor#230]
Hello,

I'm getting an error Cannot find module 'angular2-meteor-auto-bootstrap. I saw issue #196 but it did not help.  I'm not step 3 of the Angular2-meteor socially tutorial. I am on Meteor 1.3.1

My tsconfig file looks like this:

` "atom": {
    "rewriteTsconfig": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "classic",
    "experimentalDecorators": true
  },
  "filesGlob": [
    "**/*.ts"
  ],
  "files": [
    "client/app.ts",
    "collections/parties.ts",
    "node_modules/angular2-meteor-auto-bootstrap/bootstrap.d.ts",
    "node_modules/angular2-meteor-auto-bootstrap/build/bootstrap.d.ts",
    "node_modules/angular2-meteor-auto-bootstrap/build/index.d.ts",
    "node_modules/angular2-meteor-auto-bootstrap/index.d.ts",
    "node_modules/angular2-meteor-auto-bootstrap/modules/bootstrap.ts",
    "node_modules/angular2-meteor-auto-bootstrap/modules/index.ts",
    "node_modules/angular2-meteor/build/cursor_handle.d.ts",
    "node_modules/angular2-meteor/build/index.d.ts",
    "node_modules/angular2-meteor/build/meteor_component.d.ts",
    "node_modules/angular2-meteor/build/mongo_cursor_differ.d.ts",
    "node_modules/angular2-meteor/build/mongo_cursor_observer.d.ts",
    "node_modules/angular2-meteor/cursor_handle.d.ts",
   .....`

The app.ts file looks like this:

`import 'reflect-metadata';
import 'zone.js/dist/zone';
import {NgZone, Component} from 'angular2/core';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import {Parties} from '../collections/parties';
import {Tracker} from 'meteor/tracker';

@Component({
  selector: 'app',
  templateUrl: 'client/app.html'
})
class Socially {

  parties: Array<Object>;

  constructor (zone: NgZone) {
    Tracker.autorun(() => zone.run(() => {
      this.parties = Parties.find().fetch();
    }));
  }
}

bootstrap(Socially);`

Thank you!

**Comment by audan2009** [comment]
When I changed "moduleResolution": "classic" to "moduleResolution": "node" that error went away and I got a different one.

Module angular2/core resolves to a non-module entity and cannot be imported using this construct

**Comment by derekkite** [comment]
tsconfig.json

`{
	"compilerOptions": {
		"experimentalDecorators": true,
		"module": "commonjs",
		"target": "es5",
		"moduleResolution": "node",
		"emitDecoratorMetadata": true,
		"sourceMap": true
		
		},
		"files": [
		"typings/main.d.ts",
		"typings/events.d.ts",
		"typings/contacts.d.ts",
		"typings/filesgathered.d.ts"
		]
	}`

typings/main.d.ts
`/// <reference path="main/ambient/babyparse/babyparse.d.ts" />
/// <reference path="main/ambient/es6-promise/es6-promise.d.ts" />
/// <reference path="main/ambient/es6-shim/es6-shim.d.ts" />
/// <reference path="main/ambient/lodash/lodash.d.ts" />
/// <reference path="main/ambient/meteor/meteor.d.ts" />
`

Ignore my project specific stuff. If I had the angular2-meteor typings in /typings, I got the same error.

**Comment by audan2009** [comment]
Tried a few variations and what you have... still getting the same errors

**Comment by barbatus** [comment]
Message `resolves to a non-module entity and cannot be imported` usually shown when `angular2` is not installed. Please make sure that you have all NPM deps installed. If the message has not gone after,  I'll need a small repo to find out the reason.
