### ISSUE TITLE
build with meteor 1.3.2 

### ISSUE THREAD

**Issue by hlehmann** [Urigo/angular2-meteor#234]
after updating to meteor 1.3.2 I get the following error with angular2-compilers

```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While processing files with angular2-compilers (for target web.browser):
   <anonymous>: 0100-01-01-custom-popup-style.html has wrong layout
   at Error (<anonymous>)
   at compilers/html_compiler.js:30:15
   at Array.forEach (native)
   at HtmlCompiler.processFilesForTarget (compilers/html_compiler.js:22:11)
```

I have no idea of what is 0100-01-01-custom-popup-style.html but it looks like if is trying to watch files from node_modules.

**Comment by hlehmann** [comment]
@barbatus Should it means that now it would be possible to import html files into js like require('./template.html') ?

**Comment by twastvedt** [comment]
I am seeing this same error, but the html file it complains about is my index.html. Its contents on disk is just:
```
<head>
    <!-- Several meta tags -->
</head>

<body>
    <app></app>
</body>
```

**Comment by jeveloper** [comment]
There are at least 2 minor releases in meteor that appear to be urgent bug fixes , never seen releases come out that quickly.

**Comment by hlehmann** [comment]
Well now that meteor compilers inspect assets in node_modules we need to fix the compiler to avoid analysing html from there. @Urigo can you take a look at this ?

**Comment by DanielSmon** [comment]
I'm also getting this error for index.html, but I don't have an index.html in my project. Removing all html files (renaming to .htmlx) and creating a new index.html in the client folder doesn't change the error at all. Started with 1.3.2 onwards (i.e. I get the same error with 1.3.2, 1.3.2.1 and 1.3.2.2).

I'm relatively new to Meteor, and I have to say I was surprised to see those patches come out so quickly as well! Also, I wonder why Meteor doesn't use proper semver (1.3 caused a parsing issue in another project)... anyway, that's a topic for elsewhere.
