### ISSUE TITLE
Warnings not finding styles from angular2-meteor-accounts-ui

### ISSUE THREAD

**Issue by denodaeus** [Urigo/angular2-meteor#239]
Stepping through some of the code in the socially demo, I'm having this problem when pulling the latest angular2-meteor-accounts: 

=> Client modified -- refreshing (x21)
Unable to resolve some modules:

  "!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less" in
/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/angular2-meteor-accounts-ui/login-buttons.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save !!.

So when I try to render the login buttons, it doesn't work.

**Comment by barbatus** [comment]
Please report it to the angular2-meteor-accounts-ui package.
