### ISSUE TITLE
Q: Source map URL, meteor://??app...

### ISSUE THREAD

**Issue by jin-chong** [Urigo/angular2-meteor#245]
Hi,
It's question rather than issue.  Sorry I couldn't find better place for question.
I'm trying to map between source map path and local map path for remote debugging.
FYI, I'm trying to set up remote debug using VSCode (setup remoteroot and localroot at launch.json)

From Firefox or Chrome, I found the source path starts from meteor://<??>app.. (<??> is some binary).
**Could you please advice me what is <??>?  
**If it is real binary, it would be quite difficult or impossible to map between 'meteor://<??>app...' and my local path by debugger tool(such as VSCode)

Thanks in advance,
Jin.

**Comment by barbatus** [comment]
This is is a PERSONAL COMPUTER (`\u{1f4bb}`) character. It makes sure the source map category is always the last in Chrome DevTools. See for more https://github.com/meteor/meteor/blob/baa3f6a152af96ff1e7a7f9f0e00c86c9cd922ee/tools/isobuild/bundler.js#L1093
