### ISSUE TITLE
Error: tasks.ts (1, 41): Cannot find name 'Task'. 

### ISSUE THREAD

**Issue by Makombo** [Urigo/angular2-meteor#247]
I'm assuming there's a typings file missing that defines a Task interface?

**Comment by barbatus** [comment]
yes, added [here](https://github.com/Urigo/angular2-meteor/blob/master/examples/todos-meteor-1.3/typings/task.d.ts)

**Comment by Makombo** [comment]
Thanks! quick turnaround
