### ISSUE TITLE
Angular2 services -- any use cases?

### ISSUE THREAD

**Issue by denodaeus** [Urigo/angular2-meteor#249]
I don't think this project has a place for asking questions (if you guys do, such as gitter, or something, great!  Point me there), so I wanted to bring this up here.

It seems the way that angular2-meteor is designed is by using MeteorComponent to extend the behavior of components with the power of meteor.  I think this is fantastic, but it does tightly couple the angular2 client code with angular2-meteor specifically.

Do you guys see any use for angular2 service classes?  We cannot figure out a way to use them without handling all the subscribe and auto-watch logic inside of a component class, which is just a lot easier to do by extending MeteorComponent.  For example, in your example projects (1.3 Todos and 1.2 socially), you tend to use the Mongo.Cursor directly inside the component, as opposed to use angular2's change detection to property listen for changes in a service class and notify through observables to the components.

It just feels like using Angular2-Meteor is nice to get syntactically things like typescript and design by component from angular2, but a lot of the DI that the angular2 project thinks is idiomatic (example, async data sources like http) is kind of avoided completely by angular2-meteor by a lot of magic behind the scenes.

I just wondered in general, specifically to @Urigo and @barbatus, what are your thoughts on this?  Do you think there's any place for using services in combination with angular2 meteor?  Do you have any examples that you should share where you might do this, or some specific points why you wouldn't?

The other benefit to injectable services is unit testing.  We're finding unit testing with Meteor 1.3 and Angular2 Meteor almost impossible.  We'd need the ability to define and inject the Mongo behavior for unit testing purposes, but because components are so tightly coupled with things like mongo cursors (extending MeteorComponent), we're finding it almost impossible to get this to work the way it's currently designed.

Thanks for your time guys, I think this is an awesome project.

**Comment by barbatus** [comment]
MeteorComponent has nothing to do with Mongo. 
Nobody forces you to extend `MeteorComponent`, you can still use `Meteor.autorun` etc directly in your components. `MeteorComponent` is supposed to be a small utility to add zone-binding and some cleanups for these Meteor methods.
In the near future, we'll likely add small decorators that inject functionality of `MeteorComponent` to a component, like said here https://github.com/Urigo/angular2-meteor/issues/142

Also, please ask first-off questions here https://github.com/Urigo/angular2-meteor#questions-and-issues.

**Comment by paistipoikka** [comment]
@denodaeus Did you ever go any further with this question?
