### ISSUE TITLE
tsconfig.json instead of reference directives in tutorial?

### ISSUE THREAD

**Issue by stephenlaughton** [Urigo/angular2-meteor#25]
I encountered a little bit of friction running through the tutorial because I was using Atom and it's associated Typescript package. After reading up on latest developements with tsconfig.json I was able to get the example working in Atom with no errors or warnings, but it wasn't immediately obvious what was wrong (for a total beginner like myself). Since tsconfig.json seems to be the way to go moving forward, maybe it would be good to move the example over tsconfig.json so the tutorial will be quick and easy with any editor that supports tsconfig.json?

**Comment by barbatus** [comment]
Can you elaborate what exactly issues you got with tsconfig.json and Atom.
Also, what do you mean by 'the example'?

**Comment by stephenlaughton** [comment]
Sorry I should have said the [tutorial](http://angular-meteor.com/tutorials/angular2/bootstrapping). Throughout the tutorial tsconfig.json is never mentioned and if one tries to go step by step through the tutorial using Atom and the [Atom-Typscript](https://github.com/TypeStrong/atom-typescript) package they will see a lot of warnings//complaints from the Atom-Typescript package having to do with missing tsconfig.json, outdate JS and so on. The tutorial walk through goes much smoother in VS Code, but it seems like all editors are moving away from the /// references and supporting tsconfig.json instead.

**Comment by barbatus** [comment]
But how does /// references relate to tsconfig.json? 
/// references are specific to .ts-files while tsconfig.json is a global compiler config.
I don't think that presence of tsconfig.json is mandatory. Basically you add it if you want to change standard behavior. So, it's not clear why does Atom require tsconfig.json by default and what options needs there.
I personally use Sublime's TypeScript plugin and have no complains so far with or without tsconfig.json.

**Comment by stephenlaughton** [comment]
Check out 18:14 in this [talk](https://youtu.be/2ZIE9gokAxY?t=18m12s), given by the Typescript team lead, where tsconfig.json is mentioned as the way forward in Typescript projects. 

Also this is mentioned in the [release notes for Typescript 1.5](http://blogs.msdn.com/b/typescript/archive/2015/07/20/announcing-typescript-1-5.aspx):

> Lightweight, portable projects

> One of the tricky things with TypeScript projects is that it’s not often easy to move from a single file to working with a growing project of files.  You generally have two options: adding ///<reference> statements to tie your project together, or manually handling everything on the commandline.  Neither approach is particularly clean, and easily become a mess as the project grows.  Additionally, only the ///<reference> approach works well with editors, so you inevitably have a number of them in addition to your build.

> TypeScript 1.5 introduces a new feature to make getting started withTypeScript easier.  The compiler now supports ‘tsconfig.json’, a new file which allows you to specify the files in your project and the compiler settings to use.  This lets you create a lightweight project that can be used both on the command-line and within the editor.  In fact, VS Code, Sublime, Atom, and others already support using tsconfig.json files.

In the end I figured out how to get Atom to stop complaining and I learned about tsconfig.json on my own which is good. I just figured it would make the tutorial reflect better the current state of Typescript.

**Comment by drewlio** [comment]
@stephenlaughton I'm having some trouble with Atom (and atom-typescript package) and meteor-angular2 as well. In my tsconfig.json I had to specify `"compileOnSave": false` so that Atom wouldn't compile (but would still provide all the error flagging, completion, etc). However, the watcher and compiler in meteor-angular2 ignores that flag and still runs. Is this what you do as well?

I feel like I'm struggling to get a good workflow.

**Comment by pinoyyid** [comment]
@drewlio thx for the compileOnSave tip. I agree on workflow. It feels a lot more natural to let the IDE (Atom for me) do the compilation.

**Comment by jpdatalicious** [comment]
```
  "buildOnSave": false,
  "compileOnSave": false
```

`tsconfig.json` options works for me as well.

**Comment by Urigo** [comment]
Deployed, please check if it fixes the problem

**Comment by ShMcK** [comment]
Reference for a `.tsconfig.json` file setup in Atom with the [atom-typescript plugin](https://atom.io/packages/atom-typescript).

```js
{
 "atom": {
    "rewriteTsconfig": true
  },
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "system",
    "target": "es5"
  },
  "filesGlob": [
    "**/*.ts"
  ],
  "files": [],
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Comment by barbatus** [comment]
@ShMcK filesGlob seems to be non-standard section and not supported by the package. Does Atom recognize 'files'?

**Comment by ShMcK** [comment]
filesGlob is atom-typescript specific. https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md
