### ISSUE TITLE
css or sass file in component styleUrls

### ISSUE THREAD

**Issue by luxcor** [Urigo/angular2-meteor#253]
Hi, i'm trying to build a component with its own custom css (or sass) 
e.g.

`@Component({
  selector     : 'parties-list',
  templateUrl  : '/imports/ui/pages/parties-list/parties-list.html',
  styleUrls    : ['/imports/ui/pages/parties-list/parties-list.css']
})`

or using sass

`@Component({
  selector     : 'parties-list',
  templateUrl  : '/imports/ui/pages/parties-list/parties-list.html',
  styleUrls    : ['/imports/ui/pages/parties-list/parties-list.scss']
})`

this doesn't work and the style is not applied.. it seems the files have been ignored.

I tryed using require in this way: `styleUrls    : [require('/imports/ui/pages/parties-list/parties-list.scss')]`
the css it's loaded but in this case it is available for all the project and not only for the specific component..

Any suggestion?

Thank you in advice

Luca

**Comment by ThomsCass** [comment]
Yes it doesn't work. 
For now as a work around you can put it in an other folder than import, then it will be load automatically.

**Comment by Hongbo-Miao** [comment]
Duplicated with https://github.com/Urigo/angular2-meteor/issues/244

**Comment by barbatus** [comment]
Track here https://github.com/Urigo/angular2-meteor/issues/270
