### ISSUE TITLE
Sort dynamically with ngFor

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular2-meteor#254]
Hi,

I have a list of items display by the `*ngFor`directive. On each item there is a button ( pin ) that can be activate. 

```javascript
item.activate = true;
//OR
item.activate = false;
```

When it is activate I would like the item to be on the top of the list, and when it is not activate on the bottom.

I sort the items in the cursor from the publish function. So at the first subscription everything is in order.

When I activate one item from the list, I rerun the subscription but nothing update in the UI as I suppose for angular there are no changes in term of items in the list.

If I sort the list in client side, when I press the activate button of one item the javascript console goes red.

Is there a way to do that ?

I don't want to use Pipe as it is not recommended for sorting and filtering.

Thanks

**Comment by barbatus** [comment]
It might be related to this https://github.com/Urigo/angular2-meteor/issues/170.
Does the following snippet raise an exception for you?:
```
this.autorun(() => {
 this.items = Items.find((), {sort: {activate: 1}});
})
```

**Comment by barbatus** [comment]
seems to be not actual
