### ISSUE TITLE
Cannot find module 'angular/*'

### ISSUE THREAD

**Issue by onhate** [Urigo/angular2-meteor#258]
Hello,

We can see on startup logs several entries of Cannot find module... The application runs without problem, but I would like to eliminate these warnings from the logs.

Where can I find the typings for the angular modules?

```
client/app/XXX/XXX.ts (2, 27): Cannot find module 'angular2/core'.
client/app/XXX/XXX.ts (4, 33): Cannot find module 'angular2-meteor'.
client/app/XXX/XXX.ts(5, 28): Cannot find module 'angular2/router'.
```

**Comment by derekkite** [comment]
what does your tsconfig.json and typings folder look like? This is mine.

`		"files": [
			"client/app.ts",
		"typings/main.d.ts",
                 ....
	`
The main.d.ts looks like this:
`/// <reference path="main/ambient/babyparse/babyparse.d.ts" />
/// <reference path="main/ambient/es6-promise/es6-promise.d.ts" />
/// <reference path="main/ambient/es6-shim/es6-shim.d.ts" />
/// <reference path="main/ambient/lodash/lodash.d.ts" />
/// <reference path="main/ambient/meteor/index.d.ts" />
/// <reference path="main/ambient/meteor/meteor.d.ts" />
/// <reference path="main/ambient/node/node.d.ts" />
`

All the typings files are in the node_modules.

Angular and angular2 meteor are installed using npm --save.

I remember seeing that error a while ago and I think it had to do with typings definitions in the typings folder.

**Comment by Urigo** [comment]
please try with the instruction on the updated version of the tutorial (from yesterday)
should work now, let me know if not
