### ISSUE TITLE
templates should only be imported explicitly

### ISSUE THREAD

**Issue by trajano** [Urigo/angular2-meteor#261]
When using angular2-compilers templates get implicitly imported without the `import` statement.  Example on this commit.  https://github.com/trajano/meteor-boilerplate/commit/bb71a20d716e316d50c4fdbf5878f605b37e2c1a

This is both good and bad.  Good that it reduces one line of code I have to do each, bad that it does not provide a good migration path from previous `angular-templates` that require it.  In fact if will complain that there is no module found for the template.

**Comment by barbatus** [comment]
Fixed here https://github.com/Urigo/angular2-meteor/commit/84f6490eca9f942555571a50926731ea3b7fa074, will be in the next version

**Comment by trajano** [comment]
Thanks, hope it gets released soon, at the moment I am getting the error on https://github.com/trajano/meteor-boilerplate/blob/angular2/imports/ui/components/meteorSample.component.js

because `import templateUrl from './meteorSample.html'` will fail in that `./meteorSample.html` is not found.

**Comment by Urigo** [comment]
published a new version

**Comment by trajano** [comment]
Just tested, the export didn't work as expected 

    Error: [$http:badreq] Http request configuration url must be a string.  Received: {"default":"imports/ui/states/home/main.html"}

I'll try to switch it to the `{}` pattern. instead of the `import templateUrl from './template.html'`

**Comment by trajano** [comment]
Nope didn't work.  Putting in the original templateUrl with 'imports/...' still works

      templateUrl: 'imports/ui/states/home/main.html',

However, this also works

      templateUrl: templateUrl.default,

(Just went with the error I saw above).  Can it be fixed so it does not need that `.default` at the end?

**Comment by trajano** [comment]
I think if we add  exports.templateUrl = "${templateUrl}"; in https://github.com/Urigo/angular2-meteor/commit/84f6490eca9f942555571a50926731ea3b7fa074#diff-606781768ac540dde840ff73e50d5066R120 it wouild at least allow us to use the `{}` form.

**Comment by kamilkisiela** [comment]
We could change `exports.default` to `module.exports`. This way we:

could use a require function:

```js
@Component({
  selector: 'second-meteor-sample',
  templateUrl: require('./secondMeteorSample.html')
})
```

or an import statement:

```js
import * as templateUrl from './secondMeteorSample.html';
@Component({
  templateUrl,
  selector: 'second-meteor-sample'
})
```

**Comment by kokokenada** [comment]
@trajano , I just moved my app to use templateUrl: '/imports/...' instead of template: `<inline html>`.

I noticed that saving the referenced html file, does not trigger a rebuild. Is this because I need to declare it differently or import it?  Is there a best practice for importing and which versions is it imported in?

**Comment by trajano** [comment]
@kokokenada the recommended usage would be to use `template` rather than `templateUrl` according to one of @Urigo comments (just can't seem to find it at the moment)
