### ISSUE TITLE
Website not working on Chrome Browser

### ISSUE THREAD

**Issue by praneybehl** [Urigo/angular2-meteor#269]
Hi guys, 
Just wanted to give a heads-up that the website: http://www.angular-meteor.com/ is not working in Chrome Browser. I am currently using Version 50.0.2661.94 (64-bit). 

This is the error that shows in the console:

a4f775c….js:120 Uncaught Error: Handler with name 'i' already exists.
a4f775c….js:112 pathFor couldn't find a route named "migration"
a4f775c….js:61 Uncaught Error: No such function: currentApi

**Comment by barbatus** [comment]
https://github.com/Urigo/angular-meteor-docs/issues/90
