### ISSUE TITLE
No Directive annotation found on Socially - Step 3 of the angular2-meteor tutorial

### ISSUE THREAD

**Issue by dean0x** [Urigo/angular2-meteor#272]
I'm new to all of this so I hope this is the right place for this issue.

After completing step 3 of the tutorial I get the message: No Directive annotation found on Socially in the console.

This guy get's the same error as well

http://stackoverflow.com/questions/37149260/angular-meteor-error-with-angular2-meteor-auto-bootstrap-no-directive-annota

**Comment by barbatus** [comment]
Please re-post it here https://github.com/Urigo/meteor-angular2.0-socially
