### ISSUE TITLE
No app in safari

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular2-meteor#273]
Hi,

I have an app in meteor angular2 everything works fine in Chrome and Firefox but when I try in Safari nothing shows up and here is a picture with all the errors in the console :
 
<img width="742" alt="errors" src="https://cloud.githubusercontent.com/assets/10784312/15258201/829e26ae-194a-11e6-8e06-09b42809ff9f.png">

I have my `packages.json` up to date.

What should I do ?

Thanks

**Comment by Urigo** [comment]
@ThomsCass have you tried the same with a plain Angular 2.0 app (without Meteor)?

**Comment by ThomsCass** [comment]
@Urigo No I didn't, I work only with angular2 meteor.

Do you mean it's an angular 2 issue ?

**Comment by Urigo** [comment]
the best thing would be if you could create a reproduction with plain Angular 2 code and post it on the Angular 2.0 repo

**Comment by Hongbo-Miao** [comment]
@ThomsCass my app can run well with @angular/router-deprecated in Safari. A reproduction will be helpful

**Comment by ThomsCass** [comment]
Hi @Hongbo-Miao 

Here is the repo : https://github.com/ThomsCass/angular2-meteor-noapp-safari.git

I remove some stuff so it looks weird sorry. So nothing shows up in Safari with the errors above.

Thanks

**Comment by DrDanPrice** [comment]
I've run into the same problem. After reinstalling in a new project, it seems to be the zone.js call that is the problem. If you comment out that line at http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping in the original app.ts, then the safari will open just fine (it's not using zone.js for anything at that point). In fact, it seems like it is just removed later and not used, in favor of just using the NgZone wrapper. If that is what should happen, then the docs can just be changed to remove that line and everything will work. (Or at least did on my install)

**Comment by Hongbo-Miao** [comment]
Another one runs into this problem.
https://forums.meteor.com/t/range-error-maximum-call-stack-exceeded-angular2-meteor/24010

**Comment by Hongbo-Miao** [comment]
I am using `import 'zone.js/dist/zone';`, no error so far. Weird.

**Comment by kokokenada** [comment]
I can confirm that removing import 'zone.js/dist/zone'; fixed this problem for me.  (Yeah!)

**Comment by kokokenada** [comment]
However, removing 'zone.js/dist/zone'; breaks running the app on Android.  Now when I run 'meteor run android-device' it crashes:
````
I20160606-22:00:14.800(-4) (android:http://localhost:12496/app/app.js:6764) Uncaught ReferenceError: App is not defined
I20160606-22:00:15.277(-4) (android:http://localhost:12496/packages/modules.js:67904) EXCEPTION: Error in :0:0
I20160606-22:00:15.277(-4) (android:http://localhost:12496/packages/modules.js:67904) ORIGINAL EXCEPTION: The selector "for-real-cards-top-frame" did not match any elements
I20160606-22:00:15.277(-4) (android:http://localhost:12496/packages/modules.js:67904) ORIGINAL STACKTRACE:
I20160606-22:00:15.278(-4)? I/chromium(27458): [INFO:CONSOLE(67904)] "Error: The selector "<<my top level selector >>" did not match any elements
I20160606-22:00:15.278(-4)? I/chromium(27458):     at new BaseException (http://localhost:12496/packages/modules.js?hash=a6659c0cd16b2ba50b8b3a94ecb62ec0e18c55bb:67147:23)
```

Adding the line back in, fixes the problem Android problem, but the original "new FileReader() crash" and "Safari can't connect" problems come back.

**Comment by barbatus** [comment]
Please read this https://github.com/Urigo/angular2-meteor/issues/284#issuecomment-224258907

**Comment by kokokenada** [comment]
I've updated all of the meteor and npm packages and I'm still stuck.  Now it complains with "Cannot find module 'angular2-meteor-polyfills/browser'" and ios simular and android device are broken.  Repository is at: https://github.com/kokokenada/for-real-cards

**Comment by barbatus** [comment]
@kokokenada  what if you install angular2-meteor-polyfills?

**Comment by kokokenada** [comment]
@barbatus - that fixed the error messages. (I thought that it would have been installed by one of the packages, sorry to miss the obvious and thanks for your help.)  A quick smoke test showed that it's working in Chrome, Safari and iOS simulator.  However running on an Android device, it crashes complaining about not finding the root app selector. (See below.)  At first I thought it was related to a network connection problem, but I don't think so.  And if it was, there's been a change, because I used to get to my login screen when I forgot to turn Wifi on.  ( https://github.com/kokokenada/for-real-cards has been updated.)

````
I20160607-19:59:01.936(-4)? I/chromium( 7108): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
I20160607-19:59:01.937(-4)? I/MeteorWebApp( 7108): Serving asset bundle with version: 7818241d7e165bd12b6a3d84d72cc188f619d6a3
I20160607-19:59:02.495(-4)? I/chromium( 7544): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
I20160607-19:59:05.982(-4) (android:http://localhost:12496/app/app.js:6657) In apps.ts @Tue Jun 07 2016 19:59:43 GMT-0400 (EDT)
I20160607-19:59:05.982(-4) (android:http://localhost:12496/app/app.js:6658) http://192.168.43.141:3000/
I20160607-19:59:06.443(-4) (android:http://localhost:12496/packages/modules.js:69407) EXCEPTION: Error in :0:0
I20160607-19:59:06.443(-4) (android:http://localhost:12496/packages/modules.js:69407) ORIGINAL EXCEPTION: The selector "for-real-cards-top-frame" did not match any elements
I20160607-19:59:06.443(-4) (android:http://localhost:12496/packages/modules.js:69407) ORIGINAL STACKTRACE:
I20160607-19:59:06.444(-4)? I/chromium( 7108): [INFO:CONSOLE(69407)] "Error: The selector "for-real-cards-top-frame" did not match any elements
I20160607-19:59:06.444(-4)? I/chromium( 7108):     at new BaseException (http://localhost:12496/packages/modules.js?hash=6336e922ca522654fbc850b9129aaa5c8d8cd22d:68650:23)
I20160607-19:59:06.444(-4)? I/chromium( 7108):     at DomRenderer.selectRootElement (http://localhost:12496/packages/modules.js?hash=6336e922ca522654fbc850b9129aaa5c8d8cd22d:70666:23)
````
