### ISSUE TITLE
Simple scaffolding not possible anymore on meteor 1.3 with 0.5.5

### ISSUE THREAD

**Issue by rvetere** [Urigo/angular2-meteor#277]
I'm having this prototype app which was running with meteor 1.2 and angular2 beta.16. Now i've updated everything to meteor 1.3.2.4 and @angular rc1, and all other packages (including this one to 0.5.5).

Now i'm shortly away from the point i turn completely insane: I'm having my /client/app.ts which boots everything:

`import 'reflect-metadata';`
`import 'zone.js/dist/zone';`
`import {Component} from '@angular/core';`
`import {bootstrap} from 'angular2-meteor-auto-bootstrap';`

`import {Socially} from './social';`

`bootstrap(Socially);`

This variant above is working. As you can see, the "Socially" class is imported from his own file, laying directly in /client folder (social.ts). Now i move the file "social.ts" into a subfolder called "app". The import changes accordingly:

`import {Socially} from './app/social';`

As soon as we changed that and everything reloaded, we start getting this exception:

`EXCEPTION: No Directive annotation found on App`

As i could only barely believe that the folder structure is counting for this - i changed it back in structure and bam, works again... -.-

So i thought i'm "smart" and, so i ended up creating a "local" class directly in app.ts, just extending from the class i actually want:

`import {`
`  AppMeteor, AppMeteorDecorator`
`} from './app/components/app-meteor/app-meteor.component';`

`@Component(AppMeteorDecorator)`
`class AppFireball extends AppMeteor implements OnInit, AfterViewChecked {`

`}`

And well.. the app itself works, but the exception is just moving around, now he's complaining:

`EXCEPTION: No Directive annotation found on HeaderMeteor`

Well yeah, HeaderMeteor is just another custom component i'm adding as a directive - coming from another sub-folder.... -.-

The strange thing is - leaving meteor out the door, doing everything with webpack and no backend - the exact same app is working!

So i can't help myself but it must be related to the meteor-angular packages, maybe this one here or the "auto-bootstrap" one...

Can anyone help? Does anybody see the same behavior?

**Comment by rvetere** [comment]
Ah damn.. i just found the new part in the tutorial about the special "imports" folder... -.- That would be the solution right...?

**Comment by Urigo** [comment]
yes :)

**Comment by rvetere** [comment]
hehe thanks for the answer anyways 😄  it was a classic murphys-law case.. whenever i try to explain my problem to somebody else (or to github) - it happens quite often that i suddenly found the solution on my own...

**Comment by Urigo** [comment]
it a good thing, now your solution is out in the open for others to learn from
