### ISSUE TITLE
Roadmap for integrating Angular CLI and Progressive Web Apps features with Meteor

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#280]

**Comment by daslicht** [comment]
So integration of angular cli is planned ?

**Comment by barbatus** [comment]
@daslicht yes, I am working on it currently.

**Comment by daslicht** [comment]
awesome news! Its getting better and better !

**Comment by dotansimha** [comment]
This issue was moved to Urigo/angular-meteor#1475
