### ISSUE TITLE
getting Error: Uncaught (in promise): No Directive annotation found on TabComponent

### ISSUE THREAD

**Issue by hyaadd** [Urigo/angular2-meteor#281]
@Urigo when i trying to import a directive from other file, i am getting the Error: Uncaught (in promise): No Directive annotation found on TabComponent - how to solve this?

here is my code:

app.ts:
----------------------------------------------------------------------------------------------------------------------------------------------
`import 'reflect-metadata';
import 'zone.js/dist/zone';
import { Component } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';
import { TabComponent } from './components/TabComponent/tab.component';

@Component({
	selector: 'flex',
	templateUrl: 'client/app.html',
	directives: [TabComponent]
})

export class Flex { }

bootstrap(Flex);
`
----------------------------------------------------------------------------------------------------------------------------------------------

tab.component.ts:
----------------------------------------------------------------------------------------------------------------------------------------------

`import {Component} from '@angular/core';

@Component({
	selector: 'tab',
	template: `
		<div class="tab-menu-wrapper">
		    <a href="#" class="w-button link tab-button profile-page"></a>
		    <a href="#" class="w-button link tab-button inbox-page"></a>
		    <a href="#" class="w-button link tab-button camera-page"></a>
		    <a href="#" class="w-button link tab-button whatsup-page"></a>
		    <a href="#" class="w-button link tab-button search-page"></a>
		</div>
	`,
    styles: [`
		body {
		  padding-top: 50px;
		  font-family: 'Open Sans', sans-serif;
		  color: #333;
		  font-size: 14px;
		  line-height: 20px;
		  font-weight: 100;
		}

		.tab-menu-wrapper {
		  position: fixed;
		  left: 0px;
		  right: 0px;
		  bottom: 0px;
		  z-index: 5;
		  display: -webkit-box;
		  display: -webkit-flex;
		  display: -ms-flexbox;
		  display: flex;
		  height: 50px;
		  -webkit-justify-content: space-around;
		  -ms-flex-pack: distribute;
		  justify-content: space-around;
		  background-color: #fff;
		}

		.link {
		  background-color: transparent;
		  font-family: 'Open Sans', sans-serif;
		  color: #00bcd4;
		  font-size: 15px;
		}

		.link.tab-button {
		  width: 50px;
		  height: 50px;
		}

		.link.tab-button.profile-page {
		  background-image: url('client/assets/images/user-empty-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.profile-page-active {
		  background-image: url('client/assets/images/user-filled-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.inbox-page {
		  background-image: url('client/assets/images/message-empty-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.inbox-page-active {
		  background-image: url('client/assets/images/message-filled-cyan.png');
		  background-position: 50% 50%;
		  background-size: 26px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.text-editor-page {
		  background-image: url('client/assets/images/NewPost-empty-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.text-editor-page-active {
		  background-image: url('client/assets/images/NewPost-filled-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.camera-page {
		  background-image: url('client/assets/images/assets/images/Photo-empty-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.camera-page-active {
		  background-image: url('client/assets/images/Photo-filled-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.whatsup-page {
		  background-image: url('client/assets/images/whatsup-empty-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.whatsup-page-active {
		  background-image: url('client/assets/images/whatsup-filled-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.search-page {
		  background-image: url('client/assets/images/Search-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.link.tab-button.search-page-active {
		  background-image: url('client/assets/images/Search-filled-cyan.png');
		  background-position: 50% 50%;
		  background-size: 25px;
		  background-repeat: no-repeat;
		}

		.two-element-header-body {
		  padding-top: 100px;
		}

    `]
})
export class TabComponent { };
`
----------------------------------------------------------------------------------------------------------------------------------------------
how do I solve this?

**Comment by barbatus** [comment]
Please ask this question on one of the resources mentioned here https://github.com/Urigo/angular2-meteor#questions-and-issues. It's not related to this repo.
