### ISSUE TITLE
angular2-meteor-auto-bootstrap fails 

### ISSUE THREAD

**Issue by stocksp** [Urigo/angular2-meteor#282]
Step three of the 'Socially' tutorial builds clean but fails in the browser with
```
application_ref.js:36Uncaught There can be only one platform. Destroy the previous one to create a new one.
```
angular 2 rc1 apps run fine.  rc1 is the only version of Angular on my machine (Mac).  No previous versions of angular2-meteor.

The zip files for the tutorial don't correspond to the text ... I assume they are just old.

**Comment by kamilkisiela** [comment]
Are you sure? It's working for me.

Repo at step 3.9
 https://github.com/Urigo/meteor-angular2.0-socially/tree/87b5704f2427e56673c4b3b364c470392c73953c

```json
{
  "name": "socially",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "angular2-meteor": "0.5.5",
    "angular2-meteor-auto-bootstrap": "0.5.5",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  }
}
```

Try to use 

```bash
npm prune
```

to remove unused node modules that have been installed previously

```bash
npm install
```

to make sure you have all of packages :)

**Comment by stocksp** [comment]
No, that doesn't help at all.   I cloned the repo and that runs fine.  Though there are a number or errors in the terminal.
```
=> Started proxy.                             
=> Started MongoDB.                           
client/imports/auth/login.ts (33, 7): Cannot find name 'Meteor'.                   
client/imports/auth/recover.ts (32, 7): Cannot find name 'Accounts'.
client/imports/auth/signup.ts (33, 7): Cannot find name 'Accounts'.
client/imports/parties-list/parties-list.ts (24, 2): Supplied parameters do not match any signature of call target.
client/imports/party-details/party-details.ts (22, 2): Supplied parameters do not match any signature of call target.
client/app.ts (39, 2): Supplied parameters do not match any signature of call target.
client/app.ts (41, 9): Cannot find namespace 'Meteor'.
client/app.ts (49, 7): Cannot find name 'Meteor'.
```
 The package.json only differs by 'meteor-node-stubs'  which is at 0.2.0 from the tutorial (I updated and it made no difference).

Again.  I'm just following the tutorial.   Very few steps and code.  builds fine just crashes as I've noted.

thanks in advance for any help...

**Comment by stocksp** [comment]
update:   the browser is NOT crashing ... I just don't see anything as the db doesn't have any documents.   When documents are added they display ....
The error in the console persists though.
```
application_ref.js:36Uncaught There can be only one platform. Destroy the previous one to create a new one.
```

I don't see this error in the completed app I cloned ... so I'll just continue the tutorial and hope it goes away...  sorry for the noise
