### ISSUE TITLE
Routing Problem - Step 5 - Angular 2 Socially

### ISSUE THREAD

**Issue by insidemybrain** [Urigo/angular2-meteor#283]
Hello,
i'm having problems when add a ROUTER_PROVIDER and all his friends...

My Code:
```typescript
import 'reflect-metadata'
import 'zone.js/dist/zone'
import {Component,provide} from '@angular/core'
import {bootstrap} from 'angular2-meteor-auto-bootstrap'
import {ROUTER_PROVIDERS,ROUTER_DIRECTIVES,RouteConfig} from '@angular/router-deprecated'
import {APP_BASE_HREF} from '@angular/common'
import {SomeCoolComponent} from './SomeCoolComponent'
@Component({
	selector: 'app',
	templateUrl: 'client/app.html',
	directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
	{ path: '/', as: 'SomeCoolComponent', component: SomeCoolComponent }
])
class App{

}

let appProviders = [ROUTER_PROVIDERS,provide(APP_BASE_HREF,{useValue: '/'})]
bootstrap(App, appProviders)
```
When the app start gives me this error:
```typescript
Uncaught (in promise): No Directive annotation found on SomeCoolComponent
```

Well, so i've imported *RouterLink* on SomeCoolComponent, just to check... and the error has changed to:
```typescript
Uncaught Cannot resolve all parameters for 'RouteRegistry'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'RouteRegistry' is decorated with Injectable.
```

**Comment by derek-fong** [comment]
Did you add `RouterLink` into Component directives?

```js
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router-deprecated';

@Component({
    selector: 'eg-cool',
    directives: [RouterLink], // REVIEW: `RouterLink` Added?
    templateUrl: '/client/imports/cool/cool.html'
})
export class SomeCoolComponent { }
```

**Comment by barbatus** [comment]
Try to import ROUTER_DIRECTIVES on SomeCoolComponent

**Comment by insidemybrain** [comment]
@barbatus  @derek-fong Sorry but isn't working. Still getting "Uncaught Cannot resolve all parameters for 'RouteRegistry'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'RouteRegistry' is decorated with Injectable. - reflective_provider.js:182"

**Comment by barbatus** [comment]
@insidemybrain this issue is certainly not related to this repo. Here is resources where you can ask questions https://github.com/Urigo/angular2-meteor#questions-and-issues, also the error message itself is quite verbosely saying about the possible origin
