### ISSUE TITLE
Calling Router from Server

### ISSUE THREAD

**Issue by DerekTBrown** [Urigo/angular2-meteor#288]
I am writing the authentication for my application, and I would like for there to be a way for the server to directly redirect the user to a particular page.  This seems like something that should be built in to the Meteor component of Angular 2 Meteor, similar to anti:methods.

**Comment by barbatus** [comment]
If you want to get server involved there is a way to do it using Meteor routers. One of them is FlowRouter, so you could try it. It might be useful also to check out https://github.com/barbatus/angular2-meteor-universal

**Comment by DerekTBrown** [comment]
The issue with using FlowRouter is that it reloads the entire page, as opposed to just reloading the element within my ```<router-outlet>```.  I think it would be valuable to create a service which is attached to the Angular Router which can use a pub/sub to the Meteor server to control the <router-outlet> directly from the server.

**Comment by barbatus** [comment]
Meteor essentially is about to make data synchronization between client and server as seamless and simple as possible. Basically what are you talking about is some specific case that can be easily implemented using Meteor API by anyone. Hence, I don't see a reason to add it to this library since it's aimed for more general stuff. You are though welcome to create a NPM that provides mentioned functionality.

**Comment by DerekTBrown** [comment]
I mean, yes, it is simple, but nearly anyone who uses angular2-meteor needs to do it, so might as well implement it, yeah?

**Comment by barbatus** [comment]
@DerekTBrown That's the point, I doubt that's the proper way and many will need it. I would use rather event-based approach on the client rather then directly control it from the server. Also, this issue have been hanging for a while, I am sure a few people saw it but no one +1. If you find other way to verify your assumption - you are welcome. For now, closing.

**Comment by trunkatedpig** [comment]
+1

**Comment by Urigo** [comment]
I want to get more clarification of the need.
could you provide a pseudo-code example of how would you want to use this type of feature?
