### ISSUE TITLE
Dependence problems in step-0 of the tutorial

### ISSUE THREAD

**Issue by csbenjamin** [Urigo/angular2-meteor#289]
I am trying to get started to angular2-meteor, but when I try to follow the step-0 in http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping I get an error when I try to load the app on the web browser. I got this error in chrome console:
![screenshot from 2016-06-08 10-22-38](https://cloud.githubusercontent.com/assets/2938621/15895704/0eab33a4-2d63-11e6-9119-0929718f7edd.png)
Some weeks ago I did the same thing and everything was working just fine.

**Comment by barbatus** [comment]
Run `npm install angular2-meteor-polyfills --save`
