### ISSUE TITLE
Error: "The sector for "<root selector>" did not match any elements. Android only

### ISSUE THREAD

**Issue by kokokenada** [Urigo/angular2-meteor#290]
My app is working on Chrome, Safari, iOS simulator and an iOS device.  On an android device, it crashes with:
```
I20160608-10:18:47.203(-4) (android:http://localhost:12496/packages/modules.js:69407) ORIGINAL EXCEPTION: The selector "for-real-cards-top-frame" did not match any elements
I20160608-10:18:47.203(-4) (android:http://localhost:12496/packages/modules.js:69407) ORIGINAL STACKTRACE:
I20160608-10:18:47.203(-4)? I/chromium(15943): [INFO:CONSOLE(69407)] "Error: The selector "for-real-cards-top-frame" did not match any elements
I20160608-10:18:47.204(-4)? I/chromium(15943):     at new BaseException (http://localhost:12496/packages/modules.js?hash=6336e922ca522654fbc850b9129aaa5c8d8cd22d:68650:23)
I20160608-10:18:47.204(-4)? I/chromium(15943):     at DomRenderer.selectRootElement (http://localhost:12496/packages/modules.js?hash=6336e922ca522654fbc850b9129aaa5c8d8cd22d:70666:23)
```
Where "for-real-cards-top-frame" is the root selector.

I suspect some sort of timing issue.  There is a console.log() statement in the ngOnInit() of the class it can't find that does not get printed. 

Repository is at https://github.com/kokokenada/for-real-cards

Moving from #273

**Comment by kokokenada** [comment]
@barbatus - I've confirmed that this is indeed a timing problem.  I've been able to get the app to run by wrapping the bootstrap in a 1000ms timeout.

**Comment by barbatus** [comment]
@kokokenada why not to start thinking a bit before posting any bogus issue here? I did't find any sign of Angular2-Meteor in your app, not to mention Angular2-Meteor's bootstrap. Not sure why are you posting this issue here.

**Comment by kokokenada** [comment]
Sorry @barbatus - I was quite surprised when the app ran after I removed the the angular2-meteor package.  The maze of packages confused me. I seeded the app from the first few steps of the angular2-meteor tutorial a while back (which, incidentally, might need a delayed bootstrap for reliability based on the behaviour I bumped into).  The app does require "angular2-meteor-polyfills" but it doesn't seem related.   Anyways, thanks for the help and apologies if the issue was noise.

**Comment by Urigo** [comment]
@barbatus I agree with you that this issue is not belong here but I don't think it was on purpose and I don't think this type of language is appropriate on our project.

I would rather people posting unrelated issues then they would feel uncomfortable and need to think before posting.
I want this project to be a good and welcoming place both for beginners and professionals.
