### ISSUE TITLE
this.call callback result seems different than Meteor.call

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular2-meteor#291]
If I use a callback for `this.call` it seems different than Meteor.call:
```javascript
// client
this.call("someMethod",someArgs, (e,result) => {
 console.log(result) // undefined
 console.log(e[1]) // "hallo"
}, true)

this.call("someMethod",someArgs,(e,result) => {
  console.log(result) // "hallo"
})

Meteor.call("someMethod",someArgs,(e,result) => {
  console.log(result) // "hallo"
})

// server:
Meteor.methods({
  "someMethod":function(someArgs){
    return "hallo";
  }
})
```
Just want to know if this is intend to work like this. Cheers

**Comment by dohomi** [comment]
I think this issue relies on the `... , true)` to bind it to the context?

**Comment by Hongbo-Miao** [comment]
@dohomi `autobind` for `call` is not added in the version angular2-meteor 0.5.5, which is latest version right now on NPM.

And check here for the API of `this.call`.
https://github.com/Urigo/angular2-meteor/blob/master/build/meteor_component.js#L73

**Comment by dohomi** [comment]
@Hongbo-Miao Thanks for the input. I changed now the behavior to `Promise` callbacks inside of my services. All good for me know, I will close it for now.

**Comment by Hongbo-Miao** [comment]
You are welcome!
