### ISSUE TITLE
Can't use angular2-meteor-auto-bootstrap with ionic2-beta8

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular2-meteor#293]
What do I need to do to get mongo cursors working? (without using .find.fetch()) ionic2-beta8 requires it's own bootstrap method now, so I can't use the angular2-meteor-auto-bootstrap. Is it just a matter of import some providers and injecting them in the bootstrap method? Injecting METEOR_PROVIDERS doesn't seem to be enough.

**Comment by barbatus** [comment]
I guess Ionic2 wants `ion-app` element in the body. So one way would to check out if Cordova is running with Meteor.isCordova, and if yes replace `app` element with `ion-app` using for example https://github.com/jellyjs/ionic-selector before Ionic2 bootstrapping.

**Comment by vacarsu** [comment]
I'm using ionic2 in both client and browser, so I already have ion-app, which has nothing to do with the issue. The issue is both angular2-meteor and ionic2 require a custom bootstrap method.

**Comment by barbatus** [comment]
So are you saying and passing `METEOR_PROVIDERS` in the Ionic2 bootstrap https://github.com/driftyco/ionic/blob/2.0/src/config/bootstrap.ts#L45 does not work?
I remember it worked for me some time ago.

**Comment by vacarsu** [comment]
Looks like it is working now, I remember getting differ errors the first time I tried.
