### ISSUE TITLE
Reflect meta-data conflict versions

### ISSUE THREAD

**Issue by dvdgarcia** [Urigo/angular2-meteor#295]
Hi, adding google-maps I have noticed there is a  conflict between  reflect-metada version:

>  peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer angular2-meteor@0.5.5 wants reflect-metadata@0.1.2
> npm ERR! peerinvalid Peer angular2-google-maps@0.11.0 wants reflect-metadata@0.1.3

I fixed changing my package.json, but if someone tries to add google maps using:

meteor npm install angular2-google-maps --save

it doesn't work without manual change of depencies

**Comment by barbatus** [comment]
it's fixed in the master, will come with the next version.
