### ISSUE TITLE
Child components of Routed Component don't load after router.navigate

### ISSUE THREAD

**Issue by MiGu3X** [Urigo/angular2-meteor#296]
So I have a loginWithGoogle that when it success, the user gets redirected to the 'Dashboard' with this._router.navigate(['Dashboard']). The page navigates to the dashboard, but the components that are in the template of the DashboardComponent seems not to load, when I press 'F5' though, they load perfectly.

**app.ts**
`@RouteConfig([`
  `    ..{ path: '/', name: 'Landing',   component: LandingComponent },`
  `    ..{ path: '/dashboard',   name: 'Dashboard', component: DashboardComponent },`
`])` 

**landing.ts**
`import { Router } from '@angular/router-deprecated';`
`constructor(private router : Router) {`
    `..this._router = router;`
 `}`
`login() {`
    `..Meteor.loginWithGoogle({}, (error) => {`
     `....if (!error) {`
       `......this._router.navigate(['Dashboard']);`
    `....}`
   ` ..});`
 ` }`

**dashboard.html**
`<navbar type="dashboard"></navbar>`
`    <div class="col-xs-6 col-xs-offset-3 project-container-card">`
      `..<projects></projects>`
    `</div>`

Expected behaviour: 
- Child components should load correctly with its information.
- [Expected behaviour (shows like this after pressing F5 on /dashboard)](http://i.imgur.com/kx6K3Or.jpg)

Actual behaviour: 
- Child components don't show, their HTML tags **DO** appear, but the information that should be inside, doesn't.
- [Actual behaviour (after login)](http://i.imgur.com/IEktylf.jpg)

I repeat, if you press 'F5', everthing loads correctly
Please if someone could help me it would be great

P.S.: I'm using @angular/router-deprecated since the Socially tutorial uses that one, but will upgrade when new one gets out if the tutorial gets updated :+1:

**Comment by barbatus** [comment]
Run callbacks in the Angular2 zone.

**Comment by MiGu3X** [comment]
@barbatus What does this mean?

**Comment by Hongbo-Miao** [comment]
Most time you do not need, but that part of code run out of angular 2 zone, you need run it inside of zone to update UI immediately.

**Comment by hernanBeiza** [comment]
Thanks for the explanation about ngZone. Works like a charm!

**Comment by kattianita** [comment]
I have the same issue. I cannot load the search page twice.. Works fine the first time, when search is called with a different parameter, nothing happens. I am using angular2 final release .. 
doSearch($event, searchText) {
        if ($event.type == "click" || ($event.type == "keyup" && $event.which == 13)) {
            this.zone.run(() => {
                this.router.navigate(['/search', encodeURIComponent(searchText)]);
            });
            
        }
    }

and I have the below in routes: 
const routes: Routes = [
    { path: 'home', component: PageHome },
    { path: '', component: PageHome},
    { path: 'search/:searchText', component: PageSearch },

But if I hit F5, it works fine..
