### ISSUE TITLE
Angular2 Meteor Bind Data from calling this.call

### ISSUE THREAD

**Issue by Sieryuu** [Urigo/angular2-meteor#298]
Methods

```
Meteor.methods({
    'test' : function(test: string) {
        return test;
    }
})
```

Component

My Class extends MeteorComponent

```
show: string;
constructor() {
     this.call('test', 'txt', (err, res) => {
          this.show = res
     });
}
```

view

`<span>{{show}}</span>`

it shows nothing, as I expect it will show 'txt'.

**Comment by barbatus** [comment]
Run that callback in the ngZone, or add additional `true` param:
```
this.call('test', 'txt', (err, res) => {
   this.show = res
}, true)
```

**Comment by Sieryuu** [comment]
@barbatus 
ahh, sorry. that was for testing. 
```
this.call('test', 'txt', (err, res) => {
   this.show = res
})
```

this is the actual code. the res is about 200 indexes of array

**Comment by barbatus** [comment]
so that's the difference? Add last true param which is called autoBind, so callback will be run in the zone for you.

**Comment by Sieryuu** [comment]
@barbatus  thanks, it's working now

**Comment by jycouet** [comment]
Hi, 

For me this additional **_true_** param didn't change anything.
Do you have an idea why?

**Comment by ArthurMauricioDelgadillo** [comment]
The autobind param isnt needed anymore. It's by default set to true. See the api docs.

**Comment by jycouet** [comment]
Nice that it's by default.
The problem is that <span>{{show}}</span> in the html is not refreshed :(

I didn't find any example of this.
Where should I find the api docs?

Thank you

**Comment by jycouet** [comment]
Ok, I managed :+1: 

I put my code here... maybe it help others :)

```
import { Component, OnInit, NgZone } from '@angular/core';
import { MeteorComponent } from 'angular2-meteor';
import template from './create.component.html';

@Component({
  selector: 'create',
  template,
  directives: [],
})

export class CreateComponent extends MeteorComponent implements OnInit {
  myZone: NgZone;
  isInGetActivities: boolean = false;
  activities: Array<JSON> = [];

  constructor(zone: NgZone) {
    super();
    this.myZone = zone;
  }

  ngOnInit() { }

  getActivities() {
    this.isInGetActivities = true;

    this.call('getActivities', null, (error, result) => {
      this.myZone.run(() => {
        this.activities = result;
        this.isInGetActivities = false;
      });
    });
  }
}
```

I hope it's nice ;)
