### ISSUE TITLE
Angular rc2 breaks dependencies

### ISSUE THREAD

**Issue by mitjade** [Urigo/angular2-meteor#300]
When trying to follow Angular 2.0 Meteor Tutorial I get an error when executing:
meteor npm install --save angular2-meteor @angular/platform-browser-dynamic

...
npm ERR! peerinvalid The package @angular/core@2.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer angular2-meteor@0.5.5 wants @angular/core@2.0.0-rc.1

**Comment by kamilkisiela** [comment]
#302 Should fix it

**Comment by mitjade** [comment]
What if you try to switch to rc2, would that work?
I would like to try out new angular router v3 that is dependent on rc2.

**Comment by nanomoffet** [comment]
@mitjade You can use the new router with rc1 if you specify the alpha3 build instead of 6, that release only requires rc1. That's how I was able to play around with it, because rc2 still breaks all sorts of things for me.
