### ISSUE TITLE
Angular2 Router V3 behaves differently with angular2-meteor as opposed to plain Angular2

### ISSUE THREAD

**Issue by ijager** [Urigo/angular2-meteor#304]
This repo: https://github.com/ijager/Angular2-RouterV3-example is a simple example of the V3 Angular router in plain Angular, setup with angular-cli. You can navigate to List A which has a child route. Everything works as intended.

This repo: https://github.com/ijager/Angular2-Meteor-Router-V3-example is the same app but then using Meteor 1.3.3 and Angular2-Meteor. Here however the router behaves differently. 

Routing to ListA results in:` http://localhost:3000/listA` (as expected)
Clicking on child link item 1 results in `http://localhost:3000/listA/1` (as expected)
But then clicking a child link again results in `http://localhost:3000/listA/listA/1` (not expected)
And clicking  again: `http://localhost:3000/listA/listA/listA/1` (not expected)

So the first route gets repeated. This does not happen in the plain Angular2 app.

Also deep-linking to `http://localhost:3000/listA/1` correctly shows the components but also adds a `listA/` part to the URL.

**Comment by langfors** [comment]
@ijager - Adding:
````
<head>
       <base href=".">
</head>
````
In the index.html fixed it for me.  I'm not smart enough to know why Meteor needs this and plain angular app does not.  Perhaps there's a difference in the way push state is configured between the 2 servers?

**Comment by ijager** [comment]
@langfors Interesting, it does indeed solve the issue when clicking on the child routes repeatedly, however refreshing or deep-linking `http://localhost:3000/listA/1` still results in `http://localhost:3000/listA/listA/1` for me. Did you test that?

It also means that 
`provide(APP_BASE_HREF, { useValue: '.' })`
doesn't have the same effect as

````
<head>
       <base href=".">
</head>
`````

**Comment by ijager** [comment]
So I've got it working as well now.

I removed `provide(APP_BASE_HREF, { useValue: '.' })` from app.routes.ts.

My index.html looks like this (note the "/"):
````
<head>
       <base href="/">
</head>
````
With  `<base href=".">` it works in a simple project but not with deeplinking in multiple child-routes.   `<base href="/">` seems to fix that. No idea why..

The final fix was to add ` terminal: true ` to empty routes like this:
````
export const approutes: RouterConfig = [
  {path: '', component: StartComponent, terminal:true},
  {path: 'listA', component: ListAComponent,
     children: [
      { path: '', component: StartComponent, terminal:true},
      { path: ':id', component: ChildAComponent }
    ]},
  {path: 'listB', component: ListBComponent},
];
````

I've updated my [example app](https://github.com/ijager/Angular2-Meteor-Router-V3-example) if anyone is interested

**Comment by barbatus** [comment]
I think the reason is simply in what `/` and `.` mean.
'/' is about constructing links relatively to the site path, and '.' - relatively to the current path.
