### ISSUE TITLE
error when using angular2-meteor-auto-bootstrap with angular rc2

### ISSUE THREAD

**Issue by shalaby** [Urigo/angular2-meteor#305]
when using
`
import { bootstrap } from '@angular/platform-browser-dynamic';
`
no problem, but when using
`
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
`
the console shows this error
`
application_ref.js:102Uncaught TypeError: injector.get is not a functioncoreLoadAndBootstrap @ application_ref.js:102(anonymous function) @ meteor_app.js:26(anonymous function) @ meteor_app.js:16withValue @ dynamics_browser.js:23(anonymous function) @ meteor_app.js:15maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38
`

**Comment by derekkite** [comment]
Same issue.
barbatus:typescript           upgraded from 0.3.1 to 0.3.3
barbatus:typescript-compiler  upgraded from 0.5.12 to 0.6.1
"dependencies": {
    "@angular/common": "^2.0.0-rc.2",
    "@angular/compiler": "^2.0.0-rc.2",
    "@angular/core": "^2.0.0-rc.2",
    "@angular/platform-browser": "^2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.2",
    "angular2-meteor": "^0.5.5",
    "angular2-meteor-auto-bootstrap": "^0.5.5",
    "angular2-meteor-polyfills": "^0.1.1",
    "es6-shim": "^0.35.1",
    "meteor-node-stubs": "~0.2.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.9",
    "zone.js": "^0.6.12"
  }

**Comment by JeremyShubert** [comment]
same issue...

**Comment by derekkite** [comment]
From the @angular rc2 changelog...
bootstrap: Swap coreBootstrap() and coreLoadAndBootstrap() arguments (f95a604)

Looks like they changed the order of the arguments.

**Comment by barbatus** [comment]
Should be fixed in the next release
