### ISSUE TITLE
Use observable minimongo as a standalone package in any Angular2 app

### ISSUE THREAD

**Issue by yanisIk** [Urigo/angular2-meteor#306]
The minimongo implementation in angular2-meteor is excellent.
I would like to use it outside of Meteor in a basic Angular2 app.

As of now, this minimongo is the only reactive/observable in memory database available for Angular2.
It would be great to have it as a standalone package.

Meanwhile, can you tell me what I should extract from your code to use it in my Angular2 app ?

Thanks.

**Comment by barbatus** [comment]
It's not an implementation, it's just Minimongo collections support in this package. There is a standalone minimongo NPM  - https://www.npmjs.com/package/minimongo. But it's unlikely reactive. In case of Meteor, all the reactivity is done though Meteor DDP protocol. So you'll either to use Meteor (there is even standalone extraction of Meteor + Minimongo, https://www.npmjs.com/package/minimongo) or implement synchronization yourself.
