### ISSUE TITLE
Can't install @angular

### ISSUE THREAD

**Issue by Gdust** [Urigo/angular2-meteor#307]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\R\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe',
1 verbose cli   'C:\\Users\\R\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@angular' ]
2 info using npm@2.15.1
3 info using node@v0.10.45
4 verbose install initial load of E:\web\angular-meteor\socially7\package.json
5 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\angular2\package.json
6 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\angular2-meteor\package.json
7 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\angular2-meteor-auto-bootstrap\package.json
8 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\angular2-meteor-polyfills\package.json
9 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\es6-shim\package.json
10 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\meteor-node-stubs\package.json
11 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\reflect-metadata\package.json
12 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\rxjs\package.json
13 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\zone.js\package.json
14 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\@angular\common\package.json
15 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\@angular\compiler\package.json
16 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\@angular\core\package.json
17 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\@angular\platform-browser\package.json
18 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\@angular\platform-browser-dynamic\package.json
19 verbose installManyTop reading scoped package data from E:\web\angular-meteor\socially7\node_modules\@angular\router-deprecated\package.json
20 info package.json angular2-meteor-auto-bootstrap@0.5.5 No repository field.
21 info package.json @angular/common@2.0.0-rc.2 No description
22 info package.json @angular/compiler@2.0.0-rc.2 No description
23 info package.json @angular/platform-browser@2.0.0-rc.2 No description
24 info package.json @angular/core@2.0.0-rc.2 No description
25 info package.json @angular/platform-browser-dynamic@2.0.0-rc.2 No description
26 info package.json @angular/platform-browser-dynamic@2.0.0-rc.2 No repository field.
27 info package.json @angular/router-deprecated@2.0.0-rc.2 No description
28 verbose readDependencies loading dependencies from E:\web\angular-meteor\socially7\package.json
29 silly cache add args [ '@angular', null ]
30 verbose cache add spec @angular
31 silly cache add parsed spec { raw: '@angular',
31 silly cache add   scope: null,
31 silly cache add   name: null,
31 silly cache add   rawSpec: '@angular',
31 silly cache add   spec: 'E:\\web\\angular-meteor\\socially7\\@angular',
31 silly cache add   type: 'local' }
32 error addLocal Could not install E:\web\angular-meteor\socially7\@angular
33 verbose stack Error: ENOENT, open 'E:\web\angular-meteor\socially7\@angular'
34 verbose cwd E:\web\angular-meteor\socially7
35 error Windows_NT 10.0.14367
36 error argv "C:\\Users\\R\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\R\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@angular"
37 error node v0.10.45
38 error npm  v2.15.1
39 error path E:\web\angular-meteor\socially7\@angular
40 error code ENOENT
41 error errno 34
42 error enoent ENOENT, open 'E:\web\angular-meteor\socially7\@angular'
42 error enoent This is most likely not a problem with npm itself
42 error enoent and is related to npm not being able to find a file.
43 verbose exit [ 34, true ]

**Comment by barbatus** [comment]
It's not enough info to day where is the problem. Please elaborate and follow the issue description rules.
Re-open when you are done.
