### ISSUE TITLE
not possible to run todos-meteor-1.3 on Win 10 using meteor 1.3.3.1

### ISSUE THREAD

**Issue by nickprusov** [Urigo/angular2-meteor#308]
after running meteor command for example todos-meteor-1.3
W20160621-08:28:53.187(-4)? (STDERR)
W20160621-08:28:54.115(-4)? (STDERR) C:\projects\todos-meteor-1.3\.meteor\local\build\programs\server\shell-server.js:15
W20160621-08:28:54.127(-4)? (STDERR) require("meteor-promise").makeCompatible(Promise, require("fibers"));
W20160621-08:28:54.139(-4)? (STDERR)                           ^
W20160621-08:28:54.148(-4)? (STDERR) TypeError: Object function Promise(fn) {
W20160621-08:28:54.158(-4)? (STDERR)   if (typeof this !== 'object') {
W20160621-08:28:54.169(-4)? (STDERR)     throw new TypeError('Promises must be constructed via new');
W20160621-08:28:54.182(-4)? (STDERR)   }
W20160621-08:28:54.191(-4)? (STDERR)   if (typeof fn !== 'function') {
W20160621-08:28:54.202(-4)? (STDERR)     throw new TypeError('not a function');
W20160621-08:28:54.213(-4)? (STDERR)   }
W20160621-08:28:54.222(-4)? (STDERR)   this._45 = 0;
W20160621-08:28:54.233(-4)? (STDERR)   this._81 = 0;
W20160621-08:28:54.243(-4)? (STDERR)   this._65 = null;
W20160621-08:28:54.253(-4)? (STDERR)   this._54 = null;
W20160621-08:28:54.263(-4)? (STDERR)   if (fn === noop) return;
W20160621-08:28:54.273(-4)? (STDERR)   doResolve(fn, this);
W20160621-08:28:54.285(-4)? (STDERR) } has no method 'makeCompatible'
W20160621-08:28:54.296(-4)? (STDERR)     at Object.<anonymous> (C:\projects\todos-meteor-1.3\.meteor\local\build\programs\server\shell-server.js:15:27)
W20160621-08:28:54.316(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160621-08:28:54.328(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160621-08:28:54.341(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160621-08:28:54.352(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160621-08:28:54.364(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160621-08:28:54.376(-4)? (STDERR)     at require (module.js:380:17)
W20160621-08:28:54.387(-4)? (STDERR)     at Object.<anonymous> (C:\projects\todos-meteor-1.3\.meteor\local\build\programs\server\boot.js:101:3)
W20160621-08:28:54.406(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160621-08:28:54.419(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8
W20160621-08:31:16.582(-4)? (STDERR)
W20160621-08:31:16.593(-4)? (STDERR) C:\projects\todos-meteor-1.3\.meteor\local\build\programs\server\shell-server.js:15
W20160621-08:31:16.607(-4)? (STDERR) require("meteor-promise").makeCompatible(Promise, require("fibers"));
W20160621-08:31:16.618(-4)? (STDERR)                           ^
W20160621-08:31:16.628(-4)? (STDERR) TypeError: Object function Promise(fn) {
W20160621-08:31:16.640(-4)? (STDERR)   if (typeof this !== 'object') {
W20160621-08:31:16.651(-4)? (STDERR)     throw new TypeError('Promises must be constructed via new');
W20160621-08:31:16.664(-4)? (STDERR)   }
W20160621-08:31:16.674(-4)? (STDERR)   if (typeof fn !== 'function') {
W20160621-08:31:16.685(-4)? (STDERR)     throw new TypeError('not a function');
W20160621-08:31:16.695(-4)? (STDERR)   }
W20160621-08:31:16.705(-4)? (STDERR)   this._45 = 0;
W20160621-08:31:16.715(-4)? (STDERR)   this._81 = 0;
W20160621-08:31:16.725(-4)? (STDERR)   this._65 = null;
W20160621-08:31:16.735(-4)? (STDERR)   this._54 = null;
W20160621-08:31:16.745(-4)? (STDERR)   if (fn === noop) return;
W20160621-08:31:16.755(-4)? (STDERR)   doResolve(fn, this);
W20160621-08:31:16.765(-4)? (STDERR) } has no method 'makeCompatible'
W20160621-08:31:16.777(-4)? (STDERR)     at Object.<anonymous> (C:\projects\todos-meteor-1.3\.meteor\local\build\programs\server\shell-server.js:15:27)
W20160621-08:31:16.796(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160621-08:31:16.807(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160621-08:31:16.819(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160621-08:31:16.830(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160621-08:31:16.842(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160621-08:31:16.853(-4)? (STDERR)     at require (module.js:380:17)
W20160621-08:31:16.865(-4)? (STDERR)     at Object.<anonymous> (C:\projects\todos-meteor-1.3\.meteor\local\build\programs\server\boot.js:101:3)
W20160621-08:31:16.884(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160621-08:31:16.895(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)

**Comment by magbeat** [comment]
Seems to be the same issue as: https://github.com/meteor/meteor/issues/7306

**Comment by lucas-issa** [comment]
@magbeat when I executed the command `meteor NPM install meteor-promise@0.7.2 --save` both errors was fixed.

**Comment by barbatus** [comment]
Yes there was meteor-promise dep, it got removed for the next version.

**Comment by jeffersonDesouza** [comment]
after removing meteor-promise in .node_modules it works, in my case was not necessary do "meteor NPM install meteor-promise@0.7.2 --save"
