### ISSUE TITLE
Support Ionic 2.0

### ISSUE THREAD

**Issue by forkmind** [Urigo/angular2-meteor#31]
It's more a question than an issue but did you guys try to get ionic 2 to works with meteor and if yes how did you proceed ?
Edit : The title is not relevant but I cannot edit it anymore

**Comment by barbatus** [comment]
not yet but soon

**Comment by vamsivarikuti** [comment]
@barbatus @Urigo 
Thanks for integrating Angular2 with Meteor. Hope you guys will work your magic with Ionic2.

**Comment by Urigo** [comment]
We would of course love some help from other on that

**Comment by barbatus** [comment]
There is some version going on https://github.com/barbatus/ionic2-meteor

**Comment by Urigo** [comment]
http://www.angular-meteor.com/tutorials/socially/angular2/ionic
thanks @barbatus
