### ISSUE TITLE
`Can't read property 'ref' of undefined` is thrown when using meteor-method's callback

### ISSUE THREAD

**Issue by DAB0mB** [Urigo/angular2-meteor#310]
Hello,
Lately I've been working on an application based on `angular2-meteor` and I've encountered an issue which breaks my app.

When providing a callback to `MeteorComponent.call()` I receive the following error:

    Can't read property 'ref' of undefined

This error is thrown from the view where there is an iteration over a cursor which is related to that method.

Here is a reference to the callback I've been talking about: https://github.com/DAB0mB/ionic2-meteor-chat/blob/issue/method-callback/app/pages/new-chat/new-chat.js#L48
And this is where the error is thrown: https://github.com/DAB0mB/ionic2-meteor-chat/blob/issue/method-callback/app/pages/chats/chats.html#L12

Since your'e probably not familiar with this app I will give a small explanation. I have a `chats` view where you can see all the chats, and I have a `new-chat` view, where you can add chats to the `chats` view. The `new-chat` view is just a dialog box, which means that the `chats` view is not disposed and is still running in background.

I debugged this issue a little bit and ran into the following conclusions. This bug happens when using a parent view with a child view, both using the same data-source. In this case, I call the `addChat` method, which first runs on the client and emits the `add` event on the parent view's subscription on the `chats` cursor. Afterwards, the server returns a response, and the chat document we've just added should also be updated. This is caused due to different values set to the `createdAt` field using the `Date()` constructor, once on the client, and once on the server, they are both ticking in a different time when creating the document. If the server responded quick enough, the `update` should be emitted right after the `add` in the same event-loop. Then, Angular's template engine will try to update the `chat` before it was actually added, which will end up throwing a reference error.

I hope my explanation was clear, it's not an easy issue to explain, but it's a critical one since it breaks my app and prevents it from running properly.

For further explanations and questions Id'e be happy if you could contact me on my email which is listed in my profile page on GitHub.

Thanks!

**Comment by derekkite** [comment]
Is ref a field in a document in the collection you are iterating through?

It is possible you have issues where the component is loaded and initialized before the data is initialized? I ran into this with a moderately complex component and service, and essentially you are into quasi multithreading issues.

**Comment by DAB0mB** [comment]
@derekkite The parent view is never disposed, it is showed in the background. In addition I also tested the solution to your theory by adding a `setTimeout()` or `Tracker.afterFlush()` and both method resulted with the same error.

**Comment by barbatus** [comment]
@DAB0mB When first time did you notice this error?
Meteor methods run on client first only if they are defined on the client, 
is this [file](https://github.com/DAB0mB/ionic2-meteor-chat/blob/227240489345632a14a5ad2bdc0471ab25691d22/api/server/methods.js) with addChat executed on the client?
Does this error persists if you remove `createdAt `?

**Comment by DAB0mB** [comment]
@barbatus When removing the `createdAt` field it works, or when defining this method only on the server, it works as well. The problem seems to occur when there is an update right after an addition of a document. The error is thrown when switching from the `new-chat` view to the `chats` view after calling the `addChat` method.

**Comment by barbatus** [comment]
@DAB0mB I just tried to reproduce this issue on the todo demo (https://github.com/Urigo/angular2-meteor/tree/master/examples/todos-meteor-1.3), but no success. Can you please check out whether it's reproducible for you with the master's version. If not, can you tell me how to run your project quickly?

**Comment by DAB0mB** [comment]
@barbatus just render a tasks list on the view, call the method `tasks.add` *provided with a callback*, the view should fail to update with the error message I just mentioned.

**Comment by barbatus** [comment]
@DAB0mB Yes, it's what it does now (see https://github.com/Urigo/angular2-meteor/blob/master/examples/todos-meteor-1.3/client/app.ts#L22). So I am trying to reproduce (with callback or not), and no luck. Are you saying that you tried and saw this error?

**Comment by DAB0mB** [comment]
@barbatus I will try to run your app and see if it happens to me. You are welcome to use my app as well maybe you can analyze the cause of this error better than I did

**Comment by barbatus** [comment]
So I wasn't able to reproduce that error exactly  `Can't read property 'ref' of undefined`.
The only thing I found out not right is autoruns in the doc transform method here (https://github.com/DAB0mB/ionic2-meteor-messenger/blob/master/app/pages/chats/chats.js#L55). This won't work due to Meteor's ngFor relies on the Mongo cursor updates and is not aware of any manual changes.
Also, you tend to overuse autoruns in general. For example, it seems to be not needed [here](https://github.com/DAB0mB/ionic2-meteor-messenger/blob/master/app/pages/chats/chats.js#L29).

**Comment by barbatus** [comment]
@DAB0mB do you mind to say status of this

**Comment by DAB0mB** [comment]
@barbatus Excuse me for the late reply. I tested my issue against the newest version of `angular2-meteor` and this problem doesn't seem to appear anymore. Thanks for the support I think the issue can be closed :-)

**Comment by barbatus** [comment]
Ok, as a side note, autoBind is now true by default, so you can skip passing it.

**Comment by yuyinitos** [comment]
@DAB0mB I've got the same issue. To which version of `angular2-meteor` did you update exactly?
