### ISSUE TITLE
Angular rc3 upgrade

### ISSUE THREAD

**Issue by onhate** [Urigo/angular2-meteor#313]
Hello,

Any plans to upgrade the angular dependencies to rc3?

**Comment by barbatus** [comment]
Yes we are planning some major release on the next week.

**Comment by onhate** [comment]
Is there something I can do to help?

**Comment by davidbonachera** [comment]
Already RC4.

**Comment by ayazhussein** [comment]
When can we use RC4?

**Comment by watalberto** [comment]
Hey, it's not working since RC2, angular realease 3 RC really quick, I guess because they have issues in RC2 and 3, so would be great if you directly realease a new version with angular RC4. do you know more or less when we have it available? I have some dependencies problems... my app doesn't work on safari due to google-maps lib issue and to fix it I need their last v. which needs RC2, e.g.

Thanks you!!

**Comment by derek-fong** [comment]
@onhate @watalberto Looks like this is working for me with RC4

```
  "dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "@angular/router": "^3.0.0-beta.2",
    "angular2-meteor": "^0.5.6-beta.1",
    "angular2-meteor-auto-bootstrap": "^0.5.6-beta.1",
    "angular2-meteor-polyfills": "^0.1.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.6",
    "zone.js": "^0.6.12"
  }
```

**Comment by watalberto** [comment]
@derek-fong master is '0.5.5', where did you get '0.5.6-beta.1'?

**Comment by derek-fong** [comment]
`meteor npm install angular2-meteor --save`

`0.5.6-beta.1` is the [latest release](https://www.npmjs.com/package/angular2-meteor)

**Comment by watalberto** [comment]
hmm, okay, here in github latest is hidden, I gonna try then, thanks @derek-fong

**Comment by mackbrowne** [comment]
Still can't get this working.  Does anyone have a currently-working github project I could try?

**Comment by derek-fong** [comment]
@mackbrowne what's the error message you are getting?

**Comment by Urigo** [comment]
0.5.6 is out with support for Angular rc.4
@mackbrowne please let me know if a new project works for you and if we can close this
