### ISSUE TITLE
Meteor.isDevelopment not triggering true

### ISSUE THREAD

**Issue by MichaelSolati** [Urigo/angular2-meteor#314]
When I try to use Meteor.isDevelopment and Meteor.isProduction on the server for some insertions, Development never triggers (it's always in Production). Not 100% sure if it's Angular 2, but I never had this come up with Angular 1....

**Comment by barbatus** [comment]
I don't see how this package can affect it. As you know, prod/dev defined by NODE_ENV var, so I can only advise to check it
