### ISSUE TITLE
Relative component path

### ISSUE THREAD

**Issue by Richie765** [Urigo/angular2-meteor#317]
Angular 2 support relative component paths, but somehow it doesn't seem to work with angular2-meteor. Could this be implemented? It would make moving pages/components around much easier. 

```javascript
@Component({
  templateUrl: 'page.html',
})
```

**Comment by derek-fong** [comment]
@Richie765 assuming you have both `foo.component.ts` and `foo.component.html` in the same folder, 

```ts
import { Component } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'demo-foo',
  'templateUrl: 'foo.component.html'
})
export class FooComponent extends { }
```

**Comment by barbatus** [comment]
In the next version of angular2-compilers, template won't be exposed as assets since we recommend to use template content directly, check out https://github.com/Urigo/angular2-meteor#static-resources

**Comment by Richie765** [comment]
@derek-fong, thanks, that works!

@barbatus, that is great. I was looking for a way to include the templates directly! I couldn't get this to work though.

When I add:
```javascript
import template from  './page.html';
console.log(template);
```

I get:
```
/client/pages/page/page.html?hash=fee6b066dff962b214182cc4bb1f4c99d40a26c4
```

So that would be the URL, not the template itself. I figured I might need to
```bash
meteor add urigo:static-templates
```

But then I get errors like:
```
   While determining active plugins:
   error: conflict: two packages included in the app (urigo:static-templates and angular2-compilers) are both trying to handle
   *.html
```
How to solve this?

**Comment by Tallyb** [comment]
Go with inline template (with backticks). Easier to work with an no issues.

**Comment by Richie765** [comment]
@Tallyb, I think that's a matter of opinion. Editor features like syntax highlighting, reformatting and autocomplete won't work. Also there will be no way to pre-compile the template so it will be exposed as-is to the outside world. So I think keeping things separate has its advantages.

BTW I'm not sure if the templates are currently pre-compiled (can anyone clarify?), but by keeping the templates in their own files at least gives that possibility.

**Comment by Urigo** [comment]
@Richie765 we will release a new version of `angualr2-compilers` that will remove `angular2-html-templates` in favor of `urigo:static-templates`.
In the meantime, you can use the beta for that - `angualr2-compilers@-beta.2`  (not a final version, we are still improving things and will probably release tonight or tomorrow a complete version)

**Comment by barbatus** [comment]
@Richie765 what do you mean by pre-compile? they are minified currently for the prod.

**Comment by Richie765** [comment]
@barbatus, I'm not an Angular expert, just been using it for a month. I notice bootstrap was slow sometimes and that the templates were downloaded in their original form (even not minified in my case, but I'm not using the latest versions yet).

Isn't there a smarter way than doing the parsing client-side? Like Blaze compiles the templates into JavaScript perhaps something similar is possible in Angular? Anyway, using the templates directly is already an improvement. Going to upgrade my versions and try it out next week.

**Comment by barbatus** [comment]
@Richie765 yes, there is one https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli.

But since it's quite complex and Meteor's compilation process is quite fragmented, I don't see any way currently to hook it up. From other side, Meteor will support async loading of the modules in the future, so I hope we'll make it everyone can load components when they are needed with the new ng router. So the load will be decreased to some extent.

**Comment by Urigo** [comment]
this is a subject we are thinking about and would love help and collaboration from others as well

**Comment by Richie765** [comment]
@Urigo, just upgraded ```angular2-compilers``` and loading the templates with ```import``` and relative paths works like a charm! Thanks!

I get a lot of typescript errors "Cannot find module './page.html'". I suppose the only way to get rid of these errors is the same as described here: https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/css-compiler

**Comment by Urigo** [comment]
@Richie765 yes exactly

**Comment by jmarceli** [comment]
@Richie765 How did you solve this issue? (the link in your post is dead)
