### ISSUE TITLE
There is already a collection named "collection" in angular 2 + meteor

### ISSUE THREAD

**Issue by i-am-vivek** [Urigo/angular2-meteor#318]
```
import {Mongo} from 'meteor/mongo';
export let Products = new Mongo.Collection('products');
```

above code is that I've written in my sample project. When I try to run this sample project, It throws error

> There is already a collection named "products"

I've tried `meteor reset`. still I am facing same issue. I googled but got no proper solution. can anyone help me out?

**Comment by Jitra** [comment]
Had the same issue, it's like when I use ts files and let IDE to transpile it into js for me, meteor autoloads both js and ts files which causes errors. Deletion transpiled js files helps

**Comment by barbatus** [comment]
your IDE compiles ts-files as well, check "compileOnSave": false,  "buildOnSave": false in the config

**Comment by hayk94** [comment]
Hello guys I am having a similar issue, however checking "compileOnSave": false, "buildOnSave": false 
in my tsconfig.json file is not helping. Please help me.

**Comment by clouchtibat** [comment]
Same for me, I updated the tsconfig.json and removed the generated js and js.map files but I still have the error.

**Comment by drypa** [comment]
this fix is correct. but also need delete compiled js files.

**Comment by richardmarais** [comment]
I am also getting this error:

```
      Error: There is already a collection named "chats"
require<.node_modules.meteor.mongo["collection.js"]/Mongo.Collection
```

However, I don't know what transpiled js files to delete.

I delete all `*.js.map` files under `www`. When I run `ionic serve` it creates an `app.bundle.js.map` as expected. But I still get the `Error: There is already a collection named "chats"` error at `app.bundle.js:334:14943`.

Any help please.

**Comment by allamgr** [comment]
Im using WS and have the same problem
