### ISSUE TITLE
Webpack angular 2

### ISSUE THREAD

**Issue by paralin** [Urigo/angular2-meteor#320]
With webpack and angular 2 I'm getting these errors. 

https://github.com/thereactivestack/meteor-webpack/issues/216

Can you guys shed some light on this perhaps?

**Comment by barbatus** [comment]
Try latest verson of angular2-meteor

**Comment by paralin** [comment]
Still tons of errors, here are a few related to angular2-meteor

```
ERROR in /home/paralin/Documents/project/node_modules/angular2-meteor/dist/patch.d.ts
(4,19): error TS2304: Cannot find name 'Zone'.

ERROR in /home/paralin/Documents/project/node_modules/angular2-meteor/dist/patch.d.ts
(6,27): error TS2304: Cannot find name 'Zone'.

ERROR in /home/paralin/Documents/project/node_modules/angular2-meteor/dist/patch.d.ts
(7,23): error TS2304: Cannot find name 'Zone'.

ERROR in /home/paralin/Documents/project/node_modules/angular2-meteor/dist/patch.d.ts
(8,22): error TS2304: Cannot find name 'Zone'.

```

**Comment by barbatus** [comment]
You'll need to install zone.js typings and other required typings. Please read docs before opening an issue.

**Comment by paralin** [comment]
... there's still a lot more than that wrong...

```
ERROR in ./~/@angular2-material/input/input.js
Module not found: Error: Cannot resolve module 'rxjs/Observable' in /home/paralin/Documents/project/node_modules/@angular2-material/input
 @ ./~/@angular2-material/input/input.js 21:19-45

ERROR in ./~/@angular2-material/input/input.js
Module not found: Error: Cannot resolve module '@angular2-material/core/annotations/field-value' in /home/paralin/Documents/project/node_modules/@angular2-material/input
 @ ./~/@angular2-material/input/input.js 19:20-78

ERROR in ./~/@angular2-material/input/input.js
Module not found: Error: Cannot resolve module '@angular2-material/core/errors/error' in /home/paralin/Documents/project/node_modules/@angular2-material/input
 @ ./~/@angular2-material/input/input.js 20:14-61

ERROR in ./imports/panel/panel-layout.ts
Module not found: Error: Cannot resolve module '@angular/router/src/url_tree' in /home/paralin/Documents/project/imports/panel
 @ ./imports/panel/panel-layout.ts 20:17-56

ERROR in ./imports/platform-gallery/platform-gallery.ts
Module not found: Error: Cannot resolve module '@angular/router/src/url_tree' in /home/paralin/Documents/project/imports/platform-gallery
 @ ./imports/platform-gallery/platform-gallery.ts 21:17-56

ERROR in ./~/@angular/common/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/common_directives in /home/paralin/Documents/project/node_modules/@angular/common
 @ ./~/@angular/common/index.js 15:9-43

ERROR in ./~/@angular/common/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/localization in /home/paralin/Documents/project/node_modules/@angular/common
 @ ./~/@angular/common/index.js 17:21-50

ERROR in ./~/@angular/common/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/pipes in /home/paralin/Documents/project/node_modules/@angular/common
 @ ./~/@angular/common/index.js 12:9-31

ERROR in ./~/@angular/common/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/directives in /home/paralin/Documents/project/node_modules/@angular/common
 @ ./~/@angular/common/index.js 13:9-36

ERROR in ./~/@angular/common/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/forms-deprecated in /home/paralin/Documents/project/node_modules/@angular/common
 @ ./~/@angular/common/index.js 14:9-42

ERROR in ./~/@angular/common/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/location in /home/paralin/Documents/project/node_modules/@angular/common
 @ ./~/@angular/common/index.js 16:9-34
```

**Comment by paralin** [comment]
If you're so confident I'm just not reading some kind of documentation about this, then could you please point me to the relevant docs??

```
   looking for modules in /home/paralin/Documents/project/node_modules
   resolve 'file' loglevel in /home/paralin/Documents/project/node_modules
   resolve file
   /home/paralin/Documents/project/node_modules/loglevel is not a file
   /home/paralin/Documents/project/node_modules/loglevel.css doesn't exist
   /home/paralin/Documents/project/node_modules/loglevel.ts doesn't exist
   /home/paralin/Documents/project/node_modules/loglevel.scss doesn't exist
   /home/paralin/Documents/project/node_modules/loglevel.sass doesn't exist
   /home/paralin/Documents/project/node_modules/loglevel.json doesn't exist
```

Getting this now.

**Comment by paralin** [comment]
Look, this stuff doesn't work, I've tried literally every variation of what you've got in your docs, you can't just say "Please read docs before opening an issue" when there's no documentation at all on this particular problem

**Comment by barbatus** [comment]
Look, here is not a day care. I told you if you have an issue specifically related to your app, here is a list of resources for questions https://github.com/Urigo/angular2-meteor#questions-and-issues

**Comment by paralin** [comment]
???

It's a bug not a question. You reply "use the latest version of angular2-meteor" which implies you've actually tested this and gotten it to work. 

Reporting a bug is not a "day care" type thing. I could understand that if I was asking something simple about how angular2-meteor works. 

Pure laziness.

**Comment by barbatus** [comment]
Look, I told to install latest version of angular2-meteor. That helped you move to the next step. Then I told you to install typings that fixed you again. And now you are saying those were bugs of the package. I'd be glad to help but you were too cocky. Don't be enemy of yourself.

**Comment by paralin** [comment]
`I'd be glad to help but you were too cocky`

Only because you said

`Please read docs before opening an issue.`

This is **not** documented or a standard thing (using webpack with angular2). You implied I had just not read the docs and was being lazy. Not so.

**Comment by Urigo** [comment]
I'm sorry but I'm stopping the conversation here.
There is no reason for that language in the `angular-meteor` community.

If you have comments like those here or need help with talking to someone on an issue, please email them directly to me, my personal email is public on my Github profile.

**Comment by paralin** [comment]
What comments? There's no documentation on this so it makes no sense to say "read the docs"

**Comment by Urigo** [comment]
even if you don't agree with someone, please don't let the conversation get there.
If you have a problem, please feel free to email me
