### ISSUE TITLE
Callback issues with MeteorComponent "autoBind"

### ISSUE THREAD

**Issue by Richie765** [Urigo/angular2-meteor#323]
First of all, could the ```autoBind``` parameter be documented better? I know it will bind to the NgZone, but what does that mean exactly? I thought it had to do with getting a better stack trace with errors, but I don't see that. I only notice sometimes I need to bind the subscription or otherwise I won't see the results immediately in my template.

**MeteorComponent.call**. When ```autoBind``` is true, the callback is called in a wrong way. Normally the callback is ```function(err, res)```, but when ```autoBind``` is true, the callback is called like ```function([err,res])```, e.g. both parameters are passed inside an array. I think the ```autoBind``` parameter is superfluous, because if you don't want to bind you can just as well call ```Meteor.call```. Perhaps that could at least be documented.

**MeteorComponent.subscribe**. When ```autoBind``` is true, and the ```resultCallback``` is an object, it seems all fields: ```onReady```, ```onStop``` and ```onError``` are required. All of them should be optional. IIRC both ```onStop``` and ```onError``` incorrectly receive the error inside an array in the first parameter.

**MeteorComponent.autorun**. Haven't used this one yet, but looking at the docs and the source code it seems there is no way to specify the ```onError``` option, like the one of ```Tracker.autorun```.

Hope this can be solved. Starting to like Meteor with Angular 2 :-)

**Comment by barbatus** [comment]
Which version of the angular2-meteor are using?
autoBind now is true by default.

**Comment by Richie765** [comment]
I'm at 0.5.5, I thought that was the latest. I can't update right now since I got some RC.1 dependencies. Not sure how much has been fixed already.

**Comment by Urigo** [comment]
in terms of angular2-meteor, we support and tested with the latest RC.4 so we shouldn't hold you back from updating

**Comment by Urigo** [comment]
released in 0.6.2
