### ISSUE TITLE
Proper use of Static Resources?

### ISSUE THREAD

**Issue by derek-fong** [Urigo/angular2-meteor#324]
I have just upgraded my project to `angular2-meteor@0.5.6` but when I try to test out [Static Resources](https://github.com/Urigo/angular2-meteor#static-resources) with style files by following the documentation [here](https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/css-compiler#usage) 

```
import styleUrl from './foo.less!url';

@Component({
  selector: 'foo',
  styleUrls: [styleUrl]
})
class Foo { }
```

I get this error message 

> Unable to resolve some modules:
>
> "./foo.less!url" in
> /Users/project/.../Foo.component.ts
> (web.browser)

And when I try the code below

```
import style from './foo.less'

@Component({
  selector: 'foo',
  styles: [style]
})
class Foo { }
```

I get this error message on client's browser console

> zone.js:463 Error: Uncaught (in promise): Expected 'styles' to be an array of strings.

Am I missing something?

**Comment by Urigo** [comment]
can you try the beta version of `angular2-compilers@0.6.0beta.2`  ?

**Comment by derek-fong** [comment]
@Urigo Yep will give it a try tonight and will let you know the outcome.

**Comment by derek-fong** [comment]
@Urigo After updating `angular2-compilers@0.6.0`I got this error message: 

> Errors prevented startup:
>
> While processing files with angular2-compilers (for target web.browser):
> /src/app/client/main.scss: Scss compiler error: File to import: {poetic:materialize-scss}/sass/components/_color.scss not found in file: /foo/{}/src/app/client/main.scss
>
> Your application has errors. Waiting for file change.

**Comment by Urigo** [comment]
Are your SASS imports has the right path?

Here is an example - https://github.com/Urigo/meteor-angular2.0-socially/blob/master/client/css/main.scss#L1-L5

**Comment by derek-fong** [comment]
@Urigo yes the path is correct. I did not change any code in the project and it was working fine until I ran  

`meteor remove fourseven:scss`
`meteor update`

**Comment by barbatus** [comment]
@derek-fong I think you'll need to switch to one a NPM package such as https://www.npmjs.com/package/materialize-sass. The package you are using won't work any more, since it depends on `fourseven:scss`, we are using a fork of `fourseven:scss`.

**Comment by derek-fong** [comment]
Thanks @barbatus I have removed meteor package `poetic:materialize-scss` and added npm `materialize-css` and now I am able to import the HTML templates however I am still having the styles issue when attempting to import `.less` or `.scss` files. 
> Error: Uncaught (in promise): Expected 'styles' to be an array of strings.

**Comment by barbatus** [comment]
@derek-fong it's likely means some paths are incorrect

**Comment by derek-fong** [comment]
@barbatus Here's my (simplified) project structure.  

```
project
|-- .meteor
|-- node_modules
|-- src
|   `-- app
|       |-- client
|       |   |-- imports
|       |   |   |-- app
|       |   |   |    |-- app.component.html
|       |   |   |    |-- app.component.ts
|       |   |   |    `-- app.routes.ts
|       |   |   `-- foo
|       |   |        |-- foo.component.html
|       |   |        |-- foo.component.ts
|       |   |        `-- foo.component.scss
|       |   |
|       |   |-- main.html
|       |   |-- main.scss
|       |   `-- main.ts
|       `-- server
|           |-- publications
|           `-- main.ts
|-- typings
|-- package.json
|-- tsconfig.json
`-- typings.json  
```

As you can see `foo.component.ts` and `foo.component.scss` are both in the same folder so I would expect `import style from './foo.component.scss'` should resolve? Or is my project's structure causing the problem?

**Comment by derek-fong** [comment]
OK after spending some time playing with the codes I think I've identified what the problem is...

Consider the project structure below: 

```
project
|-- .meteor
|-- node_modules
|-- client
|   `-- imports
|       `-- bar
|            |-- bar.component.html
|            |-- bar.component.scss
|            `-- bar.component.ts
|-- imports
|   `-- foo
|       |-- foo.component.html
|       |-- foo.component.scss
|       `-- foo.component.ts
|-- server
|   |-- publications
|   `-- main.ts
|-- typings
|-- package.json
|-- tsconfig.json
`-- typings.json  
```

`foo.component` styles works perfectly while `bar.component` throws `Expected 'styles' to be an array of strings.` error. 

As my current project structure follows the [meteor-angular2.0-socially](https://github.com/Urigo/meteor-angular2.0-socially) tutorial, I am now a bit confused that shall I place all my components in `client/imports/some-feature` (which follows socially) or `imports/some-feature` (which works with importing styles)?

**Comment by barbatus** [comment]
Meteor's guide recommends to use `imports/client` in this case (see https://guide.meteor.com/structure.html#javascript-structure). Though, `client/imports` could also make sense, and it seems to be supported in the Meteor source code, to my mind, keeping it in `imports/client` or `client/imports` is a minor detail.

**Comment by derek-fong** [comment]
@barbatus Thanks for clarifying this - Closing this issue now.
