### ISSUE TITLE
Type Mongo.Cursor is not generic

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular2-meteor#325]
This definition (in socially - party-details) 
      `users: Mongo.Cursor <Object>;`
 is showing a red squiggle under `Object` saying `Type Mongo.Cursor is not generic`
Any thoughts?

**Comment by barbatus** [comment]
Which typings are you using? In the tests for Meteor 1.3 it does not curse (https://github.com/meteor-typings/meteor/blob/master/1.3/test/test.ts#L355)
