### ISSUE TITLE
Typescript errors when importing templates

### ISSUE THREAD

**Issue by nebiljabari** [Urigo/angular2-meteor#328]
Like I prefer to use Angular2 best-practice App structure I thought it was a mistake coming from me but it happend directly from the step 0 of the tutorial despite that the App run.
_PS: issue not present in last version_
![angular2-meteor](https://cloud.githubusercontent.com/assets/16270454/16709215/89fb3a62-460a-11e6-80f5-9f843371b8d0.png)

**Comment by Urigo** [comment]
It's present in the latest version?
Meaning it's working?

Can you share you `.meteor/versions` file?

**Comment by nebiljabari** [comment]
please be my guest
[versions.txt](https://github.com/Urigo/angular2-meteor/files/355767/versions.txt)

**Comment by nikhammerellis** [comment]
I am actually having a similar issue but it is happening in step 4, right before the Event Handlers section. The app isn't finding any of the templates. 

Here is the terminal output: 
client/imports/parties-form/parties-form.ts (5, 22): Cannot find module './parties-form.html'.
client/app.ts (6, 29): Cannot find module 'client/imports/parties-form/parties-form.html'.
client/app.ts (8, 22): Cannot find module './app.html'.

Unable to resolve some modules:

  "client/imports/parties-form/parties-form.html" in
/Users/Nik/Documents/Meteor/socially/client/app.ts (web.browser)

Here is a link to my codebase for the tutorial so far: 
https://github.com/nikhammerellis/meteor-angular2-example

Let me know if you need any more info, keep up the good work!

**Comment by Urigo** [comment]
Yes, those Typescript error are because the way Meteor compiles Typescript.

these errors will be solved with Typescript 2.0 as described here: https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/css-compiler

**Comment by Urigo** [comment]
by the way, @barbatus , is it already available in `typescript@next`?
I've seen milestone 2.0 is almost done and maybe we can start recommending people to use it?

**Comment by barbatus** [comment]
yes, TypeScript 2.0 is in Beta now. I'll see if we can update prob this week.

**Comment by barbatus** [comment]
@nikhammerellis your path is incorrect. Paths should be relative in the node resolution mode.
I.e. `client/imports/parties-form/parties-form.html` -> `./imports/parties-form/parties-form.html`

**Comment by nikhammerellis** [comment]
@barbatus thanks. That helped a ton.

**Comment by nikhammerellis** [comment]
It's actually still not finding ./app.html or ./parties-form.html and those paths look correct

**Comment by dohomi** [comment]
@Urigo is this actually resolved? I'm running the latest version of angular2 and still receiving the error message with the typings:
`Cannot find module './translationList.html'`
Beside that the app loads as expected.
Thanks

**Comment by dohomi** [comment]
I was reading further, the typescript errors will be gone when TypeScript 2.x is released? Then I'll ignore them

**Comment by lionax** [comment]
It would be helpful if this was mentioned in the guide. Researched almost an hour only to read this and to find out that I only have to ignore this until 2.0 will be released - oh man... :)

**Comment by stefanholzapfel** [comment]
I'm using typescript 2.1.4 and the newest typings and still get the "Cannot find module '.xxxxx.html' error message.

Is it still a known problem or is something wrong with my config?

Thanks!

**Comment by Slavrix** [comment]
I also still have this as a problem.
I've reverted to using 
`templateUrl: 'path/to/file.'`
because even if using the import is best practice, no errors works better for me.

**Comment by hoebbelsB** [comment]
the answer to the problem is available here: https://www.npmjs.com/package/angular2-meteor#static-resources

**Comment by mattiLeBlanc** [comment]
I installed the global typings but still have the squiggly red line under my 'html' template import. Do I need to add something to `tsconfig` too?

**Comment by ztischenko** [comment]
I have TypeScript 2.5.2 installed, and while `import template from './app.html'` results in page being loaded in browser, as expected, there is, however, still error in VisualStudio Code, saying "Cannot find module" from typescript.

Did anyone have resolved this issue?

**Comment by mattiLeBlanc** [comment]
have you tried adding a typing
```
declare module '*.html' {
  const value: Function;
  export default value;
}
```

**Comment by ztischenko** [comment]
Thanks for your input, @mattiLeBlanc : I had added 
`declare module '*.html' {
  const value: Function;
  export default value;
}`

into meteor-app/declarations.d.ts , however, the pesky red wavy underline is still there. 
Not sure if relevant, I noticed I had a file meteor-app/typings/globals/angular2-compilers/index.d.ts that had originally this definition for *html
`declare module "*.html" {
  const template: string;
  export default template;
}`

I had tried both - updating declaration inside this index.d.ts file and adding it to declarations.d.ts  - no luck.

**Comment by mattiLeBlanc** [comment]
It could be a tsconfig issue.
Mine looks like:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./typings",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "skipLibCheck": true,
    "stripInternal": true,
    "noImplicitAny": false,
    "typeRoots": [
      "node_modules/@types/"
    ],
    "types": [
      "meteor-typings",
      "@types/underscore",
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    ".meteor"
  ],
  "compileOnSave": false
}
```
and I am importing `.pug` instead of .html.
So actually, the example I gave you is wrong. 

```
declare module "*.html" { const template: string; export default template; }
```
is the right one. Pug is returning a function, hence the function declaration in my answer, but HTML will not be a Function but just a String.

Still I think it has to do with your tsconfig.json.
I also have `typings/globals/angular2-compilers` which has the index.d.ts with those declarations.

**Comment by Zory1** [comment]
@mattiLeBlanc - thanks a million for looking into it! Your tsconfig.json had resolved the issue. I am not entirely sure why (and I can live with that for now) my tsconfig did not work, but the fields that were different were baseUrl (mine was '.'), module (mine was 'umd') and typeRoots (mine did not have any) - in case if that would help someone else out there.

Again - thank you very much for helping out with this one!

**Comment by mattiLeBlanc** [comment]
@Zory1 No problem mate. I was running in the same issue before with the PUG files and fiddling with the TSCONFIG helped. You could remove keys from your config to see when the red squiggly text shows up again.
