### ISSUE TITLE
Templates not working properly

### ISSUE THREAD

**Issue by paralin** [Urigo/angular2-meteor#329]
After the latest update loading a import at for example:

`/imports/dropdown/dropdown.html`

Just returns the entire meteor app.

I have the latest of everything and angular2-polyfills, angular2-runtime, and angular2-compilers installed.

I'm not seeing the "Compiling html template" message anymore.

Pretty big problem, any ideas @barbatus ?

**Comment by barbatus** [comment]
Use relative paths for the node resolution mode. And please read docs casually.

**Comment by paralin** [comment]
`And please read docs casually.`

Worked fine in the last version, latest update just broke the app

**Comment by Urigo** [comment]
again, same type of language I don't think belongs here.
please stop.

**Comment by paralin** [comment]
?? What type of language are you referring to?

Again you condescending tell me to read the docs when there's nothing in the docs about this, and expect me to accept that as a response.

**Comment by Urigo** [comment]
I didn't say who said the bad comments.
If you see that the conversation is going to a wrong place, even if it's not your fault, please email me.
