### ISSUE TITLE
Why is the repo called Meteor-Angular2 instead of angular2-meteor?

### ISSUE THREAD

**Issue by carlosbaraza** [Urigo/Angular2-Meteor#33]
Hi @Urigo,

This question may be justified, but it feels a bit confusing the fact that the repo is called *Meteor-Angular2*, while the previous repo was called *angular-meteor*.

I expect this repository to grow, so I though it might be interesting to keep consistency calling it *angular2-meteor*.

Carlos.

**Comment by carlosbaraza** [comment]
By the way, thank you very much for all the work. It looks amazing.

**Comment by barbatus** [comment]
@Urigo what do you think? it kinda makes sense for me as well. Btw, it would be nice to add repo description too.

**Comment by Urigo** [comment]
Done.
Would love to hear more suggestions to the description, I'm not sure I wrote the best thing

**Comment by carlosbaraza** [comment]
@Urigo Haha, I like the description.

Though, being a bit picky, I don't like the capitalisation in the repo name ;). Just personal preference, no need to be changed.
