### ISSUE TITLE
Support for Node 4

### ISSUE THREAD

**Issue by puedesleerlo** [Urigo/angular2-meteor#330]
Hello everyone, I'm trying Meteor 1.4 beta 9 and the package angular2-compilers doesn't work, it seems the problem is the dependency barbatus:scss-compiler because it doesn't have an appropiately bind for Node 4.

` /home/alejandro/.meteor/packages/angular2-compilers/.0.6.0.at3ede++os.linux.x86_64+web.browser+web.cordova/plugin.Angular2Compilers.os.linux.x86_64/npm/node_modules/meteor/barbatus_scss-compiler/node_modules/node-sass/lib/index.js:15:11:
   Missing binding
   /home/alejandro/.meteor/packages/angular2-compilers/.0.6.0.at3ede++os.linux.x86_64+web.browser+web.cordova/plugin.Angular2Compilers.os.linux.x86_64/npm/node_modules/meteor/barbatus_scss-compiler/node_modules/node-sass/vendor/linux-x64-46/binding.node
   Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x
   
   Found bindings for the following environments:
   - Unknown environment (.meteor-portable)
   - Linux 64-bit with Node 0.10.x
`

Do you know if there is a solution?

**Comment by paralin** [comment]
It's a tracked issue.

To fix it do this:

```
cd  /home/alejandro/.meteor/packages/angular2-compilers/.0.6.0.at3ede++os.linux.x86_64+web.browser+web.cordova/plugin.Angular2Compilers.os.linux.x86_64/npm/node_modules/meteor/barbatus_scss-compiler/
meteor npm rebuild node-sass
```

That should fix it.

**Comment by Urigo** [comment]
thanks for the help @paralin 
could you also link to the track issue please?
thanks!

**Comment by paralin** [comment]
https://github.com/meteor/meteor/issues/7297#event-719489034

**Comment by puedesleerlo** [comment]
Thanks a lot
