### ISSUE TITLE
Barrels do not work any more

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#332]
After updating **angular2-compilers** from 0.5.7 to 0.6.0
It dose not support the Barrels any more.
angular2-compilers 0.5.8 also does not support.

Say I have a folder.
```
foo
-- aa.component.ts
-- bb.component.ts
-- index.ts
```

index.ts
```
export * from './aa.component';
export * from './bb.component';
```

Using Barrels, I can do `import { AaComponent, BbComponent } from './foo';`, however now it does not work any more.
____
Now I have to import like this:
```
import { AaComponent } from './foo/aa.component';
import { BbComponent } from './foo/bb.component';
```

**Comment by barbatus** [comment]
A dup of https://github.com/barbatus/typescript-compiler/issues/17
