### ISSUE TITLE
Tutorial step 8 - Changins in auth modules

### ISSUE THREAD

**Issue by mariohmol** [Urigo/angular2-meteor#333]
Hi there,

i'm trying to make the tutorial: http://www.angular-meteor.com/tutorials/socially/angular2/user-accounts-authentication-and-permissions

But i'm having problems, because we had some changings in angular-route v3 and angular2-meteor-accounts-ui/.

If you see the discussion here: https://github.com/Urigo/angular2-meteor-accounts-ui/pull/22

We do not have `CanActivate` and `RequireUser` anymore. 

So its necessary to update tutorial with new changes.

**Comment by barbatus** [comment]
RequireUser has nothing to do with the routing and should work now, as for router annotations, we'll add RequireUserGuard soon and change 'Routing Permissions' chapter accordingly soon. Otherwise closing it here. Please move it to the Socially repo if you feel it's necessary
