### ISSUE TITLE
The store state only shows initial state

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#335]
I am using [ngrx/store](https://github.com/ngrx/store). I met a problem that it only shows store **initial states** when I go to another page. It dose not show the complete states (**initial state** + **user generated states**).

Originally I created at https://github.com/ngrx/store/issues/171, but seems related with **angular2-meteor**.

When I go to the Test page, it does not show user generated data. I have to click Dispatch button to dispatch something to show all store states.

![image](https://cloud.githubusercontent.com/assets/3375461/16820463/20fbebac-491f-11e6-8ded-bbd50c20d25a.png)

Once I click Dispatch button, then it shows all states like below:
![image](https://cloud.githubusercontent.com/assets/3375461/16820466/287b5336-491f-11e6-9d94-66bc5db79ddf.png)

It seems related with **angular2-meteor**. Because the same code works well in [plunker](https://plnkr.co/edit/yVYevDcoDAd7jcR8qf4Q?p=preview).
When you go to Test page, it shows user generated data immediately.

____

I created a angular2-meteor version reproduction here too
https://github.com/Hongbo-Miao/bug-ngrx, you can download,

Once run `npm i`, then just `meteor` to run it.

**Comment by barbatus** [comment]
i don't see where do you use angular2-meteor in your demo

**Comment by Hongbo-Miao** [comment]
@barbatus it uses Meteor package angular2-compilers (I guess related with this?).
And if need, you can change `import { bootstrap } from '@angular/platform-browser-dynamic';` to `import { bootstrap } from 'angular2-meteor-auto-bootstrap';`.

I use `import { bootstrap } from '@angular/platform-browser-dynamic';` just want to make sure it is not related with this.

**Comment by barbatus** [comment]
I don't understand how it's supposed to work. AsyncPipe only marks a component to be checked, it doesn't run ngZone. So if ngRouter loads initial component synchronously initial effect changes won't be recognized.
And it's certainly not related to Meteor since Angular2-Meteor is not used at all, only TypeScript compiler

**Comment by Hongbo-Miao** [comment]
thanks for the thoughts!
