### ISSUE TITLE
Problem Acquiring Angular2 Typings

### ISSUE THREAD

**Issue by LelouchLight** [Urigo/angular2-meteor#336]
I have attempted to download/find the angular 2 typing, but when I try to "typings install angular2" it says that the typing can not be located.

**Comment by Hongbo-Miao** [comment]
There is no need to install angular2's typings manually.

**Comment by LelouchLight** [comment]
@Hongbo-Miao Thanks for your reply. I'm not sure if it installed for me. It wasn't in my main typings folder, and I can't find it anywhere else in my project, which was built from scratch quite recently. Although maybe I have it under another name and my problem is unrelated. But the new method of importing templates "import template from './example.html';" keeps giving me a "cannot find module error".

**Comment by Hongbo-Miao** [comment]
The typings files (*.d.ts) are in different folders of node_modules/@angular.

"cannot find module error"  is a different thing. Just wait other response.

**Comment by derek-fong** [comment]
@LelouchLight FYI Issue #328
