### ISSUE TITLE
0.6.0: MeteorComponent.autorun() not bound to zone when run from subscribe() callback

### ISSUE THREAD

**Issue by capi** [Urigo/angular2-meteor#337]
Previously to updating angular2-meteor to the latest published versions I tracked changes to server-side-state as follows:

    this.subscribe('order', this.orderId, () => {
            this.loading = false;
            this.order = Orders.findOne(this.orderId);
            if (this.order) {
                this.history.addAsMostRecent(this.order._id);
            } // if
        }, true)
    });

This worked fine, but now the `autorun()` callback won't run in the `NgZone` any more, causing change-detection to miss this. The following works, though:

    this.subscribe('order', this.orderId);
    this.autorun(() => {
        this.loading = false;
        this.order = Orders.findOne(this.orderId);
        if (this.order) {
            this.history.addAsMostRecent(this.order._id);
        } // if
    }, true);

Also it's possible to force the zone, then autorun works as well:

    this.subscribe('order', this.orderId, () => zone.run(() => {
        this.autorun(() => {
            this.loading = false;
            this.order = Orders.findOne(this.orderId);
            if (this.order) {
                this.history.addAsMostRecent(this.order._id);
            } // if
        }, true)
    }));

I think, that somewhere in `MeteorComponent.subscribe()` the binding to the current `NgZone` is lost, but I could not yet track down where.

Testing with the other commands in the callback of  `subscribe()` it seems that the callback is not executed in the `NgZone` at all (regardless if last parameter is boolean, true, or false). `autorun()` uses current zone on `true` or default, but since the current zone is not the `NgZone`, the connection to angular2 is lost.

**Comment by barbatus** [comment]
Yes, that was missed. Will be fixed in the next version.
BTW, autoBind is true by default from 0.6.0.

**Comment by capi** [comment]
Thanks a lot for the quick fix!
