### ISSUE TITLE
Error: Cannot find primary outlet to load 'HomePage'

### ISSUE THREAD

**Issue by dpdonohue** [Urigo/angular2-meteor#340]
I have been trying to get my first Angular2-Meteor app working for the past week.  
Everything I try fails.  The problems relate to importing pages.  I cannot get the app to load any of my HTML templates from other files.  And routing also fails.

When I run my app I get this error in the browser console
> browser_adapter.js:84 Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'HomePage'
>     at resolvePromise (zone.js:538)
>     at zone.js:515
>     at ZoneDelegate.invoke (zone.js:323)
>     at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.js:53)
>     at ZoneDelegate.invoke (zone.js:322)
>     at Zone.run (zone.js:216)
>     at zone.js:571
>     at ZoneDelegate.invokeTask (zone.js:356)
>     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:44)
>     at ZoneDelegate.invokeTask (zone.js:355)

I am running Meteor 1.3.4.4

Here is my app.web.ts file:
````
import 'reflect-metadata';
import 'angular2-meteor-polyfills';
import { Component, provide } from '@angular/core';
// import { bootstrap } from '@angular/platform-browser-dynamic';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import { provideRouter, RouterConfig, ROUTER_DIRECTIVES } from '@angular/router';
import { APP_BASE_HREF } from '@angular/common';
import { HomePage } from './pages/home/home';
import { AboutPage } from './pages/about/about';

import template from './app.html';

@Component({
  selector: 'app',
  directives: [ROUTER_DIRECTIVES],
  // template
  template:`
  <nav>
  <ul>
    <li>
        <a href="">Home</a>
    </li>
    <li>
        <a href="about">About</a>
    </li>
  </ul>
</nav>
  `
})
class MyApp { }

const routes: RouterConfig = [
  { path: '',   component: HomePage },
  { path: 'about',	component: AboutPage },
];

const APP_ROUTER_PROVIDERS = [
  provideRouter(routes)
];

export function run(): void {
  bootstrap(MyApp, [APP_ROUTER_PROVIDERS, provide(APP_BASE_HREF, { useValue: '/' })]);
}
````

Here is my package.json
````
{
  "name": "testangularrouting",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/http": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "@angular/router": "^3.0.0-beta.2",
    "angular2-meteor": "^0.5.6",
    "angular2-meteor-auto-bootstrap": "^0.5.6",
    "angular2-meteor-polyfills": "^0.1.1",
    "ionic-angular": "^2.0.0-beta.10",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.6",
    "zone.js": "^0.6.12"
  }
}
````

Here is my .meteor/packages
````
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

barbatus:angular2-runtime
angular2-compilers
````

**Comment by derek-fong** [comment]
@dpdonohue Looks like you are missing the `<router-outlet></router-outlet>` in your HTML template. 

```
@Component({
  selector: 'app',
  directives: [ROUTER_DIRECTIVES],
  // template
  template:`
  <nav>
  <ul>
    <li>
        <a href="">Home</a>
    </li>
    <li>
        <a href="about">About</a>
    </li>
  </ul>
</nav>
<router-outlet></router-outlet>
  `
})
class MyApp { }
```

Without the  `<router-outlet></router-outlet>` your app does not know where to render your `HomePage`, `AboutPage`, etc components and that's why it this giving you this error message.

**Comment by dpdonohue** [comment]
Thanks @derek-fong I now added ```` <router-outlet></router-outlet> ```` and I get the same error.  (I had tried this previously and omitted it here).

Also note that I cannot import HTML files.  In my app.web.ts file, I have 
```` 
import template from './app.html'; 
````
On the command line I see this:
client/imports/app/app.web.ts (13, 22): Cannot find module './app.html'.

In fact the only way my application can find the HTML is if i embed it in the ```` @Component ```` declaration, as I have done above.  This also fails: ```` templateUrl: './app.html' ````

I think there is some fundamental problem loading templates and loading pages.  
It seems to break when I ```` import ```` using relative paths.  
Is this related to a known bug?  Such as the one @Urigo referenced here?
https://forums.meteor.com/t/problem-with-angular-templates/26280

**Comment by derek-fong** [comment]
@dpdonohue 
> I now added <router-outlet></router-outlet> and I get the same error. (I had tried this previously and omitted it here).

Just want to confirm - Does your project contain an [index.html](https://github.com/Urigo/angular2-meteor/blob/master/examples/todos-meteor-1.3/client/index.html) file to specify the root component of your app?
```
<body>
  <app></app>
</body>
```

---

> I cannot import HTML files. In my app.web.ts file, I have

> import template from './app.html'; 
> On the command line I see this:
> client/imports/app/app.web.ts (13, 22): Cannot find module './app.html'.

This issue has been reported in #328 (Please see Urigo's comments). Although it shows `Cannot find module './app.html'` when compiling, your code should still run. I guess we just have to wait until `typescript 2.0` becomes available and ignore these typescript warnings in the meantime. 

---

> In fact the only way my application can find the HTML is if i embed it in the @Component declaration, as I have done above. This also fails: templateUrl: './app.html'

Consider upgrading `angular2-meteor` to `0.6.0` and make sure your meteor packages `angular2-compilers` and `barbatus:angular2-runtime` are up-to-date. 

Once you have updated to version `0.6.0` then you can checkout [Static Resources](https://github.com/Urigo/angular2-meteor#static-resources) which shows the recommended way of handling templates and stylesheets.

**Comment by dpdonohue** [comment]
OK thanks to you @derek-fong I have found the mystery workaround to getting this to work.
I did upgrade angular2-meteor to 0.6.0 but I don't think that was the solution.

So in my file client/main.ts wants to load relative to the current client directory
````
import 'reflect-metadata';
import { Meteor } from 'meteor/meteor';
import { run as runWeb } from './imports/app/app.web';

if (Meteor.isCordova) {
  document.addEventListener('deviceready', () => {
    // ionicSelector('app');
    // runMobile();
    setClass('mobile');
  });
} else {
  runWeb();
  setClass('web');
}

function setClass(css): void {
  if (!document.body.className) {
    document.body.className = "";
  }
  document.body.className += " " + css;
}
````

However in my file client/imports/app/app.web.ts, it wants to 
* import **HTML templates** relative to the current directory
* import **pages** relative to some other, far-off directory (wild speculation: node_modules/angular2-meteor?)

````
import 'reflect-metadata';
import 'angular2-meteor-polyfills';
import { Component, provide } from '@angular/core';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import { provideRouter, RouterConfig, ROUTER_DIRECTIVES } from '@angular/router';
import { APP_BASE_HREF } from '@angular/common';
import { HomePage } from '../../imports/app/pages/home/home';
import { AboutPage } from '../../imports/app/pages/about/about';

import template from './app.html';

@Component({
  selector: 'app',
  directives: [ROUTER_DIRECTIVES],
  template:`
  <nav>
  <ul>
    <li>
        <a href="">Home</a>
    </li>
    <li>
        <a href="about">About</a>
    </li>
  </ul>
</nav>
<router-outlet></router-outlet>
  `

})
class MyApp { }

const routes: RouterConfig = [
  { path: '',   component: HomePage },
  { path: 'about',	component: AboutPage },
];

const APP_ROUTER_PROVIDERS = [
  provideRouter(routes)
];

export function run(): void {
  bootstrap(MyApp, [APP_ROUTER_PROVIDERS, provide(APP_BASE_HREF, { useValue: '/' })]);
}
````

So for now I am back in business, thanks!  I can actually (after a week of effort) load pages in Meteor/Angular 2.  Crossing my fingers for no more gotchas!

Should the documentation/tutorials be updated?  Or is there some way to make this Angular2 importing behave more intuitively/consistently?

**Comment by barbatus** [comment]
@dpdonohue it's not related to Angular2 itself but rather to Node modules resolution style which is preset in the tsconfig by default "moduleResolution": "node".

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781409/7546a078-b7bd-11e6-9e4e-261c9560dc20.png)
