### ISSUE TITLE
hot reloading for angular 2 with meteor

### ISSUE THREAD

**Issue by daynisy** [Urigo/angular2-meteor#342]
Hi all,
I know the hot reload for React with meteor is implemented. But how about Angular2 ? Do we have a  similar one for that? Currently the Angular2 tutorial app refreshes the whole page which gives a long refresh time.

**Comment by Urigo** [comment]
would love some help with that.
Could you link to the implementation of React and Meteor?

**Comment by daynisy** [comment]
Hi Urigo,
Here is the github for the meteor react implementation.
https://github.com/gadicc/meteor-hmr

I don't deeply dive into the code of that library, but from the gif picture, it seems the implementation is ready.

**Comment by paralin** [comment]
This was the idea behind using webpack:webpack. Can we perhaps rally behind getting that working? Or is that not the right solution, do you think?

**Comment by daynisy** [comment]
Hi paralin,
I think just use the 'native meteor way'(i.e. like the gadicc:ecmascript-hot library) is a good approach to go. Web application developers just like me don't want to deal with the poor-documented and complicated webpack, that's way I choose meteor which is simple to add third-party library and package using Atmosphere package.

**Comment by paralin** [comment]
@daynisy That's exactly what `webpack:webpack` is

**Comment by daynisy** [comment]
hi paralin, 
maybe it is better for you to read 
this(https://forums.meteor.com/t/what-is-hot-reloading-and-code-splitting-webpack-webpack-vs-ecmascript-hot/19734/3)
to get better understanding about the difference between webpack:webpack and gadicc:ecmascript-hot.

**Comment by paralin** [comment]
Thanks, I will read through that. Definitely interested in something
similar for angular. The reload times are just painful right now :)

**Comment by barbatus** [comment]
There is a good project on that https://github.com/mgechev/angular2-hot-loader. We just need to create own server API (probably use some ideas from gadicc:ecmascript-hot). It's gonna take some time though.

**Comment by dotansimha** [comment]
This issue was moved to Urigo/angular-meteor#1474
