### ISSUE TITLE
canActivate() Guard with Meteor.user()

### ISSUE THREAD

**Issue by derek-fong** [Urigo/angular2-meteor#343]
Not sure if this is `angular2-meteor` related but I am just trying my luck here...

What I am trying to do is to implement a `CanActivate` guard for a route which basically: 
a. Activate a route if user is logged in or
b. Redirect user to `login` page if user is not logged in

The idea should be pretty simple - Here is my `auth.guard.ts`:

```
import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';

@Injectable()
export class AuthGuard implements CanActivate {
  constructor(private router: Router) {}

  canActivate(): boolean {
    let canActivate: boolean = (Meteor.user()) ? true : false;

    if (!canActivate) {
      this.router.navigate(['/login']);
    }
    return canActivate;
  }
}
```

And of course my `app.routes.ts` would be something like this: 

```
import { provideRouter, RouterConfig } from '@angular/router';

import { LoginComponent } from '../auth/login.component';
import { FooComponent } from '../foo/foo.component';

export const routes: RouterConfig = [
  { path: '', redirectTo: '/foo', pathMatch: 'full' },
  { path: 'foo', component: FooComponent, canActivate: [AuthGuard] }
  { path: 'login', component: LoginComponent },
];

export const APP_ROUTER_PROVIDERS: any = [
  AuthGuard,
  provideRouter(routes)
];
```

However, whenever I try to access the url `http://bar.com/foo` it always redirects to the login page `http://bar.com/login` even I was logged in. 

Did some troubleshooting and noticed `Meteor.user() = undefined` and therefore `canActivate` returns false and redirects to the login page, which I suspect the `canActivate()` function returns before `Meteor.user()` has a value assigned. 

In angular 1 I used to handle this with promises but I am just not sure how to handle this in Angular 2?

**Comment by dotansimha** [comment]
Hi @derek-fong ,
Please try to use https://github.com/Urigo/angular2-meteor-accounts-ui package, it exposes `AuthGuard` which can provide you the same functionality. 

Also, another possible solution, I think that you can return a Promise in your `canActivate`, and then you can wait for Meteor to load and then check if there is a user connected (using Autorun), and the to resolve the promise. 

Please re-open if you still have issues.

**Comment by mragwa** [comment]
I have the same problem
I checked meteor accounts ui example you are using routing like   
`{ path: 'guarded', component: GuardedComponent, canActivate: [AuthGuard],}`
what if i need to redirect user to the login page?. 
 @dotansimha  if you can post a snippet it will be appreciated. 
thank you

**Comment by styssi** [comment]
Try changing your AuthGuard in the following way. Using Meteor.user() is not the perfect solution here, because it takes to long to load. Instead you can use Meteor.userId(), which should be here right from the beginning. It is working for me, and I hope this is working for you too.

`
let canActivate: boolean = (Meteor.userId()) ? true : false;
`

**Comment by mragwa** [comment]
thanks @styssi  for your post but the problem here is that i need to check user permissions if he allowed to access this route or not, with just Meteor.userId() you can't did it.

**Comment by at-nhuibo** [comment]
I also have same issue, don't know how to check `Meteor.user()` correctly in `canActivate`.
Any Guru, please help, many thanks. :)

**Comment by MartiniHenry1988** [comment]
@mragwa Did you find the solution for checking user permissions in canActivate()? i also need to access the user object instead of only Meteor.userId()

**Comment by mragwa** [comment]
for sorry NO, and still on my list but i take a step forward on my application and i will back to it, or some one get a solution :D

**Comment by c0desolut1ons** [comment]
Hi,
Meteor.user() sometime is undefined ... in our case we use next snippet code in component ngOnInit (attention! no in canActivate) method:

```
Tracker.autorun(() => {
      let user = Meteor.user();
      
      // vendors permission
      if (!PermissionUtil.doesUserHavePermission(user, 'vendors')) {
        this.zone.run(() => this.router.navigate(['/']));
      }

    });
```
