### ISSUE TITLE
Angular 2 styles compiler for Meteor not importing

### ISSUE THREAD

**Issue by MichaelSolati** [Urigo/angular2-meteor#344]
Earlier today/last night I was trying to import a SASS file `import style from './app.sass'` into a component of mine (my root component).
```javascript
@Component({
  selector: 'ion-app',
  styles:['style'],
  template,
  providers: [
    Language,
    PostsService
  ],
  directives: [
    ROUTER_DIRECTIVES
  ]
})
```

Well, keeping things simple, my SASS style isn't being imported at all. I can console log `style` in my constructor, and all of my SASS styling in the console, but no style...

I actually downloaded this repo and tested the todos-meteor-1.3. I removed all of the style for the body background in the `./client/main.css` and added to the `./imports/components/task.less`....
```
body {
 background:red;
}
```

But the background stays white....

Any thought's on this would be awesome. (Also this seems to work only for `import styleUrl from './foo.css!url';` not importing url for SASS or LESS.)

**Comment by kfarst** [comment]
Have you looked into `ViewEncapsulation`?

**Comment by MichaelSolati** [comment]
@kfarst `ViewEncapsulation` seems to have resolved most of my issue.... (There is still some weirdness in importing Ionic2 with it.. 🤔) Also that would mean the Todo example app should be updated with `ViewEncapsulation`.

**Comment by kfarst** [comment]
@MichaelSolati not sure as I haven't worked with Ionic 2, but I think there might be some styling going on in this tutorial: https://github.com/ashteya/ionic2-tutorial-github

Otherwise you could look into serving up the styles as a static folder on the server, then importing them into your existing styles (possibly with https://expressjs.com/)
