### ISSUE TITLE
Error when import template

### ISSUE THREAD

**Issue by tna274** [Urigo/angular2-meteor#345]
When I try import my template in ts file by statements:
_import template from './app.html';_
In my IDE and terminal, an error message appear:
+ In IDE: error in 'template' text, full error: 'Default export is not declared in imported module'
+ In terminal (when run command 'meteor'): client/app.ts (11, 22): Cannot find module './app.html'.
But when I open meteor on browser, It's worked fine. 
With every template have similar problems.
What wrong here?

**Comment by kamilkisiela** [comment]
TypeScript 2.0 (soon out of beta) should fix it.

It would be possible to use wildcards:

```ts
declare module "*.html" {}
```

Could be any time.

**Comment by tna274** [comment]
thanks for answer, my error in IDE was fixed but terminal has added another error is:
client/app.ts (9, 22): Cannot find module './app.html'
Maybe, I'll wait TypeScript 2.0 :)

**Comment by temo44** [comment]
@kamilkisiela is there a reason why templateUrl is not working?

If I have app.html along with app.ts in the client folder then
```
templateUrl: 'client/app.html' //(./app.html also  doesn't work)
```
isn't working.

**Comment by kamilkisiela** [comment]
@temo44 `angular2-compilers` since `v0.6.0` supports only `template as a string` pattern.

Take a look at this https://github.com/Urigo/angular2-meteor#static-resources

So there's no `templateUrl`.

```ts
import template from './app.html';

// ...

// inside @Component or something
template: template
```

or 

```ts
import template from '/client/app/html';

template: template
```

**Comment by temo44** [comment]
Ah thanks for that!

The reason why I ask is because it isn't explained in the angular 2 meteor socially tutorial and I only worked with templateUrl's before the tutorial.
