### ISSUE TITLE
Cannot use Routing Permissions

### ISSUE THREAD

**Issue by tna274** [Urigo/angular2-meteor#346]
I had try to created Routing Permissions follow http://www.angular-meteor.com/tutorials/socially/angular2/user-accounts-authentication-and-permissions 
But some error was occurred:
+ Cant import 'ComponentInstruction': it's show cant _**cannot resolve symbol 'ComponentInstruction'**_
+ In function _**checkPermissions(instruction: ComponentInstruction)**_: when call function _**instruction.params['partyId'];**_ error in params was occurred _**unresolve variable params**_ 
+ Last, when call function **_@CanActivate(checkPermissions)_** this show error message: _**Invalid number of arguments, expect 0**_
Someone can help me

**Comment by Tallyb** [comment]
The problem is because of the new new new router. 
Check your package.json to make sure you are on the new router (3.0.0) and not on router-deprecated. Check that you are on angular2-meteor-accounts-ui 0.6.1.

**Comment by Tallyb** [comment]
Angular2-meteor-accounts-ui until version 0.5.0 works with deprecated router, and uses the requireUser annotation. 
The 0.6.x releases are for router v3 and implement authGuard.

**Comment by Urigo** [comment]
we've updated the tutorial.
Please try that and if you have a problem open another issue
