### ISSUE TITLE
`Cannot find name 'Zone'` when building project with Webpack and Typescript-loader

### ISSUE THREAD

**Issue by DAB0mB** [Urigo/angular2-meteor#348]
Hello,

I encounter the following error report whenever I try to build my project:

    ERROR in /my-project/node_modules/angular2-meteor/dist/patch.d.ts
    (4,19): error TS2304: Cannot find name 'Zone'.

    ERROR in /my-project/node_modules/angular2-meteor/dist/patch.d.ts
    (6,27): error TS2304: Cannot find name 'Zone'.

    ERROR in /my-project/node_modules/angular2-meteor/dist/patch.d.ts
    (7,23): error TS2304: Cannot find name 'Zone'.

    ERROR in /my-project/node_modules/angular2-meteor/dist/patch.d.ts
    (8,22): error TS2304: Cannot find name 'Zone'.

My project is written in `Typescript` and I build it using `Webpack`.

Here are the configuration files I use for my project:

**tsconfig.json**
```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "files": [
    "app/app.ts",
    "typings/index.d.ts"
  ],
  "exclude": [
    "www",
    "node_modules"
  ]
}
```

**typings.json**
```js
{
 "dependencies": {
    "es6-promise": "registry:npm/es6-promise#3.0.0+20160211003958"
  },
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160602141504",
    "meteor": "registry:env/meteor#1.3.0+20160713172414",
    "meteor-publish-composite": "registry:dt/meteor-publish-composite#0.0.0+20160316171810"
  }
}
```

If I load `node_modules/zone.js/dist/zone.js.d.ts` definition manually in the `tsconfig.json` it seems to solve the issue, however I would expect it to be done automatically and not load it whenever I use `angular2-meteor`.

**Comment by barbatus** [comment]
You need `"zone.js": "npm:zone.js"` in the `typings.json`.
There is `typings.json` in this repo, don't the reason why not to look into.
