### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'XXX' after updating angular2-compilers

### ISSUE THREAD

**Issue by onhate** [Urigo/angular2-meteor#350]
Hello,

After updating my meteor packages with _meteor update_ the application is no more loading due to a exception:

`EXCEPTION: Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'XXX'`

I have no clue on where to start the investigation, can you help me?

**meteor packages before update**
```
angular2-compilers@0.5.7
angular2-html-templates@0.5.3
barbatus:typescript@0.3.1
barbatus:typescript-compiler@0.5.12
```

**meteor packages after update**
```
angular2-compilers@0.6.0
barbatus:css-compiler@0.3.0
barbatus:scss-compiler@3.8.1_1
barbatus:typescript@0.3.4_1
barbatus:typescript-compiler@0.6.11
urigo:static-html-compiler@0.1.7
```

**npm angular2 packages**
```
@angular/common: ^2.0.0-rc.4,
@angular/compiler: ^2.0.0-rc.4,
@angular/core: ^2.0.0-rc.4,
@angular/http: ^2.0.0-rc.4,
@angular/platform-browser: ^2.0.0-rc.4,
@angular/platform-browser-dynamic: ^2.0.0-rc.4,
@angular/router: ^3.0.0-beta.2,
angular2-meteor: ^0.6.2,
angular2-meteor-polyfills: ^0.1.1,
es6-shim: 0.35.1,
meteor-node-stubs: ^0.2.3,
reflect-metadata: ^0.1.3,
rxjs: 5.0.0-beta.6,
systemjs: ^0.19.26,
zone.js: ^0.6.12
```

**Comment by derek-fong** [comment]
Have you tried importing your HTML templates with [this method](https://github.com/Urigo/angular2-meteor#static-resources) after upgrading from `angular2-compilers@0.5.7` to `angular2-compilers@0.6.0`?

**Comment by onhate** [comment]
The <router-outlet> that the exception is describing as missing is inside a angular2 template.

app/client/app.ts
```
@Component({
    selector: 'main-app',
    templateUrl: 'client/app.html'
})
export class MainApp extends MeteorComponent {
...
}
```

app/client/app.html
```
<div>
...
</div>
<router-outlet></router-outlet>
```

**Comment by derek-fong** [comment]
@onhate According to the link that I have posted in previous comment

Provided that your `main.html` and `main.ts` are in the same folder:  

```
import template from './main.html';

@Component({
  selector: 'main-app',
  template: template
})
export class MainApp extends MeteroComponent {}
```

I encourage you to have a read on [this](https://github.com/Urigo/meteor-static-templates) in case you have missed out.

**Comment by onhate** [comment]
Got it @derek-fong, thanks!

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
