### ISSUE TITLE
Cannot find module './app.html'.

### ISSUE THREAD

**Issue by cltnschlosser** [Urigo/angular2-meteor#351]
Following along exactly with http://www.angular-meteor.com/tutorials/socially/angular2/, but I get warnings for my html files, saying they cannot be found. Everything still works fine, but the warnings are annoying. Is there something simple I did wrong?

**Comment by derek-fong** [comment]
@cltnschlosser Please see comments from #328 - This is a known issue and hopefully will be fixed once `TypeScript 2.x` is released.
