### ISSUE TITLE
angular2-compilers: TypeScript warnings about missing module

### ISSUE THREAD

**Issue by kamilkisiela** [Urigo/angular2-meteor#352]
Same as here: Urigo/meteor-static-templates#9

**Comment by kamilkisiela** [comment]
@barbatus We have the Urigo/meteor-static-templates#9 to keep track of that issue, but I thought it would be nice to keep an open issue here, in `angular2-meteor` repository to inform people that it is a known issue.

But you can close it if you don't agree with that.

**Comment by barbatus** [comment]
barbatus:typescript@0.4.0 is based on TypeScript@2.0.0.
One will also need to add definitions as follows: 
```
typings install github:meteor-typings/angular2-compilers#c2ca3d3036b08f04a22b98ed16ff17377499e1e7 --global
```
