### ISSUE TITLE
Collection type

### ISSUE THREAD

**Issue by maranqz** [Urigo/angular2-meteor#353]
Hello. 
I have collection A.
```
export let A = new Mongo.Collection<AType>('images');
export class AType{
  //somithing variables
  constructor(){}
}
```
I'm trying to get a record.
```
{
  ...
  a: AType;
  ....
  this.a = A.findOne(id);
  ...
}
```
But i'm getting Object. Not AType.
What am I doing wrong?

It isn't working.
```
this.a = <AType>A.findOne(id);
```

Thank you in advance.

**Comment by barbatus** [comment]
You need to return a new class instance in the `transform` method.
See available options here https://docs.meteor.com/api/collections.html#Mongo-Collection-findOne
