### ISSUE TITLE
No console output for angular2 errors?

### ISSUE THREAD

**Issue by janus-reith** [Urigo/angular2-meteor#355]
This is one of the many times that I made simple changes to my app and broke it.
It now gets stuck on the first index page:
```
<head>
    <base href="/">
</head>
<body>
  <app>Lädt...</app>
</body>
```

As there are no errors in the console output, I don't know where to get started when debugging this.
The code of the next component that should be loaded, app.component.ts, seems to be fine aswell.

**Comment by derek-fong** [comment]
@janus-reith can you please show us your code?
