### ISSUE TITLE
Imported templates are minified in development

### ISSUE THREAD

**Issue by Richie765** [Urigo/angular2-meteor#359]
When using the import method to import templates (in development):
```javascript
import template from  './foo.html';
console.log(template);
```

The template seems to be minified, making it hard to find errors in it:
```javascript
EXCEPTION: Error in ./FooPage class FooPage - inline template:0:1026
```

Could the template be imported as-is in development so errors contain useful line numbers?

**Comment by barbatus** [comment]
no they are not minified

**Comment by barbatus** [comment]
@kamilkisiela [JSON.stringify](https://github.com/Urigo/meteor-static-html-compiler/blob/master/src/utils.ts#L15) seems to be removing new lines. Can we get rid of it?
