### ISSUE TITLE
Server side breakpoint is not hitting while debugging typescript

### ISSUE THREAD

**Issue by pankyka** [Urigo/angular2-meteor#36]
Hi,

I tried with Webstorm 10-11, but breakpoints are not hitting in server side code. In .tsconfig file I set "sourceMap": true but still doesn't work. Is there any setting/config/workaround to get it to work?

**Comment by vangorra** [comment]
I can also confirm this is not working in Webstorm EAP nor the browser. Any ideas would be appreciated.

**Comment by barbatus** [comment]
@vangorra Am I right that the issue is about server side code only? Does debugging of the client side's typescript work for you?

**Comment by vangorra** [comment]
This issue has been driving me nuts so I setup basic projects in typescript, coffee script, es6 and js. Each of them fail to debug in a predictable manner. At this point I'm thinking the issue is with webstorm. Here is the bug I submitted with jetbrains for reference:
https://youtrack.jetbrains.com/issue/WEB-19334

**Comment by pankyka** [comment]
@vangorra Debugging server side code with latest Webstorm working for me when I use es6. You might need to set true "js.debugger.v8.use.any.breakpoint" in Ws registry (if already disabled). 
@barbatus Debugging ts source on client side working fine for me.

**Comment by vangorra** [comment]
@pankyka I have tried "js.debugger.v8.use.any.breakpoint" as enabled and disabled for es6 projects and ts projects, it doesn't seem to make any difference. 

@pankyka @barbatus Are you both able to debug server and client code? What OS are you using? The office issued me a Win10 machine a few weeks and I'm looking for any excuse to run Ubuntu.

**Comment by barbatus** [comment]
@vangorra Client side debugging works find for me (in a browser), but there might be an issue with the server side. I plan to look into it soon.

**Comment by barbatus** [comment]
just tried debugging for the server side, it works as expected in the last version.
