### ISSUE TITLE
Load javascript on router activation

### ISSUE THREAD

**Issue by andresespinosapc** [Urigo/angular2-meteor#366]
Just as the title says, I don't want to load the javascript of my whole application at once, but load separate javascript files for each router. Is there a function that executes after router activation? I also need that the javascript is imported after anything else, as usual (in particular because it relies in jQuery that is loaded as a meteor package).

**Comment by barbatus** [comment]
It's not implemented yet. It's likely be part of https://github.com/Urigo/angular2-meteor/issues/280
