### ISSUE TITLE
Unable to resolve some modules on Step 0

### ISSUE THREAD

**Issue by theasimzaidi** [Urigo/angular2-meteor#368]
Following Step 0.

But this line of code doesn't work, it tells me to download the github folder, so I did that. Then inside the folder I run meteor npm install which also worked. Then when I try running meteor, I get this issue. And it keeps looping in my command line as well infinitely so the app is never able to run. Even tried doing this in C9.io, Nitrous, and my Windows, but unable to get it running, pretty frustrating. I'm on my Macbook Air right now. 

Here's the actual error I get in my CL and they just keep repeating until i exit it. I even did meteor update but still had just about the same error and meteor npm install --save @angular  wasn't working, got a lot of different errors from that.

[[[[[ ~/socially ]]]]]                                                          

=> Started proxy.                             
=> Meteor 1.4.0.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
client/imports/parties/parties-list.component.ts (4, 27): Cannot find module '../../../both/collections/parties.collection'.
client/imports/parties/parties-list.component.ts (5, 38): Cannot find module './parties-form.component'.
client/imports/parties/parties-list.component.ts (7, 22): Cannot find module './parties-list.component.html'.
client/imports/parties-form/parties-form.component.ts (2, 78): Cannot find module '@angular/forms'.
client/imports/parties-form/parties-form.component.ts (4, 25): Cannot find module '../../../both/collections/parties.collection'.
client/imports/parties-form/parties-form.component.ts (6, 22): Cannot find module './parties-form.component.html'.
client/app.component.ts (4, 27): Cannot find module '../both/collections/parties.collection'.
client/app.component.ts (5, 38): Cannot find module './imports/parties/parties-form.component'.
client/app.component.ts (7, 22): Cannot find module './app.component.html'.
                                              
Unable to resolve some modules:

  "../both/collections/parties.collection" in 
/Users/Asim/socially/client/app.component.ts (web.browser)
  "./imports/parties/parties-form.component" in
/Users/Asim/socially/client/app.component.ts (web.browser)
                                              
server/main.ts (2, 54): Cannot find module '@angular/forms'.
server/main.ts (4, 30): Cannot find module './app.component'.
                                              
Unable to resolve some modules:

  "@angular/forms" in /Users/Asim/socially/server/main.ts (os.osx.x86_64)
  "./app.component" in /Users/Asim/socially/server/main.ts (os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save @angular          
                                              
W20160806-15:01:46.316(-5)? (STDERR)          
W20160806-15:01:46.466(-5)? (STDERR) /Users/Asim/.meteor/packages/meteor-tool/.1.3.5_1.1houqv2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160806-15:01:46.483(-5)? (STDERR)            				throw(ex);
W20160806-15:01:46.483(-5)? (STDERR)            				      ^
W20160806-15:01:46.486(-5)? (STDERR) reflect-metadata shim is required when using class decorators
=> Exited with code: 8                        
client/imports/parties/parties-list.component.ts (4, 27): Cannot find module '../../../both/collections/parties.collection'.
client/imports/parties/parties-list.component.ts (5, 38): Cannot find module './parties-form.component'.
client/imports/parties/parties-list.component.ts (7, 22): Cannot find module './parties-list.component.html'.
client/imports/parties-form/parties-form.component.ts (2, 78): Cannot find module '@angular/forms'.
client/imports/parties-form/parties-form.component.ts (4, 25): Cannot find module '../../../both/collections/parties.collection'.
client/imports/parties-form/parties-form.component.ts (6, 22): Cannot find module './parties-form.component.html'.
client/app.component.ts (4, 27): Cannot find module '../both/collections/parties.collection'.
client/app.component.ts (5, 38): Cannot find module './imports/parties/parties-form.component'.
client/app.component.ts (7, 22): Cannot find module './app.component.html'.
                                              
Unable to resolve some modules:

  "../both/collections/parties.collection" in 
/Users/Asim/socially/client/app.component.ts (web.browser)
  "./imports/parties/parties-form.component" in
/Users/Asim/socially/client/app.component.ts (web.browser)
                                              
server/main.ts (2, 54): Cannot find module '@angular/forms'.
server/main.ts (4, 30): Cannot find module './app.component'.
                                              
Unable to resolve some modules:

  "@angular/forms" in /Users/Asim/socially/server/main.ts (os.osx.x86_64)
  "./app.component" in /Users/Asim/socially/server/main.ts (os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save @angular          
                                              
W20160806-15:02:10.224(-5)? (STDERR)          
W20160806-15:02:10.225(-5)? (STDERR) /Users/Asim/.meteor/packages/meteor-tool/.1.3.5_1.1houqv2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160806-15:02:10.227(-5)? (STDERR)            				throw(ex);
W20160806-15:02:10.227(-5)? (STDERR)            				      ^
W20160806-15:02:10.228(-5)? (STDERR) reflect-metadata shim is required when using class decorators

**Comment by Tallyb** [comment]
Did you run npm install and typings install?

**Comment by Urigo** [comment]
@theasimzaidi closing as it seems to be the issue but it it's not please open another

**Comment by kenp77** [comment]
I'm having the same problem !
At step 3 of the tutorial i have this error : ' Cannot find module ../../both/coll ections/parties.collection'. Note that typings and typings-core are both installed and i can see them under the node_modules.
So what is causing this error ? Now i 'm litte bit discouraged about using Angluar 2 meteor cause i'm having lot of errors from step 0 and i need to fix them one by one ! Why just don't give us a working app in the official web site ?
