### ISSUE TITLE
Cant import Scss files from npm module 

### ISSUE THREAD

**Issue by rajjejosefsson** [Urigo/angular2-meteor#373]
Why can't I import the login-buttons.scss

main.scss inside client
`@import "{}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss";`
Errors prevented startup:

```
While processing files with angular2-compilers (for target web.browser):
/client/main.scss: Scss compiler error: File to import: {}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss not found in file: /Users/Rasmusjosefsson/Desktop/ng-meteor/socially/{}/client/main.scss

Your application has errors. Waiting for file change.
```

**Comment by aessig** [comment]
I have the same problem. Any idea how to solve this ?

**Comment by neeraj1928** [comment]
Same issue. I am new to meteor and scss. How you solved it

**Comment by tafelito** [comment]
In case you are having the same issue, I solved adding version 0.8.0 of the angular2-meteor-accounts-ui module

**Comment by zaverichintan** [comment]
@tafelito It does not work by doing so, Kindly update on the entire process.

**Comment by tafelito** [comment]
@zaverichintan you can actually use version 1.0.0 now, and you don't have to import login-buttons.scss anymore. Just remove the import and it should work. See https://github.com/Urigo/meteor-angular2.0-socially/issues/141 for more info
