### ISSUE TITLE
Error installing Angular2 moment

### ISSUE THREAD

**Issue by theasimzaidi** [Urigo/angular2-meteor#375]
Angular 2 Whatsapp tutorial was running great until i had to run this on my Mac:

npm install angular2-moment --save

Here's the error I got, let me know if you know what's wrong and thank you!

whatsapp@ /Users/Asim/Desktop/whatsapp
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.4
└── angular2-moment@1.0.0-beta.1 

npm WARN angular2-moment@1.0.0-beta.1 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed.
npm WARN whatsapp@ No repository field.
npm WARN whatsapp@ No license field.

**Comment by theasimzaidi** [comment]
Also, when i open up the localhost, nothing loads and when i inspect the page I find this error:

Uncaught TypeError: core_1.NgModule is not a function

**Comment by Tallyb** [comment]
Angular versions were moving fast, and it is an RC 4, RC 5 problem.
You should force your angular to rc4, until the tutorial is updated. 
[you might need to downgrade also your angular2-meteor package, but I am not sure what version]. 

It will probably take a while until the tutorial will settle on a version, together with Angular. 

As of now, I can offer you the changes I made the alignment with RC5, but it is far from being final, so you can just use it as a reference. 
https://github.com/Tallyb/meteor-angular2.0-socially/tree/rc5
(note - this is on the rc5 branch, and not on master).

**Comment by derek-fong** [comment]
@theasimzaidi 

Like @Tallyb said this is most likely be one of those `angular2 RC 5` compatibility issues with `angular2-meteor`. 

Meanwhile could you please try this in your `package.json`

```
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "angular2-meteor": "0.6.3-beta.4",
    "angular2-meteor-auto-bootstrap": "0.6.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-moment": "^0.8.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
```

**Comment by ChameleonGeek** [comment]
Try using angular2-moment@0.8.2 it works for me

**Comment by barbatus** [comment]
Please version advised for rc4, as mentioned above.
Hopefully we'll upgrade to rc6 soon.
