### ISSUE TITLE
Wait on User subscription

### ISSUE THREAD

**Issue by simonhull** [Urigo/angular2-meteor#377]
I'm running into issues when loading data from the user accounts collection.  The information hasn't fully loaded when the component renders throwing errors.  Is there an equivalent WaitOn or this.data.ready function for Angular2-Meteor?

**Comment by barbatus** [comment]
It's not clear what do you want to get.
Meteor's methods (publish and call) take callbacks which run when data is available on the client.
Please elaborate (better with a demo if you want a quicker reply)

**Comment by sdarnell** [comment]
Not sure is the situation is exactly the same as mine, but we encountered the situation where Meteor.userId is setup immediately on login, but the user object for that record didn't appear in the user's collection until shortly afterwards. That is, Meteor.userId() was valid, but Meteor.user() was null. This naturally confuses code that expects both to be setup.

This behaviour appears to be standard meteor, and various routers tackle it (and availability of other collections) in a number of different ways.

For angular2 I suggest you look at route guards (CanActivate and Resolve): 

- https://angular.io/docs/ts/latest/guide/router.html#!#can-activate-guard
- https://angular.io/docs/ts/latest/guide/router.html#!#resolve-guard

Both support returning Observables or Promises which allow the routing action to be delayed.

With meteor you can wait on in a few different ways, such as Tracker.autorun() and convert that into an Observable or Promise.

HTH
