### ISSUE TITLE
Can I use this Angular2-meteor package in NativeScript + Angular2 + Meteor?

### ISSUE THREAD

**Issue by netwiser** [Urigo/angular2-meteor#379]
There is a npm module calls nativescript-ng2-meteor to integrate NativeScript + Angular2 + Meteor, but the change detection is not working properly. Since angular2-meteor package is pretty mature, I am wonder whether it is possible to port it to support with NativeScript as well?

**Comment by PseudoPsycho** [comment]
NativeScript already has built-in support for Angular 2 and I don't see how it would interfere with Meteor. So yes, you should be able to use angular2-meteor even without any modifications.
Keep in mind though that this solution does have a couple limitations:
- The Angular 2 renderer does not support self-closing tags like <Button />. You'll have to write <Button></Button>
- The newest version of Angular 2 is not compatible with Meteor. Make sure you use RC 5.

**Comment by barbatus** [comment]
@PseudoPsycho thanks for the tips
