### ISSUE TITLE
Weird problems when I subscribe twice to the same collection on the same page

### ISSUE THREAD

**Issue by pgrm** [Urigo/angular2-meteor#38]
Following application structure:

I have a menu on the left with a list of items which are links. This is filled by a component via

````
this.subscribe('subscription', () => this.items = Items.find(), true);
````

and in the view is a normal `*ng-for` loop.

Additionally, I have on one route another component which shows the exact same list of items, just with more details. Subscription is done the same way and loop as well.

Here are all the two errors I've noticed so far:

1) `TypeError: Cannot read property 'renderFragment' of undefined at AppViewManager_._attachRenderView` 

Supposedly, the local variable in the ng-for loop of the side list is null. However, sometimes the first item would show, before the exception throws.

This problem shows up when I use 2 separate publications, one which publishes only the name and the other which publishes the whole object. Also it showed up when I didn't wait for the subscription in the callback, but right away assigned the value `this.items = Items.find()`

~~2) When I use the same publication for both components, than it seems to work fine in the beginning. Later on, when I add new items and switch to a different view (the list in the menu stays, but the list of all items with more details is gone) Meteor starts sending delete commands for those newly created items.~~

~~Example: I start with a list of items 1-5. On the overview page, I add items 6-10. So far so good. Now I go away from the overview page and meteor sends to the client the command to delete items 6-10, even though my side list is still subscribed to it. And when I switch back to the overview page, the items 6-10 are downloaded again and everything seems fine, until I leave the overview page.~~

I'm currently trying to reproduce it with the parties example, but maybe you already have any idea why:

1. the items in the cursor would be null sometimes (I do apply a transformation function, but that should work, as they are only null from time to time)

~~2) why Meteor commands the application to delete items, even though another subscription is still running? (maybe this isn't possible with meteor?)~~

**Comment by pgrm** [comment]
Ok, I've found the problem for the 2. problem - queries on the server aren't reactive, but the first problem still is bugging me a bit, any ideas?

**Comment by barbatus** [comment]
I can only guess that some property is still undefined when being rendered. Otherwise, a repo with the issue needed.

**Comment by barbatus** [comment]
@pgrm can you pls check with the latest version?

**Comment by juanpujol** [comment]
I have a similar problem. Tested with `v0.3.4`

This always works locally in Chrome and Safari, in Firefox sometimes. It rarely works on the server.
```javascript
export class RoomComponent {
    room: Room;

    constructor(public params: RouteParams) {
        let roomId = this.params.get('id');
        this.room = Rooms.findOne(roomId);
    }
}
```

This doesn't work neither locally or the server (won't update `this.room`):
```javascript
export class RoomComponent extends MeteorComponent {
    room: Room;

    constructor(public params: RouteParams) {
        super();
        let roomId = this.params.get('id');
        this.subscribe('room', roomId, () => {
            this.room = Rooms.findOne(roomId);
        }, true);
    }
}
```
Could it be the reactive problem with queries on the server?

Thank you.

**Comment by juanpujol** [comment]
I fixed my issue. I had someting worng on my pub files inside the server directory. 

Now `this.subscribe` works fine.

**Comment by pgrm** [comment]
@barbatus sry it took so long. The new version seems to work, I can't reproduce the issue anymore. Closing it for now.
