### ISSUE TITLE
@Injectable decorator not working

### ISSUE THREAD

**Issue by paistipoikka** [Urigo/angular2-meteor#380]
Hi,

I am creating an Angular2-Meteor project. I have set it up my to use Angular 2 RC5. Everything works nicely until I try to add a service using the @injectable() decorator. As soon as it's added I receive a meteor compile error:

> reflect-metadata shim is required when using class decorators

As soon as I remove the @injectable() decorator Meteor compiles everything and I can load my application.

I have the barbatus:angular2-polyfills package installed which I think is all that is needed to import the required zone.js and reflect-metadata package. Someone has suggested using imports at the top of the main.ts but that doesn't work.

The @NgModule and @component decorators are working without a problem. As I have yet to wire the service (that uses the @injectable decorator) up to my @ngmodule I think this indicates that the Meteor environment simply isn't handling the @injectable decorator as intended. Regardless of whether it is used or not.

Is this a known issues, a new issue or some kind of misconfiguration? Any advice or ideas on how to solve this issue would be much appreciated. 

JT

The meteor packages installed are:

```
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library
standard-minifier-css@1.2.0   # CSS minifier run for production mode
standard-minifier-js@1.2.0    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.5.8              # Enable ECMAScript2015+ syntax in app code

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
angular2-compilers
barbatus:angular2-runtime
practicalmeteor:mocha
xolvio:cleaner
hwillson:stub-collections
dispatch:mocha-phantomjs
shell-server
barbatus:angular2-polyfills
```
The npm packages from package.json installed are:

 ```
 "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "^0.3.0",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.1",
    "@angular2-material/button": "^2.0.0-alpha.7-4",
    "@angular2-material/card": "^2.0.0-alpha.7-4",
    "@angular2-material/checkbox": "^2.0.0-alpha.7-4",
    "@angular2-material/core": "^2.0.0-alpha.7-4",
    "@angular2-material/input": "^2.0.0-alpha.7-4",
    "@angular2-material/toolbar": "^2.0.0-alpha.7-4",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-auto-bootstrap": "^0.6.0",
    "angular2-meteor-polyfills": "^0.1.1",
    "angular2-meteor-tests-polyfills": "^0.0.2",
    "bcrypt": "^0.8.7",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "0.2.3",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "chai": "3.5.0",
    "chai-spies": "0.7.1",
    "codelyzer": "latest",
    "tslint": "latest",
    "typescript": "latest",
    "typings": "latest"
  }
```

**Comment by bergben** [comment]
I am not sure what it is, but I can tell you that it's not a known issue since it works fine in my project. 

You could try to remove and add barbatus:angular2-polyfills.

If that doesn't work then you can try to uninstall and reinstall reflect-metadata and import it in the file where you are actually using the decorator, not in the main.ts, using 
import 'reflect-metadata';

That would only be a workaround though...

**Comment by paistipoikka** [comment]
OK, I have solved the problem. 

I didn't have my services underneath underneath an "imports" directory. Once I refactored my directory structure and placed the service inside the imports directory it worked. uurrghh....
