### ISSUE TITLE
Upgaring to Angular2 RC6

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/angular2-meteor#381]
Just managed to run with Meteor 1.4.1 and RC5, now RC6 is out and it's broken again  :-)

With this npm package versions:

```
{
  "name": "sbs",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "^2.0.0-rc.6",
    "@angular/compiler": "^2.0.0-rc.6",
    "@angular/core": "^2.0.0-rc.6",
    "@angular/forms": "^0.3.0",
    "@angular/platform-browser": "^2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.6",
    "@angular/router": "^3.0.0-rc.1",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-polyfills": "^0.1.1",
    "bootstrap-sass": "^3.3.7",
    "bootswatch": "^3.3.7",
    "meteor-node-stubs": "^0.2.3",
    "ng2-bootstrap": "^1.0.24",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0-beta.11",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "tslint": "^3.14.0",
    "typescript": "^2.0.2"
  }
}
```

I get the following errors:

```
=> Started proxy.
=> Started MongoDB.
W20160901-19:11:44.711(2)? (STDERR) C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\packages\modules.js:27659
W20160901-19:11:44.797(2)? (STDERR) export function scheduleMicroTask(fn) {
W20160901-19:11:44.798(2)? (STDERR) ^^^^^^
W20160901-19:11:44.799(2)? (STDERR) 
W20160901-19:11:44.800(2)? (STDERR) SyntaxError: Unexpected reserved word
W20160901-19:11:44.800(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20160901-19:11:44.801(2)? (STDERR)     at C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\boot.js:287:30
W20160901-19:11:44.802(2)? (STDERR)     at Array.forEach (native)
W20160901-19:11:44.803(2)? (STDERR)     at Function._.each._.forEach (C:\Users\Stefan\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160901-19:11:44.803(2)? (STDERR)     at C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\boot.js:128:5
=> Exited with code: 1
W20160901-19:12:05.724(2)? (STDERR) C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\packages\modules.js:27659
W20160901-19:12:05.725(2)? (STDERR) export function scheduleMicroTask(fn) {
W20160901-19:12:05.725(2)? (STDERR) ^^^^^^
W20160901-19:12:05.726(2)? (STDERR) 
W20160901-19:12:05.727(2)? (STDERR) SyntaxError: Unexpected reserved word
W20160901-19:12:05.727(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20160901-19:12:05.728(2)? (STDERR)     at C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\boot.js:287:30
W20160901-19:12:05.729(2)? (STDERR)     at Array.forEach (native)
W20160901-19:12:05.729(2)? (STDERR)     at Function._.each._.forEach (C:\Users\Stefan\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160901-19:12:05.730(2)? (STDERR)     at C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\boot.js:128:5
=> Exited with code: 1
W20160901-19:12:21.412(2)? (STDERR) C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\packages\modules.js:27659
W20160901-19:12:21.413(2)? (STDERR) export function scheduleMicroTask(fn) {
W20160901-19:12:21.413(2)? (STDERR) ^^^^^^
W20160901-19:12:21.414(2)? (STDERR) 
W20160901-19:12:21.415(2)? (STDERR) SyntaxError: Unexpected reserved word
W20160901-19:12:21.415(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20160901-19:12:21.416(2)? (STDERR)     at C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\boot.js:287:30
W20160901-19:12:21.417(2)? (STDERR)     at Array.forEach (native)
W20160901-19:12:21.417(2)? (STDERR)     at Function._.each._.forEach (C:\Users\Stefan\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160901-19:12:21.418(2)? (STDERR)     at C:\_Workspaces\Webstorm\sbs\.meteor\local\build\programs\server\boot.js:128:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

THANKS for any help!

**Comment by bergben** [comment]
I am using meteor 1.4.1 with RC5 right now too, updating to RC6 works for me, like at least the meteor server starts up. I am getting some errors later on in the browser console about meteorInstall etc. though. 
This is my package.json, although I don't think the problem is there as rather - if at all in the packages - in the meteor packages...
```
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
>>"@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
>>"@angular/router": "^3.0.0-rc.2",**
    "@angular/upgrade": "2.0.0-rc.6",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-polyfills": "^0.1.1",
    "bcrypt": "^0.8.7",
    "bcryptjs": "^2.3.0",
    "client": "0.0.1",
    "es6-shim": "^0.35.1",
    "meteor-node-stubs": "~0.2.0",
    "ng2-meta": "^1.0.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.11",
    "tether": "^1.3.3",
    "zone.js": "^0.6.12"
  }```
Just chill a few days and let the angular2-meteor guys do their magic, RC6 has only been released yesterday after all :)

**Comment by stefanholzapfel** [comment]
You're right, the error messge sounds more like a meteor issue. Can you please post your atmosphere versions for comparison? Thx!

**Comment by bergben** [comment]
sure thing, here you go:
```
accounts-password              1.3.0  Password support for accounts
angular2-compilers             0.6.0* Angular 2 Templates, HTML and TypeScript compilers for Meteor
anti:fake                      0.4.1  Random text and data generator
barbatus:angular2-polyfills    0.5.0  Polyfills for Angular2
barbatus:angular2-runtime      0.5.0  Polyfills for Angular2
ecmascript                     0.5.8  Compiler plugin that supports ES2015+ in all .js files
es5-shim                       4.6.14  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome        4.5.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS,...
jquery                         1.11.9  Manipulate the DOM using CSS selectors
meteor-base                    1.0.4  Packages that every Meteor app needs
mobile-experience              1.0.4  Packages for a great mobile user experience
mongo                          1.1.12  Adaptor for using MongoDB and Minimongo over DDP
orgztion:meteor-global-tether  1.0.0  HupSpot Tether exposed on global Meteor 1.3
reactive-var                   1.0.10  Reactive variable
seba:minifiers-autoprefixer    1.0.1  Standard minifiers used with Meteor apps by default + css autoprefixer.
shell-server                   0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-js           1.2.0  Standard javascript minifiers used with Meteor apps by default.
tmeasday:publish-counts        0.7.3  Publish the count of a cursor, in real time
tracker                        1.1.0  Dependency tracker to allow reactive callbacks
twbs:bootstrap                 4.0.0-alpha2  The most popular front-end framework for developing responsive, mob...
```

**Comment by Tallyb** [comment]
I got the export error as well, and it made me think about it a little deeper. 
The recent changes in Angular, which really moved it from a framework to a platform and with meteor being a platform as well, the inevitable time of clash has arrived. 
The newly introduced functionality of angular, such as router based lazy loading and AoT compilation, and the fact that meteor has a different way of doing things on the client side, I do not see how you can use both framework without compromising one or the other. I can see why majority of people are using react, as those issues do not exist there (being just a view rendering layer). 
Time to rethink Angular and Meteor?

**Comment by stefanholzapfel** [comment]
I already feared something like this after all the smart guys started focusing on apollo. :) To be honest thats exactly what I need, only a proper datalayer for an angular app. Too bad it's not yet reactive ...

**Comment by bergben** [comment]
So right now AoT compilation and lazy loading may not be usable yet. But if that is due to Meteor, then how is React better regarding that? You can use Angular without lazy loading and AoT compilation for now and maybe some day it will be compatible with Meteor. 
The issues simply don't exist with React because React doesn't offer such features AFAIK. But you can perfectly fine use Angular just as a view rendering layer too, the other features are optional...

**Comment by Tallyb** [comment]
@bergben I did not mean to say react is better, just easier to integrate because it is not *not* a platform, but then again I might be wrong here.

**Comment by bergben** [comment]
@Tallyb I get your point. I think you are right about that, React is also supposed to be learnt way faster than Angular. React sure has its advantages as a light-weight easy to learn rendering tool.

**Comment by stefanholzapfel** [comment]
Hm, now I'm really stuck. Even if I go back to Meteor 1.4.0 and the same packages as bergben, I get the export error.

**Comment by bergben** [comment]
are you on RC5 @stefanholzapfel  ?

**Comment by stefanholzapfel** [comment]
Tried to go back from RC6 to RC5, but it doesn't work, still get the same error message..

**Comment by bergben** [comment]
That is weird. 
Are you 100% sure you are on RC5?
Make sure you got all like this:
"@angular/common": "2.0.0-rc.5",
and not
"@angular/common": "**^**2.0.0-rc.5", (note the ^)

Try to run npm prune / delete the node_modules/@angular directory

**Comment by stefanholzapfel** [comment]
Jep, I already deleted the node_modules directory and reinstalled via "meteor npm install".

So obviously the problem is not RC6 but some other dependency/version :)

**Comment by bergben** [comment]
Well... I am running RC5 with those packages:
``` 
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-polyfills": "^0.1.1",
    "bcrypt": "^0.8.7",
    "client": "0.0.1",
    "meteor-node-stubs": "~0.2.0",
    "ng2-meta": "^1.0.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.11",
    "tether": "^1.3.6",
    "zone.js": "^0.6.17"
  }
```
I am out of ideas what it could be, maybe one of the guys that is more into Meteor can help, sorry :(

**Comment by stefanholzapfel** [comment]
It indeed is weird.. 

I have now copied over the package.json and versions/packages/release files from an empty project which is working properly (with RC6), cleaned the .meteor/local and node_modules directory and I still get this error.

So obviously it's a problem with my own code. Interesting that tallyb got the same error....

Thanks for your support so far @bergben

**Comment by stefanholzapfel** [comment]
Ok I have now nailed the problem down to this line of code:

let itemCollection = new MongoObservable.Collection<Item>('item');

So the instantiation of a new MongoObservable causes the error.

**Comment by jpsantosbh** [comment]
I'm Stuck too.

As @bergben my server is starting, but the app is crashing at browser. With tons of meteor related "Uncaught TypeError: Cannot read property".

It like look likes meteor modules didn't get imported.

**Comment by derekkite** [comment]
I was getting the same error, 

export function scheduleMicroTask(fn) {
 ^^^^^^   
          
SyntaxError: Unexpected reserved word

When I remove MongoObservable the error goes away. That is as far as I got.

**Comment by barbatus** [comment]
Some updates:
RC6 NPM files are ES6 modules now (see first point [here] (https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes)); RC6 package.jsons rely now on UDM files.
We are upgrading to RC6 currently and are stuck at this issue https://github.com/angular/angular/issues/11309. So we decided (because of that and not) to move observables into a separate package, which we'll then recommend to use by default with Meteor.
Current package will persist though and will be updated as soon as the issue fixed.
After, Angular2 compiler (ngc) will likely be integrated into `angular2-compilers` package as soon as possible.

**Comment by cubitworx** [comment]
Finally Angular 2 has been released [here](http://angularjs.blogspot.co.za/2016/09/angular2-final.html) and [here](http://juristr.com/blog/2016/09/ng2-released/)

With this in mind do we have any idea about a timeline for updating angular2-meteor? I imagine we would start a new issue since the above comments are probably no longer relevant?

I know it is a bit soon but I only ask so that know if I should continue on the current files (RC4) or whether I should wait a few days for an update to be compatible with the release version.

Thanks for all the great work!

**Comment by barbatus** [comment]
There is only one issue that prevents upgrading: https://github.com/angular/angular/issues/11309.
It didn't get to the release for some reason.

**Comment by Kamshak** [comment]
@barbatus: ah too bad! Is there a fork or a hack to make this work right now?

**Comment by barbatus** [comment]
@Kamshak I am looking into one.

**Comment by donvadicastro** [comment]
Does anyone know some existing workaround for this problem?

```
export function scheduleMicroTask(fn) {
^^^
```

**Comment by F1ERRO** [comment]
I am having this problem as well.  No idea why

**Comment by Kamshak** [comment]
You can fix this by updating your zone.js

**Comment by donvadicastro** [comment]
I'm trying to use the latest zone version but still have this error :(

**Comment by Kamshak** [comment]
This works for me (well it compiles & runs):

package.json
```
{
  "name": "angular2-meteor-base",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs"
  },
  "devDependencies": {
    "chai": "3.5.0",
    "chai-spies": "0.7.1",
    "typescript": "^2.0.2"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "0.2.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "angular2-meteor": "git+ssh://git@github.com/Urigo/angular2-meteor.git",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "bootstrap": "^4.0.0-alpha.4",
    "es6-shim": "0.35.1",
    "express-cors": "0.0.3",
    "meteor-node-stubs": "0.2.3",
    "meteor-rxjs": "git+https://github.com/Urigo/meteor-rxjs.git",
    "reflect-metadata": "0.1.3",
    "rxjs": "^5.0.0-beta.12",
    "ui-router-ng2": "^1.0.0-beta.2",
    "zone.js": "^0.6.23"
  }
}
```
.meteor/packages
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
jquery@1.11.9                  # Helpful client-side library

es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.

angular2-compilers
standard-minifier-js@1.2.0    # JS minifier run for production mode
barbatus:angular2-polyfills

practicalmeteor:mocha
xolvio:cleaner
hwillson:stub-collections
dispatch:mocha-phantomjs
shell-server
check
```

**Comment by barbatus** [comment]
please try 0.7.0-beta.2, it should work with Angular2

**Comment by laser-me** [comment]
@barbatus "There is only one issue that prevents upgrading: angular/angular#11309."
Was this about upgrading to 2.0.0 or aot? Will AoT be supported in near future by angular-meteor?

**Comment by Urigo** [comment]
@laser-me this issue was related to the Component API and also has been avoided so there is no blockage on updating.
The current recommended way is to use the RxJS API - https://www.angular-meteor.com/meteor-rxjs
