### ISSUE TITLE
Inheriting MeteorComponent from MeteorDirective

### ISSUE THREAD

**Issue by cubitworx** [Urigo/angular2-meteor#382]
FEATURE REQUEST

From a structural point of view would it not make sense to have a MeteorDirective class that becomes the parent class for MeteorComponent. I feel that this would make logical sense since in Angular2 a Component is a Directive and all functionality that MeteorComponent currently has appears to be needed for a MeteorDirective class.

I am trying to create an Angular2 Structural Directive that requires autorun & as far as I know I cannot do this without the above or extending MeteorComponent to create my own MeteorDirective class but that would not be future-proof.

In fact I think it would be beneficial to actually remove the autorun method from MeteorComponent & implement it in a 'Meteor' class. This way anything that needs it could use it (services, directives, components, etc). You could inherit MeteorDirective & MeteorComponent from this class but then you run fowl of the problem of deep inheritance creating a fragile framework; so I would think keeping it as a separate class would serve angular2-meteor best.

I would think one then does something like this:
```
export class MyComponent extends MeteorComponent {
    test() {
        Meteor().autorun(() => {
            . . .
        });
    }
}
```

Since the Meteor functionality is global & doesn't actually need to be instantiated it doesn't even need to be a class and can just be a function that returns a Meteor object.

Everybody seems to be so focused on components that it's proving to be difficult getting going with the other powerful features of Angular2 - it seems to be mostly due to lack of documentation since it's still changing so quickly being an RC.

**Comment by barbatus** [comment]
MeteorComponent will be renamed into MeteorReactive in the next release.
MeteorComponent actually doesn't do much, but those things are anyways important especially for UI components: to destroy Meteor handlers on ngOnDestroy and to update UI on the callbacks (i.e. run ngZone).
Other structural elements like services don't need this stuff in most cases, so users are expected to use regular Meteor API in them. That's why one global API is too much.

**Comment by cubitworx** [comment]
@barbatus Thanks & good to know; however I would disagree that services don't need this sort of stuff. In my opinion services is exactly where this logic should appear. The biggest flaw I see with the angular2-meteor tutorial is that it teaches users to put server data queries directly into components which is exactly what Angular discourages in favour of separation of concerns.

My argument would be that ***all*** calls to the server should instead be in services so that you can share them with any component by just referencing them instead of copy & pasting server subscription code between components. Imagine suddenly you need another 1, 2 or 3 components that show a parties list in a slightly different way, then you have to duplicate your entire autorun method in the new component instead of just importing the partiesList service & reusing it.

I think putting things like Meteor.subscribe() calls into components is just asking for trouble. Yes, it is easier but is not good design practice according to Angular2's design methodology - at least this is my understanding & I am open to correction.

**Comment by derek-fong** [comment]
@cubitworx +1 agree server data queries should be done within services to encourage code re-use.
