### ISSUE TITLE
Can't install angular2-compilers@0.6.1 windows x64

### ISSUE THREAD

**Issue by mrwillis** [Urigo/angular2-meteor#383]
Hi everyone,

I'm just starting a fresh angular2-meteor project on a windows x64 machine. I'm following the instructions in the readme here:

https://github.com/Urigo/angular2-meteor

I'm trying to just install the package after running

meteor create [name]
npm install angular2-meteor --save

fix the dependencies with the above things...
then the problem:

meteor add angular2-compilers

which returns:

c:\Users\jwilso37\Documents\meteor-synapse>meteor add angular2-compilers                      
 => Errors while adding packages:                                                             
                                                                                              
While checking for angular2-compilers@0.6.1:                                                  
error: No compatible binary build found for this package. Contact the package author and      
ask them to publish it for your platform.  

Thanks for the help,

Julian

**Comment by derek-fong** [comment]
@mrwillis For now please try to run with `angular2-compilers@0.6.0`

`meteor add angular2-compilers@=0.6.0` (See #372)

**Comment by mrwillis** [comment]
Thanks a lot Derek.

**Comment by haroldjcastillo** [comment]
I have the same issue.

`=> Meteor server restarted
=> Errors prevented startup:

   While checking for angular2-compilers@0.6.1:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it
   for your platform.

=> Your application has errors. Waiting for file change.`

**Comment by derek-fong** [comment]
@haroldjcastillo try `meteor rebuild` ?

**Comment by haroldjcastillo** [comment]
C:\Users\xuser\Documents\project\projectx>meteor rebuild
=> Errors while rebuilding packages:

While checking for angular2-compilers@0.6.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.

I have the same issues, but I compile before this package.

**Comment by alekseys** [comment]
@haroldjcastillo You also need to run this for now:
`meteor add angular2-compilers@=0.6.0`

**Comment by barbatus** [comment]
angular2-compilers@0.6.2 should fix it

**Comment by jycouet** [comment]
Hi @barbatus, 

I have the same issue with @0.6.2

```
While checking for angular2-compilers@0.6.2:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.
```

**Comment by barbatus** [comment]
@jycouet now it's a dup of https://github.com/Urigo/angular2-meteor/issues/410

**Comment by VishnuvY007** [comment]
Hi Team,

I am beginner for this tutorial and when i was set up, i found same error 

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While checking for angular2-compilers@0.6.1:
   error: No compatible binary build found for this package. Contact the
   package author and ask them to publish it for your platform.

=> Your application has errors. Waiting for file change.

Please help, if any body have any idea.

**Comment by jycouet** [comment]
This issue is close now.
Just run: 

> meteor remove angular2-compilers

then
> meteor add angular2-compilers

Like this you will get the new working version.
