### ISSUE TITLE
angular2-compiler error "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by vtulin** [Urigo/angular2-meteor#386]
I run my project on one computer without errors, on another cloned from bitbucket I have the following weird error!

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:
   
   While processing files with angular2-compilers (for target
   web.browser):
   native: Maximum call stack size exceeded
   at RegExp.exec (native)
   at win32StatPath (path.js:89:32)
   at Object.win32.normalize (path.js:185:18)
   at Object.win32.join (path.js:246:16)
   at Object.pathJoin
   (C:\Users\vtulin\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:88:22)
   at Isopack._getServePath (C:\tools\isobuild\isopack.js:1938:13)
   at InputFile.getDisplayPath
   (C:\tools\isobuild\compiler-plugin.js:396:63)
   at SassCompilerExtended.compileOneFile
   (packages/barbatus:scss-compiler/plugin/compile-scss.js:75:41)
   at packages/caching-compiler/multi-file-caching-compiler.js:115:45
   at packages/caching-compiler/multi-file-caching-compiler.js:97:11
   at
   C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:324:29
   at
   C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:44:16
   at packages/caching-compiler/multi-file-caching-compiler.js:148:9
   at
   C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:324:29
   at
   C:\Users\vtulin\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:44:16
   at packages/caching-compiler/multi-file-caching-compiler.js:148:9
   at

... last chunks of error loops for thousands times (see attached log).
Looks like a recursion loop.

Angular-compiler version 0.6.0.
Here are my dependencies:

  "dependencies": {
    "@angular/common": "=2.0.0-rc.5",
    "@angular/compiler": "=2.0.0-rc.5",
    "@angular/core": "=2.0.0-rc.5",
    "@angular/forms": "^2.0.0-rc.6",
    "@angular/platform-browser": "=2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "=2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.2",
    "@angular2-material/button": "^2.0.0-alpha.7-4",
    "@angular2-material/core": "^2.0.0-alpha.7-4",
    "@angular2-material/input": "^2.0.0-alpha.7-4",
    "@angular2-material/list": "^2.0.0-alpha.7-4",
    "@angular2-material/sidenav": "^2.0.0-alpha.7-4",
    "@angular2-material/toolbar": "^2.0.0-alpha.7-4",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-polyfills": "^0.1.1",
    "meteor-node-stubs": "~0.2.0",
    "ng2-material": "^0.6.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0-beta.11",
    "zone.js": "^0.6.17"
  },

Thank you.
[log.txt](https://github.com/Urigo/angular2-meteor/files/454879/log.txt)

**Comment by stefanholzapfel** [comment]
I had a similar problem with Angular RC5. In my case, the constructor of the component was infinitely looping without ever reaching the onInit lifecycle hook.

The problem was (or is, since the issue isn't resolved yet), that Angular somehow couldn't cope with my templates when importing them from an .html file. For the moment it works for me when creating the templates directly in the component with ``.

**Comment by vtulin** [comment]
@stefanholzapfel I don't think that is the problem, as I mentioned this code works on another similar workstation, both Windows 8.1 x64, both using same Meteor version and meteor packages. Now I'm trying to rebuild it on clean new virtual machine.

**Comment by vtulin** [comment]
So, for now I've done a trial research:

- project cloned from bitbucket **is identical to a working copy on another computer** (as Git says);
- project cloned from bitbucket **doesn't work on a clean virtual machine** (same output);
- created from scratch new meteor project with copied scripts returns same output **%)**.

Something went wrong!))
Proceeding my research.

**Comment by vtulin** [comment]
Ok, I found the clue! yey! but I'm not sure where exactly the issue. If I run in just cloned project from bitbucket **meteor npm install** it won't start, if I run **npm install** it will.

What does exactly **meteor** prefix in **meteor npm install** do?

**Comment by Tallyb** [comment]
it can be different versions. You can check it out: 
![image](https://cloud.githubusercontent.com/assets/7386255/18271037/c7536766-7438-11e6-90ef-6aa64f3f5967.png)

**Comment by vtulin** [comment]
Yep, this is it:
![2016-09-06_15-33-42](https://cloud.githubusercontent.com/assets/21104306/18273921/7f7206f4-7448-11e6-8bcf-5339c3bf76a3.png)

Upgrade of npm has fixed an issue! Thank you!!!
