### ISSUE TITLE
how to add features (sub-modules) in angular-meteor (using angular2)

### ISSUE THREAD

**Issue by neeraj1928** [Urigo/angular2-meteor#387]
I have just gone through tutorial of angular-meteor (socially) and angular 2 (https://angular.io/docs/ts/latest/guide/router.html). In the angular2 guide, they have mentioned how to create submodules (features) and then how it can be easily imported into the app.module.ts. But the issue here is that in meteor-app there is no such app.module.ts and instead they have app.main.ts and in it there is the bootstrap class which tells the entry point in the app. It takes only a component and providers. Please tell me how can we add submodules (features) in the angular-meteor.

**Comment by stefanholzapfel** [comment]
I guess the socially tutorial is outdated and for RC4.

To use RC5:

Bootstrapping in main.ts:
```
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";
import {AppModule} from "path-to-your-module/app.module";

platformBrowserDynamic().bootstrapModule(AppModule);
```

index.html example:

`<head>
    <base href="/">
</head>
<body>
    <my-app></my-app>
</body>`

Modules are created like this:
```
@NgModule({
    imports: [],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
export class AppModule {}
```

Read futher details about modules and it's imports, declarations, etc. here:
[https://angular.io/docs/ts/latest/guide/ngmodule.html](url)

RC6 seems not to be supported until now.

**Comment by neeraj1928** [comment]
Thank you for pointing me to rc4 issue. Now I have create a new app with the updated package.json to install the new dependencies.
`

    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",


    "angular2-meteor": "0.6.2",
    "angular2-meteor-auto-bootstrap": "0.6.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",


    "es6-shim": "0.35.1",
    "meteor-node-stubs": "0.2.3",


    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.17",

    "angular2-in-memory-web-api": "0.0.18",
    "bootstrap": "^3.3.6"`

Then I created a new app.module.ts in the client folder. Its code is below:

`
    import { NgModule }      from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';

    @NgModule({
      imports:      [ BrowserModule ]
    })

    export class AppModule { }
`

But now it is throwing the error that NgModule can't be found. Please guide

**Comment by stefanholzapfel** [comment]
As mentioned, RC6 is not supported yet. 

```
"@angular/common": "2.0.0-rc.6",
"@angular/compiler": "2.0.0-rc.6",
"@angular/core": "2.0.0-rc.6",
"@angular/forms": "2.0.0-rc.6",
"@angular/http": "2.0.0-rc.6",
"@angular/platform-browser": "2.0.0-rc.6",
"@angular/platform-browser-dynamic": "2.0.0-rc.6",
```
should be
```
"@angular/common": "=2.0.0-rc.5",
"@angular/compiler": "=2.0.0-rc.5",
"@angular/core": "=2.0.0-rc.5",
"@angular/forms": "=2.0.0-rc.5",
"@angular/http": "=2.0.0-rc.5",
"@angular/platform-browser": "=2.0.0-rc.5",
"@angular/platform-browser-dynamic": "=2.0.0-rc.5",
```

Don't forget to clean out the node_modules directory and reinstall with "meteor npm install".

**Comment by neeraj1928** [comment]
Thank you for quick reply.
I remove my node_modules directory. Changed the package.json code with this one
`

    "@angular/common": "^2.0.0-rc.5",
    "@angular/compiler": "^2.0.0-rc.5",
    "@angular/core": "^2.0.0-rc.5",
    "@angular/forms": "^2.0.0-rc.5",
    "@angular/http": "^2.0.0-rc.5",
    "@angular/platform-browser": "^2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.2",

`

But still unable to import NgModule in my meteor app
`import { NgModule }      from '@angular/core';`
it is throwing this error

> Module '"/home/mista/meteor-app/socially/node_modules/@angular/core/index"' has no exported member 'NgModule'.at line 1 col 10

**Comment by stefanholzapfel** [comment]
Ok, than it's a problem with the typescript typings.

Look up the "moduleResolution" in tsconfig.json. It should be:

` "moduleResolution": "node",`

to make typescript look in your node_modules directory for typings files.

**Comment by neeraj1928** [comment]
`"moduleResolution": "node", ` this is already there in tsconfig.json.

Below is my tsconfig.json
`
  {
    "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "isolatedModules": false,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}

`

I want to point out that i can easily import  this `import { Component } from '@angular/core';` from the core module

**Comment by stefanholzapfel** [comment]
Also set "experimentalDecorators" to true and set the "filesGlob" Array to the same as in my example:

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "isolatedModules": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "filesGlob": [
    "client/**/*.ts",
    "imports/**/*.ts",
    "server/**/*.ts",
    "typings/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by neeraj1928** [comment]
I have added "fileGlod" but it is still showing the same error. It is throwing error for these two modules
`

    import { NgModule }      from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';

`

However i can easily import other modules like 
`import { FormsModule } from '@angular/forms';`

**Comment by stefanholzapfel** [comment]
Try not using the "^"operator but "**=**" in the package json (to really get RC5) and **delete** the nodes_module\@angular directory before using "meteor nmp install" again...

`"@angular/core": "=2.0.0-rc.5",`

If that doesn't work, I'm running out of ideas :)

**Comment by stefanholzapfel** [comment]
Ahh one more:

use the newest version of angular-meteor:

`"angular2-meteor": "^0.7.0-beta.1",`

**Comment by neeraj1928** [comment]
I am sorry but still error is there.
To be safe I am deleting the node_modules directory, implementing the changes you mentioned and then ran `meteor npm install` but still the same issue.
Could you please tell me how are you using angular2-meteor? Are you able to use NgModule and easily create submodules and also include routing in it as they mentioned.

**Comment by stefanholzapfel** [comment]
Yes I'm using feature modules as well as a core module and shared module as described in the angular docs. I do routing in the responsible feature module.

**Comment by neeraj1928** [comment]
Is it possible that you can share your package.json or some example repo which I can see to figure out what wrong I am doing.
Before I have developed web-app using turbogears2 (python mvc framework). But after reading about meteor and angular2 and going through various videos i wanted to use angular2-meteor. In one of the video Urigo mentioned that angular2 and meteor team are working together to create this framework. Since last 10 days i ( and my team also)  have been learning curiously angular2 and meteor. I have tried tutorials of both angular2 and angular2-meteor, they worked fine but when we are combing things, it is throwing error. We want to use this angular2-meteor. Please suggest

**Comment by stefanholzapfel** [comment]
Here's my whole package.json:

```
{
  "name": "sbs",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "=2.0.0-rc.5",
    "@angular/compiler": "=2.0.0-rc.5",
    "@angular/core": "=2.0.0-rc.5",
    "@angular/forms": "^2.0.0-rc.6",
    "@angular/platform-browser": "=2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "=2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.2",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-polyfills": "^0.1.1",
    "bcrypt": "^0.8.7",
    "bootstrap-sass": "^3.3.7",
    "bootswatch": "^3.3.7",
    "meteor-node-stubs": "^0.2.3",
    "ng2-bootstrap": "^1.0.24",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0-beta.11",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "tslint": "^3.14.0",
    "typescript": "^2.0.2"
  }
}
```

my complete app.module.ts:

```
import { NgModule }         from '@angular/core';

//Imports
import {BrowserModule}      from '@angular/platform-browser';
import {SharedModule}       from '../_shared/shared.module';
import {CoreModule} from '../_core/core.module';
import {routing}            from '../_app/app.routing';
//Feature imports
import {DashboardModule}    from '../dashboard/dashboard.module';
import {ModuleSelectorModule} from '../module-selector/module-selector.module';
import {ItemModule} from '../item/item.module';
import {UserModule} from '../user/user.module';

//Declarations
import {AppComponent}      from './app.component';

@NgModule({
    imports: [
        BrowserModule,
        SharedModule,
        CoreModule,
        routing,
        // Feature modules:
        DashboardModule,
        ModuleSelectorModule,
        ItemModule,
        UserModule
    ],
    declarations: [
        AppComponent
    ],
    bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by neeraj1928** [comment]
Thank you very much for sharing this. I will keep on working on it

**Comment by Tallyb** [comment]
@neeraj1928 https://github.com/Tallyb/meteor-angular2.0-socially/tree/rc5 (note: RC5 branch!) has a project that works. It has lot of issues that I did not work out (layout, ngmaps etc.) but it can bootstrap. 

check your meteor npm and node versions (meteor npm -v, meteor node -v)

**Comment by neeraj1928** [comment]
meteor npm -v  is 3.10.6  and meteor node -v is 4.5.0.
Thank you for sharing this branch. I will go through it.

**Comment by neeraj1928** [comment]
@Tallyb I am trying to bootstrap your given branch. But it is throwing this error
`npm ERR! Failed at the ng2-material@0.6.1 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.`

version of node installed in my system is 'node/6.5.0' (node --version) but when i run meteor node --version it show 4.5.0. How to update node inside meteor?

**Comment by Tallyb** [comment]
@neeraj1928  you cannot upgrade inside meteor.  It seems to be like a typings issue. Do you have typings install? which version?

**Comment by neeraj1928** [comment]
typings version is 3.10.6 (meteor npm typings -v)

**Comment by Tallyb** [comment]
nay, this is meteor npm version. what happens in "typings -v"?

**Comment by neeraj1928** [comment]
npm typings -v shows 3.10.3

**Comment by Tallyb** [comment]
no npm - just typings

**Comment by neeraj1928** [comment]
sorry, it is not installed (command not found is showing).  Should i install it with sudo apt-get install typings

**Comment by Tallyb** [comment]
ok - this seems to be the problem. 
` npm install -g typings

**Comment by neeraj1928** [comment]
@Tallyb Thank you very much. I installed typings and now I can boostrap your branch. Thank you very much. Just one more thing, could please suggest good package to add material design to my project.

**Comment by neeraj1928** [comment]
And could you also tell what error made you think that this is the issue of typings?

**Comment by Tallyb** [comment]
@neeraj1928  Angular2-material is the most appropriate. I installed ng2-material to use layout directives. I do not think there is anything better. 
PS - care to star my project?

**Comment by Tallyb** [comment]
it says the problem here is the typings:  Failed at the ng2-material@0.6.1 postinstall script 'typings install'

**Comment by neeraj1928** [comment]
ok. Thank you very much for your support
