### ISSUE TITLE
ObservableCollection.find() (without arguments) doesn't work

### ISSUE THREAD

**Issue by Lavan** [Urigo/angular2-meteor#388]
The `find()` call in ObservableCollection expands into a call to `Meteor.Collection.find(undefined, undefined)`.

As this call has an actual 2 arguments it doesn't work with 

At https://github.com/meteor/meteor/blob/devel/packages/mongo/collection.js#L315-L316 and subsequently here: https://github.com/meteor/meteor/blob/devel/packages/mongo/collection.js#L265-L270, where an empty parameter list is correctly transformed to `{}` but if there are actual arguments arguments then they will be passed on regardless of their value, including undefined. As it seems that minimongo doesn't like the undefined selector at all it will return an empty cursor in that case.

**Comment by Lavan** [comment]
I was thinking about changing https://github.com/Urigo/angular2-meteor/blob/master/modules/minimongo-observable/observable-collection.ts#L132

```
const cursor = this._collection.find(selector, options);
```

into

```
const cursor = this._collection.find(selector || {}, options);
```

Similar change for findOne as well.

**Comment by barbatus** [comment]
Ok, I changed to the latter. Also it's been moved to a new package https://github.com/Urigo/mongo-rxjs-observable. Please check out it from there.
