### ISSUE TITLE
Angular2 meteor with accounts-password module

### ISSUE THREAD

**Issue by mariohmol** [Urigo/angular2-meteor#389]
I'm trying to change whatsapp clone app to have login with normal password, but i can get this module to work.. Does have any project in docs using accounts-password? Is it working with angular2? If not, is any workaround? 

Here is the question on stack:

* http://stackoverflow.com/questions/39451400/cant-make-meteor-account-password-to-work-with-meteor-angular2

**Comment by PseudoPsycho** [comment]
I am using it without any problems whatsoever.Accounts-UI is obviously not working because it uses Blaze. The extension in question, however, works flawless.
Can you explain the problem a little further? What did you do and what happens? Do you get any errors?

**Comment by mariohmol** [comment]
Thanks for your help..is so hard to find help in meteor...

look at this issue.. https://github.com/DAB0mB/ionic2-meteor-messenger/issues/7

basicly.. i install meteor using atmosphere.. use the require.. but meteor never works the password methods

**Comment by mariohmol** [comment]
Instead of using this project fork the tutorial project example, i'm doing from the scratch following the tutorial. In this part i have:

https://www.angular-meteor.com/tutorials/whatsapp2/ionic/authentication

```
$ meteor add accounts-base
$ meteor add okland:accounts-phone
$ npm install accounts-base-client-side --save
$ npm install accounts-phone --save
```

Applying the same idea for `accounts-password` it works for `meteor add accounts-password` .
But i do not have the npm package `npm install accounts-password`. But lets consider that this will not work for the frontend, what is ok for me because i can create i method on backend to do login/sigin and other operations with accounts-password.

So if i try to import on client side i have:

```
Module not found: Error: Cannot resolve module 'accounts-password' in /app
 @ ./app/app.ts 17:0-28
 ```

 So trying to make it work on backend anyway, i created a meteor methods

 ```
 import {Meteor} from 'meteor/meteor';
 import {check, Match} from 'meteor/check';
 import {Accounts} from 'meteor/accounts-base';

 Meteor.methods({
   updateProfile(login: string): void {
     Accounts.createUser({username: login, password: 'password'})
   }
 });
 ```

 And when i call it using the frontend i'm getting :


 ```
 Exception while simulating the effect of invoking 'updateProfile' TypeError: Cannot read property 'Accounts' of undefined(…) TypeError: Cannot read property 'Accounts' of undefined
    at updateProfile (http://localhost:8101/build/js/app.bundle.js:102775:25)
    at http://localhost:8101/build/js/app.bundle.js:104:16735
    at withValue (http://localhost:8101/build/js/app.bundle.js:95:31865)
    at Connection.apply (http://localhost:8101/build/js/app.bundle.js:104:16574)
    at Connection.call (http://localhost:8101/build/js/app.bundle.js:104:15571)
    at Object.call (http://localhost:8101/build/js/app.bundle.js:102945:15)
    at meteorCall (http://localhost:8101/build/js/app.bundle.js:103482:26)
    at ZoneDelegate.invoke (http://localhost:8101/build/js/zone.js:323:29)
    at Object.onInvoke (http://localhost:8101/build/js/app.bundle.js:13033:42)
    at ZoneDelegate.invoke (http://localhost:8101/build/js/zone.js:322:35)
```

Its so basic process, i really dont know what am i doing wrong.

here is the project that i created for this example:

https://github.com/mariohmol/brigadistas

thanks for your help!

**Comment by mariohmol** [comment]
Allright.. made some progress.. if i put a `if (Meteor.isServer) `.

So the question now is.. how to use accounts-password in the frontend app? 

Now i will try to make this work in the https://github.com/DAB0mB/ionic2-meteor-messenger/ project

```
if (Meteor.isServer) {
  Meteor.methods({
    updateProfile(login: string): void {
      Accounts.createUser({username: login, password: 'password'})
    }
  });
}
```

**Comment by mariohmol** [comment]
Here is the fork in ionic2-meteor-messenger with accounts-password instead:

* https://github.com/mariohmol/ionic2-meteor-messenger

But still having problems to login after create user, here is more details:

https://github.com/idanwe/accounts-password-client-side/issues/7

**Comment by mariohmol** [comment]
Could make it work. the solution is in other issue

Well.. what i have as a lesson is... there is a slack in meteor documentation about accounts-password, without a module like @idanwe we can make a simple login using password

**Comment by mariohmol** [comment]
There is a module that handles the accouns-password for frontend, here is a full example : https://github.com/mariohmol/ionic2-meteor-messenger-password

**Comment by aleksander351** [comment]
@mariohmol: link broken...

**Comment by mariohmol** [comment]
sorry.. i deleted unintencionally =(
