### ISSUE TITLE
Getting "UNMET PEER DEPENDENCY" errors when running "npm install angular2-meteor --save"

### ISSUE THREAD

**Issue by rbrugnollo** [Urigo/angular2-meteor#390]
Hey guys, I'm trying to start a new project and when I run:
```npm install angular2-meteor --save```

I get the following result:
```
+-- UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.5
+-- angular2-meteor@0.7.0-beta.1
| `-- lodash@4.15.0
`-- UNMET PEER DEPENDENCY angular2-meteor-polyfills@^0.1.1
```

Any ideas on how to solve this problem?

Tks

**Comment by derekkite** [comment]
What angular version are you using? rc6 breaks quite a bit.

**Comment by barbatus** [comment]
install @angular/core and  angular2-meteor-polyfills
