### ISSUE TITLE
https://github.com/bsliran/angular2-meteor-base not work for me. 

### ISSUE THREAD

**Issue by inromualdo** [Urigo/angular2-meteor#394]
Can i use meteor angular 2 from scrash. meteor create, install dependencies and so one...

When i clone the repo, meteor npm install end metro, it throws this error: /Users/mac/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
throw error;
^

Error: ENOENT: no such file or directory, open '/private/var/folders/v0/bzh15d2n24vfzqzp9fzrnr700000gn/T/mt-qi6wj/os.json'
at Error (native)

**Comment by inromualdo** [comment]
Please, i can actually use angular2 meteor in OS Sierra. this error appear: 

/Users/mac/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
throw error;
^

Error: ENOENT: no such file or directory, open '/private/var/folders/v0/bzh15d2n24vfzqzp9fzrnr700000gn/T/mt-qi6wj/os.json'
at Error (native)

**Comment by kamilkisiela** [comment]
Try to use
```
meteor reset 
```

**Comment by Urigo** [comment]
@inromualdo we changed a lot on the repo in the last couple of days and updated it to the latest Angular 2.0 stable and updated all the tutorials as well.
Please try again and if something is not working open a new issue in the central repository here - https://github.com/urigo/angular-meteor
