### ISSUE TITLE
Extracting angular2-compiler never ends after compile 'meteor add angular2-compilers@0.6.0' on Windows 7

### ISSUE THREAD

**Issue by juliocesar12** [Urigo/angular2-meteor#395]
Hello everyone, I am trying to install angular2-meteor(https://www.npmjs.com/package/angular2-meteor) but when I try to compile 'meteor add angular2-compilers@0.6.0' in the CMD of Windows 7 it returns the message 'Extracting angular2-compilers@0.6.0... ' but never ends. Before of this, the message which is show is 'Downloading angular2-compilers@0.6.0.'.
Thanks
![extangular2-components](https://cloud.githubusercontent.com/assets/11258942/18791125/177d8122-8177-11e6-9a56-5b9916b43a6f.png)

**Comment by barbatus** [comment]
hm, seems to be some issue with 7z.exe. Is it the same with angular2-compilers@0.6.1 as well?
Try to re-install meteor, as I know it was helpful for similar issues before.

**Comment by stefanholzapfel** [comment]
I had a similar issue with another atmosphere package. Found out that meteor was using a tar.exe from my git folder which didn't work.

Open a cmd shell (when on windows?) and type "where tar". If it shows a tar.exe from your git folder, go there and rename it. Than install the newest 7zip. Meteor will now use its extractor.

Hope that also helps in your case.

**Comment by juliocesar12** [comment]
@barbatus thanks for responding, I re-installed meteor, but the bug persists yet.

**Comment by juliocesar12** [comment]
@stefanholzapfel thanks for responding, it works, I renamed the tar.exe and install 7zip. :D 
thank you very much
