### ISSUE TITLE
angular2-compilers CSS Compiler does't escape CSS strings

### ISSUE THREAD

**Issue by Kamshak** [Urigo/angular2-meteor#396]
If compiling a style like this:

```
span::after {
     content: "\00A0 \2014"; // nbsp, em dash
}
``` 

The compiler errors:
```
C:\Users\funkv\AppData\Local\.meteor\packages\angular2-compilers\0.6.0\plugin.Angular2Compilers.os.windows.x86_32\npm\node_modules\meteor\babel-compiler\node_modules\babylon\lib\parser\location.js:22:13:
   Octal literal in strict mode (508:14)
```

**Comment by Kamshak** [comment]
@barbatus could you take a look? I think it needs escaping here: https://github.com/Urigo/angular2-meteor/blob/master/atmosphere-packages/css-compiler/compilers/basic_compiler.js#L56

**Comment by barbatus** [comment]
btw I don't think \00A0 \2014 is a valid JS string, which basically means you are trying to escape 0 or 2 in them.

**Comment by barbatus** [comment]
but valid CSS, alright
