### ISSUE TITLE
latest project: error core.umd.js:403Uncaught reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by elpddev** [Urigo/angular2-meteor#401]
On angular 2 new project, I get this error:
core.umd.js:403Uncaught reflect-metadata shim is required when using class decorators

**Comment by barbatus** [comment]
Because you are missing `reflect-metadata`. As it's said in the readme: either import `angular2-meteor-polyfills` at top of the main file of your app, or add `barbatus:angular2-polyfills` package
