### ISSUE TITLE
Not loading template

### ISSUE THREAD

**Issue by akshath4u** [Urigo/angular2-meteor#404]
I have configured my project with angular2 meteor. But while running the project I am getting below error. (screen shot attached)
<img width="1275" alt="screen shot 2016-09-26 at 11 08 39 pm" src="https://cloud.githubusercontent.com/assets/9428527/18845222/674e74ee-843e-11e6-8a3f-ae0f3e394a2f.png">

**Comment by jesperneelen** [comment]
I'm getting the same error

**Comment by barbatus** [comment]
Remove ecmascript package from your app and add barbatus:angular2-polyfills

**Comment by akshath4u** [comment]
I have removed ecmascript and restarted my app. now app crashing with following error
<img width="1274" alt="screen shot 2016-09-27 at 10 24 02 pm" src="https://cloud.githubusercontent.com/assets/9428527/18883584/6d908d1a-8501-11e6-8ad6-b1726a99c124.png">

**Comment by kamilkisiela** [comment]
@akshath4u Silly question, but do you use `barbatus:typescript` package?

**Comment by jesperneelen** [comment]
I get the same error now somehow, couple of days it went good, now it's back to broken

**Comment by barbatus** [comment]
@akshath4u make sure you've installed `barbatus:angular2-polyfills`. If you are using ES6 code, you still need `ecmascript` package. `barbatus:angular2-polyfills` re-adds dependecines in the right way.

**Comment by barbatus** [comment]
@jesperneelen if it doesn't work check what if any other package adds `ecmascript`. The problem here is that ecmascript can overwrite Zone-aware promise with Meteor promise.

**Comment by Urigo** [comment]
can you share a reproduction or at least all your package versions and Meteor version?

**Comment by barbatus** [comment]
Please run `meteor update` to update to the latest barbatus:typescript. It was likely related to the issue when any tsconfig.json from the node_modules could sift through to the compiler.
