### ISSUE TITLE
Is possible to add a style.scss file to the style.index file, in order to be able to use it in all pages(like a style file base)?

### ISSUE THREAD

**Issue by juliocesar12** [Urigo/angular2-meteor#405]
In my file index.html I have the following:
```
<head>
    <base href="/">
</head>
<body>
  <app>Loading...</app>
</body>
```
I would like to add styles to this file, in order to they can be shared by all templates of the project.
I don't know if it is possible, but if not, you can tell another way to create styles which can be shared in all the project? 
Note: 
I cloned this project : https://github.com/bsliran/angular2-meteor-base
I am talking about index.html which is in the Client folder.
Thanks

**Comment by kamilkisiela** [comment]
Yes it is, use `angular2-compilers` package

[It says](https://github.com/Urigo/angular-meteor/tree/master/packages/angular2-meteor/atmosphere-packages/css-compiler#usage):

> If a style file is placed in the client folder, it'll be processed as a regular Meteor style file, i.e., bundled together with other style files.
But if it's placed in the imports folder of your app, then there become available two other ways to access styles for a Angular 2 component.

Those two ways are described in the linked resource.
