### ISSUE TITLE
Unmet Peer Dependency with 'angular2-meteor-auto-bootstrap'

### ISSUE THREAD

**Issue by LelouchLight** [Urigo/angular2-meteor#408]
The current version of the tutorial results in an UNMET PEER DEPENDENCY that prevents the app from running.

Crosss-MacBook-Pro:SST Mars$ meteor npm install --save angular2-meteor-auto-bootstrap
angular2-meteor-base@ /Users/Mars/SST
├── UNMET PEER DEPENDENCY angular2-meteor@0.7.0-beta.2
└── angular2-meteor-auto-bootstrap@0.6.0

**Comment by derek-fong** [comment]
@LelouchLight Current version of `angular2-meteor@0.7.0-beta.3` no longer require `angular2-meteor-auto-bootstrap`. You will need to use `platformBrowserDynamic()` instead 

i.e.
```
platformBrowserDynamic().bootstrapModule(AppModule)
```

Please see https://github.com/Urigo/angular2-meteor/issues/392 will give you some ideas of setting up the project with latest `angular2-meteor` and `angular2.0.1`.

**Comment by juliocesar12** [comment]
it seems the tutorial is not updated. I cloned this project https://github.com/bsliran/angular2-meteor-base as the tutorial says, but when I tried to follow the rest of the tutorial I had your bugs, so I realized tutorial page's syntaxis is not the right to the project cloned.
@derek-fong one question please, You recommend me to start my project from the cloned project https://github.com/bsliran/angular2-meteor-base?
Thanks

**Comment by derek-fong** [comment]
@juliocesar12 yes [angular2-meteor-base](https://github.com/bsliran/angular2-meteor-base) has recently updated with `angular2.0.0` - I have cloned that repo yesterday, tested and it is working. 

Like you said the [tutorial](https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping) is a bit out-dated and it's just needs to be refreshed but I think most of the key concepts demonstrated in the tutorial are still valid.
