### ISSUE TITLE
Race condition when publishing selected fields from collection that contains more fields on .insert()

### ISSUE THREAD

**Issue by slippyC** [Urigo/angular2-meteor#409]
This pertains to this issue:
https://forums.meteor.com/t/issue-with-subscribing-to-certain-fields-in-mongo-collection-crash-when-insert-new-document/29759

Way to reproduce error:
Publish a collection that only contains certain fields you want from that collection
ex. Collection.find({},{fields:{field1:1,field2:1}});
Subscribe to that collection.
Have a page/view open that displays those variables reactively.
Do an .insert() on that collection or do a Meteor.method() that will insert into that collection
Bad news.... :(

Questions you may have:
This is the only publish being subscribed to that updates that Collection on the client(minimongo).
It will also crash the app if a remote client does an .insert()
If `{fields:{field1:1,field2:1}}` is removed from that publish, the error goes away.
This crash happens client-side only.

**Comment by barbatus** [comment]
what error exactly do you get?

**Comment by dotansimha** [comment]
This issue was moved to Urigo/angular-meteor#1473
