### ISSUE TITLE
Can't install angular2-compilers@0.6.2 windows x64

### ISSUE THREAD

**Issue by derek-fong** [Urigo/angular2-meteor#410]
RE: https://github.com/Urigo/angular2-meteor/issues/383 - Noticed `angular2-compilers@0.6.2` has been released. Tried to update the package on Windows with no success. 

``` 
=> Errors while adding packages:

While checking for angular2-compilers@0.6.2:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.
```

I have also tried 

```
meteor remove angular2-compilers
meteor rebuild
meteor add angular2-compilers
```

but that did not resolve the problem.

Any ideas?

**Comment by juliocesar12** [comment]
You can try with:
> meteor add angular2-compilers@=0.6.2
I did the same for version 0.6.0.
I hope I can help you

**Comment by barbatus** [comment]
Which version of Meteor are you using? Meteor 1.4.1 shouldn't require compatible build any more (https://github.com/meteor/meteor/blob/devel/History.md#v141)

**Comment by derek-fong** [comment]
@barbatus 

```
$ meteor --version
Meteor 1.4.1.1
```

I have cloned the same repo to my Mac, tried to update `angular2-compilers@0.6.2` and it works fine. 

However, it still does not work on my Windows PC. :disappointed:

**Comment by htafolla** [comment]
I am having the same issue on Windows running Meteor 1.4.1.1.

meteor --version
Meteor 1.4.1.1

meteor add angular2-compilers
 => Errors while adding packages:

While checking for angular2-compilers@0.6.1:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

**Comment by barbatus** [comment]
@derek-fong what if you follow this https://guide.meteor.com/v1.4/1.4-migration.html#binary-packages-require-build-toolchain and install MS Build Tools. Let see then if it's gonna help.

**Comment by ArthurMauricioDelgadillo** [comment]
I'm having the same issue on Windows 10 x64,  If a create a new meteor project it works ok using meteor 1.4.1.1 (not using angular2-meteor), but doesn't work when I clone the angular2-meteor-base. I also tried with `meteor add angular2-compilers@=0.6.2` but same result.

**Comment by jycouet** [comment]
Hi @barbatus.
I followed [ https://guide.meteor.com/v1.4/1.4-migration.html#binary-packages-require-build-toolchain](url) and I installed [MS Build tools](https://www.microsoft.com/en-us/download/details.aspx?id=48159). 
In the guide, they show how to check if everything is working or not. And it was not... After some time I found I nice way to install everything with one command:
> npm install --global --production windows-build-tools

Like this `meteor npm install bcrypt` work well. So I guess that my **Build Toolchain** is now working.

But I still get 

> meteor add angular2-compilers@0.6.2
>  => Errors while adding packages:
> 
> While checking for angular2-compilers@0.6.2:
> error: No compatible binary build found for this package. Contact the
> package author and ask them to publish it for your platform.

**Comment by kokokenada** [comment]
I'm getting the problem on Mac after adding the xcode build tools (xcode-select --install)

```
xcode-select -p
/Applications/Xcode.app/Contents/Developer

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

meteor update angular2-compilers
=> Errors while upgrading packages:           
                                              
While checking for angular2-compilers@0.6.2:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by barbatus** [comment]
We published new version, it should fix the problem, please try.

**Comment by jycouet** [comment]
Hi @barbatus, 

I confirm that on Windows x64 it's working well now.

> C:\MyTextProject>meteor add angular2-compilers
> 
> Changes to your project's package version selections:
> 
> angular2-compilers            added, version 0.6.2_1
> barbatus:css-compiler         added, version 0.3.1_1
> barbatus:scss-compiler        added, version 3.8.1_3
> barbatus:typescript           added, version 0.4.1
> barbatus:typescript-compiler  added, version 0.7.1_1
> barbatus:typescript-runtime   added, version 0.1.2
> urigo:static-html-compiler    added, version 0.1.8
> 
> 
> angular2-compilers: Angular 2 Templates, HTML and TypeScript compilers for
> Meteor

Thank you very much :)

**Comment by kokokenada** [comment]
Fixed on mac too

**Comment by derek-fong** [comment]
@barbatus Sorry for the late reply I have been away - Tested on Windows and confirmed it's working. 

Cheers :+1:
