### ISSUE TITLE
Uncaught TypeError: Cannot read property 'current' of undefined when including METEOR_PROVIDERS.

### ISSUE THREAD

**Issue by AngelCastilloB** [Urigo/angular2-meteor#411]
I am using **angular2-meteor": "^0.7.0** with angular **^2.0.0**, I had to remove all the MeteorComponent inheritance because I would get the error:

`Uncaught TypeError: Cannot read property 'current' of undefined`
I tracked the error down to this line:

`var gZone = g.Zone.current;`

Only adding

> METEOR_PROVIDERS

To the list of providers on my main module would trigger the error. So as of right now I cant use the MeteorReactive class.

This is what my list of npm dependencies looks like:

>     "@angular/common": "^2.0.0",
>     "@angular/compiler": "^2.0.0",
>     "@angular/core": "^2.0.0",
>     "@angular/forms": "^0.3.0",
>     "@angular/platform-browser": "^2.0.0",
>     "@angular/platform-browser-dynamic": "^2.0.0",
>     "@angular/router": "^3.0.0",
>     "@angular2-material/button": "2.0.0-alpha.8-2",
>     "@angular2-material/button-toggle": "2.0.0-alpha.8-2",
>     "@angular2-material/card": "2.0.0-alpha.8-2",
>     "@angular2-material/checkbox": "2.0.0-alpha.8-2",
>     "@angular2-material/core": "2.0.0-alpha.8-2",
>     "@angular2-material/grid-list": "2.0.0-alpha.8-2",
>     "@angular2-material/icon": "2.0.0-alpha.8-2",
>     "@angular2-material/input": "2.0.0-alpha.8-2",
>     "@angular2-material/list": "2.0.0-alpha.8-2",
>     "@angular2-material/menu": "2.0.0-alpha.8-2",
>     "@angular2-material/progress-bar": "2.0.0-alpha.8-2",
>     "@angular2-material/progress-circle": "2.0.0-alpha.8-2",
>     "@angular2-material/radio": "2.0.0-alpha.8-2",
>     "@angular2-material/sidenav": "2.0.0-alpha.8-2",
>     "@angular2-material/slide-toggle": "2.0.0-alpha.8-2",
>     "@angular2-material/slider": "2.0.0-alpha.8-2",
>     "@angular2-material/tabs": "2.0.0-alpha.8-2",
>     "@angular2-material/toolbar": "2.0.0-alpha.8-2",
>     "@angular2-material/tooltip": "2.0.0-alpha.8-2",
>     "angular2-meteor": "^0.7.0",
>     "angular2-meteor-polyfills": "^0.1.1",
>     "angular2-meteor-tests-polyfills": "0.0.2",
>     "ng2-dragula": "^1.1.10",
>     "@angular/http": "2.0.0",
>     "faker": "^3.1.0",
>     "gm": "^1.22.0",
>     "transliteration": "^1.1.6",
>     "meteor-node-stubs": "0.2.3",
>     "meteor-rxjs": "0.2.3",
>     "reflect-metadata": "^0.1.8",
>     "rxjs": "5.0.0-beta.12",
>     "core-js": "^2.4.1",
>     "dragula": "^3.7.1",
>     "es6-shim": "^0.35.0",
>     "zone.js": "^0.6.21"

and this is my meteor package file:

> meteor-base 
> mobile-experience
> mongo
> reactive-var
> jquery
> tracker
> standard-minifier-css
> standard-minifier-js
> es5-shim
> ecmascript
> angular2-compilers@=0.6.0
> aldeed:simple-schema
> aldeed:collection2
> konecty:mongo-counter
> jalik:ufs
> jalik:ufs-local
> check
> momentjs:moment
> percolate:migrations
> service-configuration
> accounts-password
> accounts-facebook
> accounts-google
> accounts-twitter
> biglup:biglup-ui

I was following this:

https://github.com/Urigo/angular2-meteor/tree/master/examples/todos-meteor-1.3

As an example and I cant find what is it that I am doing wrong, I did notice that the angular meteor base project is not adding METEOR_PROVIDERS to the list of providers:

https://github.com/bsliran/angular2-meteor-base/blob/master/client/imports/app/app.module.ts

So does that means MeteorReactive cant be used yet? or something is wrong with my setup?

**Comment by derek-fong** [comment]
```
meteor remove ecmascript
meteor add barbatus:angular2-polyfills
meteor add barbatus:angular2-runtime
meteor npm install --save angular2-meteor@0.7.0-beta.3
```

In [app.module.ts](https://github.com/derek-fong/angular2-meteor-boilerplate/blob/master/imports/client/app/app.module.ts#L15), 

```
@NgModule({
  imports: [
    ...
  ],
  providers: [METEOR_PROVIDERS],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
```


Sample [meteor/packages](https://github.com/derek-fong/angular2-meteor-boilerplate/blob/master/.meteor/packages#L20-L21) and [package.json](https://github.com/derek-fong/angular2-meteor-boilerplate/blob/master/package.json#L23).

**Comment by AngelCastilloB** [comment]
Thanks @derek-fong, that solved the issue 👍 . When I was doing the upgrade to angular 2.0.1 at some point I removed barbatus:angular2-runtime because it was giving me a "promise override" error.
