### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by htafolla** [Urigo/angular2-meteor#412]
After upgrading to 2.0.1 and 0.7.0-beta.3. I get this error when trying to load the app.

app.js?hash=602e44d…:2553 Uncaught SyntaxError: Unexpected token import

import 'rxjs/add/observable/throw'; 

It looks like the typescript conversion to js is not happening correctly.

**tsconfig.js**
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "isolatedModules": false,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true,
    "noEmitHelpers": true
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
**Package.json**
{
  "name": "wordproject",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "devDependencies": {
    "chai": "3.5.0",
    "chai-spies": "0.7.1"
  },
  "dependencies": {
    "@angular/common": "~2.0.1",
    "@angular/compiler": "~2.0.1",
    "@angular/core": "~2.0.1",
    "@angular/forms": "~2.0.1",
    "@angular/http": "~2.0.1",
    "@angular/material": "2.0.0-alpha.9",
    "@angular/platform-browser": "~2.0.1",
    "@angular/platform-browser-dynamic": "~2.0.1",
    "@angular/router": "~3.0.1",
    "angular2-autosize": "^1.0.0",
    "angular2-meteor": "^0.7.0-beta.3",
    "angular2-meteor-accounts-ui": "^0.8.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-pagination": "^0.2.1",
    "bcrypt": "^0.8.7",
    "es6-shim": "^0.35.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "typescript": "^2.0.3",
    "zone.js": "0.6.23"
  }
}

**Package:**

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0   # CSS minifier run for production mode
standard-minifier-js@1.2.0    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.

accounts-password@1.3.0
anti:fake
barbatus:angular2-runtime
practicalmeteor:mocha
xolvio:cleaner
hwillson:stub-collections
dispatch:mocha-phantomjs
tmeasday:publish-counts
mys:fonts
alanning:roles
email@1.1.17
barbatus:angular2-polyfills
shell-server
angular2-compilers@=0.6.0

**Comment by htafolla** [comment]
I had accidently included an unneeded file in the wrong place.

**Comment by maxfriedmann** [comment]
I have a very similar problem right now. Unfortunately I cannot figure out which is the bad file. Is there a possibility to debug the problem or how did you figure out which file was wrong?
