### ISSUE TITLE
Unable to use videogular2 in angular2-meteor project (bounty!)

### ISSUE THREAD

**Issue by langfors** [Urigo/angular2-meteor#414]
I'm unable to use videogular/videogular2 in a recent angular2-meteor project. (This was working in earlier versions of angular2/angular2-meteor/meteor).  I suspect there is a packaging issue with videogular2 which makes it incompatible with angular2-meteor but despite my attempts to debug this I cannot figure it out.  I'm offering a $100 bounty to anyone who can help me solve this.  I have a minimal reproduction of the issue here:

https://github.com/slapfive/todos-meteor-1.3

and here is the link to the bounty:

https://www.bountysource.com/issues/38027022-unable-to-use-videogular2-in-angular2-meteor-project

Thanks in advance for any help!

**Comment by Urigo** [comment]
@langfors did you solve it?

**Comment by langfors** [comment]
@Urigo  no, I coudln't solve it but I believe that it's a duplicate of videogular/videogular2#249 which implicates Angular2
