### ISSUE TITLE
Step 3 : Cannot find module '../../both/coll ections/parties.collection'.

### ISSUE THREAD

**Issue by kenp77** [Urigo/angular2-meteor#415]
Hi,

I'm following the socially app tutorial but i'm having an error at step 3 : `' Cannot find module ../../both/collections/parties.collection'.` Note that typings and typings-core are both installed and i can see them under the node_modules.
So what is causing the error ? Now i 'm litte bit discouraged about using Angluar 2 meteor  cause i'm having lot of errors from step 0 and i need to fix them one by one ! Why just don't give us a working app in the official web site ?

**Comment by barbatus** [comment]
Please re-post this issue to the tutorial repo here https://github.com/Urigo/meteor-angular2.0-socially
