### ISSUE TITLE
Scss compiler error: fs.existsSync is not a function

### ISSUE THREAD

**Issue by albsa** [Urigo/angular2-meteor#416]
Hi I am getting this error when trying to compile .scss

```
Errors prevented startup:

While processing files with angular2-compilers (for target web.browser):
/client/main.scss: Scss compiler error: fs.existsSync is not a function


Your application has errors. Waiting for file change.
```

How can this be fixed?

**Comment by Urigo** [comment]
what version of `angular2-compilers` are you using?

**Comment by albsa** [comment]
angular2-compilers@0.6.1

**Comment by Urigo** [comment]
Can you please try updating to `0.6.2_1`?

**Comment by albsa** [comment]
@Urigo still not working :( again:
```
Started MongoDB.
Errors prevented startup:

While processing files with angular2-compilers (for target web.browser):
/client/main.scss: Scss compiler error: fs.existsSync is not a function


Your application has errors. Waiting for file change.
```
I am using NPM 3.10.3
node v6.6.0

angular2-compilers      upgraded from 0.6.1 to 0.6.2_1
barbatus:css-compiler   upgraded from 0.3.0 to 0.3.1_1
barbatus:scss-compiler  upgraded from 3.8.1_1 to 3.8.1_3

**Comment by albsa** [comment]
Thanks @barbatus @Urigo works now.
