### ISSUE TITLE
File collection-object.model.ts is not a module

### ISSUE THREAD

**Issue by kenp77** [Urigo/angular2-meteor#417]
Now i'm having an other error at step 4.14 :
```

both/models/party.model.ts (1, 34): File 'both/models/collection-object.model.ts
' is not a module.
```
Any reason why i have that error ? and how to resolve it ? I'm following the tuto step by step !

**Comment by barbatus** [comment]
It usually means that you don't export anything from this module (`export ...`).
Also please post issue related to the tutorial here https://github.com/Urigo/meteor-angular2.0-socially
