### ISSUE TITLE
What is the correct way of using styles inside a component

### ISSUE THREAD

**Issue by elpddev** [Urigo/angular2-meteor#418]
I am trying to test the style import inside a component. 

`import style from './demo.component.scss!url';`

I get this error:

`install.js:85Uncaught Error: Cannot find module './demo.component.scss!url'`

The [document](https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/css-compiler) say:

```
import styleUrl from './foo.less!url';

@Component({
  selector: 'foo',
  styleUrls: [styleUrl]
})
class Foo {
}

import style from './foo.less'

@Component({
  selector: 'foo',
  styles: [style]
})
class Foo {
}
```

If i try without the !url while debugging I get a module and it works when using with styleUrls: [style] but no shadow dom emulation.

If i try without the !url and using styles: [style] I get an error:

> Uncaught TypeError: Cannot read property 'replace' of undefined

What is the correct way to import a style inside a component ?

**Comment by kamilkisiela** [comment]
This error is just TypeScript related, it won't stop your application to be compiled into JavaScript.

`console.log` or debug styleUrl returned by `./foo.less!url` to see what the value is.

If the value is correct then use code below to hide all TS warning about missing module:

```
declare module '*.scss!url' {
  const url: string;
  export default url;
}
```

I'm not sure it will work (with `!url` suffix) but you can try it out.

**Comment by barbatus** [comment]
Both ways works but use either `styles:[style]` or `styleUrls:[styleUrl]` (ie. no import them together). Shadow DOM emulation is set by the emulation metadata property, by default it's emulated.
