### ISSUE TITLE
route component not loading

### ISSUE THREAD

**Issue by LelouchLight** [Urigo/angular2-meteor#424]
This is the error I get when trying to host locally. 

client/imports/app/app.routes.ts (4, 31): File 'client/imports/home/home.component.ts' is not a module

This is the home.component.ts

`import { Component } from '@angular/core';
 
import template from './home.component.html';
 
@Component({
  selector: 'home',
  template
})
export class HomeComponent {}`

**Comment by jycouet** [comment]
Maybe you should provide the route.ts code.

**Comment by LelouchLight** [comment]
import { Route } from '@angular/router';
 
import { ContactComponent } from '../contact/contact.component';
import { HomeComponent } from '../home/home.component';
 
export const routes: Route[] = [
  { path: '', component: HomeComponent },
  { path: 'contact', component: ContactComponent }
];

**Comment by bergben** [comment]
I suppose your path to the home component is wrong?
import { HomeComponent } from '../home/home.component';

You should provide a more thorough explanation including all the relevant code pieces / folder structure if you expect people to be able to help you.

**Comment by dotansimha** [comment]
@LelouchLight If you are using WebStorm or any other fine IDE, try to remove the import that causes the issue, and try to re-import it using your IDE auto-complete. 

If you are still having issues, please provide a repository with you code.
