### ISSUE TITLE
Is there a way to support typescript without using angular 2?

### ISSUE THREAD

**Issue by zh-wowtv** [Urigo/angular2-meteor#425]
I have a project using meteor as a server only. The client side is native mobile application (iOS and Android). But I still want to use typescript. Is there a way to support typescript without using angular 2.

I found some boilerplates. But all looks quite complicated. For example, some are using gulp to transpile the code which I don't like very much.

**Comment by Urigo** [comment]
@zh-wowtv yes you can, with this package - https://github.com/barbatus/typescript

If you have issues, open those there.
Good luck!
