### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by laserus** [Urigo/angular2-meteor#426]
Is this repo abandoned for https://github.com/Urigo/angular-meteor/tree/master/packages/angular2-meteor?

No commits during a month here, while active development there...

**Comment by Urigo** [comment]
Yes, sorry for not updating but we moved the code to the main `angular-meteor` repository here: https://github.com/urigo/angular-meteor
I'm in the process of migrating everything and deprecating this repo with the right readme
