### ISSUE TITLE
Support for Angular Beta.0?

### ISSUE THREAD

**Issue by vamsivarikuti** [Urigo/angular2-meteor#43]
Is this compatible with Angular Beta?

`/// <reference path="../typings/angular2-meteor.d.ts" />`
Is there a way to avoid this referencing in every single file?

**Comment by barbatus** [comment]
@vamsivarikuti currently no, usually it's avoided by setting `files` property in the ts-config, which
I plan to add soon.

**Comment by vamsivarikuti** [comment]
I thought so, But I have seen a tweet by meteor to try angular2 beta with link to angular-meteor tutorial.

@barbatus I would like to contribute to the repo, but i do not know any of these concepts, can you write an article or something, that provides new comers where to find the resources to learn, and how to contribute

**Comment by barbatus** [comment]
Yes, it was compatible already with the beta at that time.

For the second, what concept do you mean? First resource to learn is Angular2 tutorial. I guess we've been doing to some avail )

**Comment by vamsivarikuti** [comment]
This issues can be closed, angular2-meteor is updated to Angular2.0 beta.0

I'm basically an Angular Dev. I'm very interested in Meteor. 
I want to learn about the things that I need to be able to combine them both. Like you are doing with angular2-meteor. 

One more thing - Why is meteor and other meteor packages converted to use `typescript` and not Angular2 converted to `es6` when meteor has good support for `es6` with `ecmascript` package?

Will angular2-meteor work with `es6` using  meteor's `ecmascript` package?
