### ISSUE TITLE
Error regarding login-button scss not found.

### ISSUE THREAD

**Issue by zaverichintan** [Urigo/angular2-meteor#431]
>    While processing files with angular2-compilers (for target web.browser):
>    /client/main.scss: Scss compiler error: File to import: {}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss not found in file: /home/zaverichintan/socially/{}/client/main.scss

Kindly resolve the issue.

**Comment by Urigo** [comment]
this repository is deprecated, please open this issue on https://github.com/urigo/angular-meteor
also, I think there is already an open issue on it
