### ISSUE TITLE
Error: (SystemJS) Template parse errors:(…) ==> Angular 2

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [Urigo/angular2-meteor#432]
Hello every one i have a problem during running my  project in angular 2 using npm start this is a pic for my problem 
![1](https://cloud.githubusercontent.com/assets/19964514/21176483/9b6b79d6-c1ef-11e6-9cb3-70b5d275aeb2.png)

and when i click on index 20 i go to this line in index.html
System.import('app').catch(function(err){ console.error(err); });

**Comment by Urigo** [comment]
are you using Meteor at all?
this repo is deprecated and moved to https://github.com/urigo/angular-meteor
