### ISSUE TITLE
Disable <app></app> insertion

### ISSUE THREAD

**Issue by Matanlb** [Urigo/angular2-meteor#46]
Hi,

I've been trying incorporate Angular 2 in our system which is currently using blaze, step by step.

The insertion of  <app></app> at the index.html by the package is causing me a lot of trouble, and I've currently have most of this file commented-out.

Assuming that I want to to incorporate Angular 2, at least for the time being, at a non-central point, can I disable this feature?

**Comment by Stivfk** [comment]
Read here https://github.com/Urigo/angular2-meteor/issues/35

**Comment by barbatus** [comment]
If you have at least one HTML file with <body> or <head> tags, it won't be inserted.

**Comment by dotansimha** [comment]
done in https://github.com/Urigo/angular2-meteor/commit/66593685ac30cfd3734c11f152befb6536212395
