### ISSUE TITLE
angular2-meteor & blaze-html-templates integration

### ISSUE THREAD

**Issue by Matanlb** [Urigo/angular2-meteor#48]
Hi,

I've been trying incorporate Angular 2 in our system which is currently using blaze, step by step.

Since replacing the system front end must be an incremental process (and I assume there will be more projects like this after the blaze deprecation) there is a need for allowing both *angular2-meteor* **and** *blaze-html-templates* to work together.

In order to make it work for the time being I've cloned the repo, changed the [plugin in registrator.js](https://github.com/Urigo/angular2-meteor/blob/master/plugin/registrator.js#L4) to handle 'ang.html' files instead of handling 'html' files (and renamed bootstub.html to bootstub.ang.html).

Is there a plan to support this kind of integration built in to the package?
I suspect stuff like Blaze html concatenation may cause a lot of trouble when things start to get complicated.

**Comment by Stivfk** [comment]
This is a duplicate issue. It is currently under discussion here https://github.com/Urigo/angular2-meteor/issues/14

**Comment by barbatus** [comment]
Closed as duplicated.
