### ISSUE TITLE
Nested directives using angular2 & blaze

### ISSUE THREAD

**Issue by Matanlb** [Urigo/angular2-meteor#49]
Hi,

I've been trying incorporate Angular 2 in our system which is currently using blaze, step by step.

One of the major problems I encountered trying to replace one of the system pages from Blaze to Angular2 (while keeping all other pages working with blaze in a working order) is when I try to use on directive inside of another.

I getting what I think is a dummy exception from the browser, **Uncaught SyntaxError: Unexpected token <**. from what I can see in the browser dev-tools some part of the infrastructure try to use the concatenated html since the imported file of the nested directive files to either be transpiled or imported, I don't really know since I don't see any errors from the meteor CLI 'compilation' process.

Any clue what can cause this behavior?

**Comment by Stivfk** [comment]
I usually get this exception when a file is not well referenced in an application. Try to look inside debug console --> explore to see which file is it.

**Comment by barbatus** [comment]
Source of the issue is unlikely related to nested directives. As was mentioned above, some module is likely referenced wrongly in your app.
