### ISSUE TITLE
angular2-meteor sample stopped working after meteor update

### ISSUE THREAD

**Issue by funnyprinter** [Urigo/angular2-meteor#53]
I'm just going through the Meteor Angular 2 Tutorial. Installed Meteor a while ago. At step 6 I just randomly tried 'meteor update' which crashed my sample. Update worked, created some new typings and server is starting. For me my local copy is identical to the sample in the git repository. However the browser screen stays now empty and in the console appears an error:

    Uncaught SyntaxError: Unexpected token <

    Uncaught (in promise) Uncaught SyntaxError: Unexpected token <
        Evaluating http://localhost:3000/client/app.js
        Error loading http://localhost:3000/client/app.js

Already posted question on http://stackoverflow.com/questions/34501079/angular2-meteor-sample-stopped-working-after-meteor-update, but no answer up to now. Just thought it may be better situated here.

Since I'm new to meteor I not able to figure out the reason why I'm getting this error?

**Comment by barbatus** [comment]
If you haven't updated for a long time, you might still be using 'angular2/angular2' module, which is outdated now. If not this then repo with the code is welcomed.

**Comment by funnyprinter** [comment]
I'm using meteor packages, which should be the latest

    autopublish            1.0.4  (For prototyping only) Publish the entire database to all clients
    es5-shim               4.1.14  Shims and polyfills to improve ECMAScript 5 support
    insecure               1.0.4  (For prototyping only) Allow all database writes from the client
    jquery                 1.11.4  Manipulate the DOM using CSS selectors
    meteor-base            1.0.1  Packages that every Meteor app needs
    mobile-experience      1.0.1  Packages for a great mobile user experience
    mongo                  1.1.3  Adaptor for using MongoDB and Minimongo over DDP
    session                1.1.1  Session variable
    standard-minifiers     1.0.2  Standard minifiers used with Meteor apps by default.
    tracker                1.0.9  Dependency tracker to allow reactive callbacks
    urigo:angular2-meteor  0.3.5  Angular2 and Meteor integration

**Comment by funnyprinter** [comment]
Got it solved updating all the changed angular 2 syntax. @barbatus thx
