### ISSUE TITLE
tutorial step 4(angular2) doesn't work

### ISSUE THREAD

**Issue by davidxiao** [Urigo/angular2-meteor#55]
Hi,
There is one issue about step4, but not sure if it's the same, so mention here again,

addParty function is not called, and any updates to parties-form.html will be not reflected in the view(even could remove parties-form.html without changes to other codes)

could reproduce: 
1.download https://github.com/Urigo/meteor-angular2.0-socially/archive/step_4.zip
2.play with parties-form.html, etc

I am using latest version, i.e: 0.3.5

**Comment by vamsivarikuti** [comment]
@davidxiao Its working fine, addParty function is getting called.

I ran `meteor` in the project directory, then different typings were generated, There were errors like `angular2/core` not found.

But after that I ran `meteor update` in the project, deleted the typings directory and then ran `meteor` , new typings got generated, then it works fine

**Comment by davidxiao** [comment]
@vamsivarikuti, thanks, yes, after updating,
it's related to my env

**Comment by davidxiao** [comment]
just in case somebody experienced it, positively believe it's related to my env,
it works with ports than 3000,
I tested this with the exact same code copy
