### ISSUE TITLE
Avoid using `/// <reference path="../....."> ` in every file

### ISSUE THREAD

**Issue by vamsivarikuti** [Urigo/angular2-meteor#57]
We can specify `files` in tsconfig.json to avoid referencing in every file
Reference: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

@barbatus: Can you guide me on this? i think i can do this.

**Comment by barbatus** [comment]
Yes, this is exactly what I am doing now.
Please, check a preliminary roadmap here https://github.com/Urigo/angular2-meteor/#roadmap.
You can pick up any of the features you want.

**Comment by vamsivarikuti** [comment]
@barbatus :)
can you suggest a beginner friendly feature and mentor me?

**Comment by barbatus** [comment]
For the smaller ones, you could try to implement reactive variables support in the templates (proposal is here https://docs.google.com/document/d/1tkhqvVJimXi5hKvKViNKaujkfbZKzPOQwj0uHQmzcBU; I personally don't like the feature but it might be great for smaller apps), or investigate how to make exception handling in Angular 2 templates similar to Blaze (there seems to be a way to override default exception handling in Angular 2).

For the bigger ones, as I remember Urigo once suggested you to take on the Blaze templates to Angular 2 components migration solution. I see two steps here: first is to implement a special directive that given a template name renders the template inside (I already have a code for it), second is to create a transition path and describe it [here](http://www.angular-meteor.com/migration/angular1/intro). If you choose this one, I can create a doc file with more detailed description how I see it.

**Comment by vamsivarikuti** [comment]
@barbatus I want to try reactiveVar, I need some help in setting up the plugin for local use. 
Can we discuss on gitter or slack? instead of here

**Comment by Urigo** [comment]
Deployed, please check if it fixes the problem
