### ISSUE TITLE
Cant start a new project

### ISSUE THREAD

**Issue by elzeron** [Urigo/angular2-meteor#60]
I'm trying to start a new project and i get this error:

Started MongoDB.
Errors prevented startup:

While processing files with urigo:angular2-meteor (for target os.linux.x86_32):
/tools/isobuild/compiler-plugin.js:418:13: Document sections can only be emitted to web targets
  at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:418:13)
  at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:294:24)
  at NgHtmlCompiler.addCompileResult (compilers/html_compiler.js:72:10)
  at caching-compiler.js:305:14
  at /home/edelgadillo/.meteor/packages/urigo_angular2-meteor/.0.3.6.1xcunlz++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
  at replenish (/home/edelgadillo/.meteor/packages/urigo_angular2-meteor/.0.3.6.1xcunlz++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
  at /home/edelgadillo/.meteor/packages/urigo_angular2-meteor/.0.3.6.1xcunlz++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:328:15
  at Object.async.forEachLimit.async.eachLimit (/home/edelgadillo/.meteor/packages/urigo_angular2-meteor/.0.3.6.1xcunlz++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:221:35)
  at NgHtmlCompiler.processFilesForTarget (caching-compiler.js:277:11)
  at NgHtmlCompiler.processFilesForTarget (compilers/ng_caching_compiler.js:17:32)
  at HtmlCompiler.processFilesForTarget (compilers/html_compiler.js:46:24)

Your application has errors. Waiting for file change.

Meteor version: 1.2.1
Also when i run "meteor add urigo:angular2-meteor" it doesn't create the typings folder
I used meteor update and it didn't run anymore
files in project folder: 
app.ts
index.html

I'm following step 0 (bootstrapping) of the 'socially' tutorial on angular-meteor.com (Angular2) and I cant finish it

**Comment by franzsilva** [comment]
Are the files app.ts and index.html in a folder called client? So they should be like this.

client/index.html
client/app.ts.

**Comment by elzeron** [comment]
I apologize, You were right, and it seems I have not red enough documentation. Now it is working correctly. 
Thank you

**Comment by franzsilva** [comment]
No worries. Glad to help.

**Comment by BryanARivera** [comment]
I am getting the same error with both of the examples.  The recommendation above did not work.

```
=> Errors prevented startup:                  
   
   While processing files with urigo:angular2-meteor (for target os.osx.x86_64):
   /tools/isobuild/compiler-plugin.js:418:13: Document sections can only be emitted to web targets
   at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:418:13)
   at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:294:24)
   at HtmlCompiler.processFilesForTarget (compilers/html_compiler.js:40:24)
```

**Comment by kyle-007** [comment]
Hi, I think had the same problem and it turns out that when I remove the bundle directory it works again. Good luck

**Comment by BryanARivera** [comment]
@kyle-007 Where is the "bundle directory"?

**Comment by kyle-007** [comment]
Hi, it is right under the root project directory for me. It was create when
I tried to run my meteor as docker. If you do not have one then you error
was caused by something else.

**Comment by BryanARivera** [comment]
I am pulling direct from the example.  Not a good sign when the issue is continually closed without proper resolution.  I hope this gets better as angular2-meteor looks awesome.

**Comment by barbatus** [comment]
@BryanARivera it's caused if you have HTML files get to the server part as well. Check out that everything with .html extension is under client folder.

**Comment by BryanARivera** [comment]
@barbatus that's probably it.

**Comment by BryanARivera** [comment]
@barbatus does meteor normally behave like this?  Or is it specfic to this project's code?  Seems like there should at least be a more descriptive warning somewhere.

**Comment by barbatus** [comment]
@BryanARivera most people keep it in this way, i.e., client code in the client folder. Yes, by default Meteor creates an app with all files in the root, but for bigger projects with multiple html files, it is recommended to have rigid app structure, i.e., with at least client, server folders.

Anyways, I wanted to fix this issue long time but just didn't have time. I may do it finally in the near time.
