### ISSUE TITLE
"Document sections can only be emitted to web targets" (Ubuntu 14.04)

### ISSUE THREAD

**Issue by j127** [Urigo/angular2-meteor#61]
I'm getting an error with angular2-meteor on Ubuntu 14.04 and Meteor 1.2. To reproduce:

`meteor create myapp`

Remove:

* `myapp.css`
* `myapp.html`
* `myapp.js`

Add `index.html` containing:

    <body>
      <p>Hi</p>
    </body>

Everything still works up to that point.

Then do:

* `meteor add urigo:angular2-meteor` (errors begin after this step)
* `meteor remove blaze-html-templates`
* `meteor remove ecmascript`

Errors:

    => Modified -- restarting.                    
       Building for web.browser                  \

       Building for os.linux.x86_64              |

    => Errors prevented startup:                  
       
       While processing files with urigo:angular2-meteor (for target os.linux.x86_64):
       /tools/isobuild/compiler-plugin.js:418:13: Document sections can only be emitted to web targets
       at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:418:13)
       at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:294:24)
       at NgHtmlCompiler.addCompileResult (compilers/html_compiler.js:72:10)
       at caching-compiler.js:305:14
       at /home/username/.meteor/packages/urigo_angular2-meteor/.0.3.6.1bhyb3x++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
       at replenish
       (/home/username/.meteor/packages/urigo_angular2-meteor/.0.3.6.1bhyb3x++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
       at /home/username/.meteor/packages/urigo_angular2-meteor/.0.3.6.1bhyb3x++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:328:15
       at Object.async.forEachLimit.async.eachLimit
       (/home/username/.meteor/packages/urigo_angular2-meteor/.0.3.6.1bhyb3x++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:221:35)
       at NgHtmlCompiler.processFilesForTarget (caching-compiler.js:277:11)
       at NgHtmlCompiler.processFilesForTarget (compilers/ng_caching_compiler.js:17:32)
       at HtmlCompiler.processFilesForTarget (compilers/html_compiler.js:46:24)
       
       
    => Your application has errors. Waiting for file change.

I followed [this tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping) twice and got that error at the same place both times.

**Comment by franzsilva** [comment]
Are you adding the files in the client folder?

you should have client/index.html

**Comment by j127** [comment]
Thanks... I had the file in the wrong place. Sorry about that.

**Comment by franzsilva** [comment]
No worries. Glad to help.
