### ISSUE TITLE
Reconsider angular 2 import approach

### ISSUE THREAD

**Issue by staeke** [Urigo/angular2-meteor#62]
First, thanks for good work!

We've started some work based off this package. I'm using WebStorm, and I've noticed some inconveniences as compared with "standard" angular 2 development:

1. WebStorm's "Auto import packages" functionality imports the packages erronously through statements like ```import NgStyle = common.NgStyle``` instead of ```import {NgStyle} from 'angular2/common```. That happens because of the declared (global) modules ```common``` and friends in the typings directory. Note that this is not the case for angular 2 work outside of meteor in WebStorm, where types are auto imported correctly.
2. The TypeScript configuration is hidden in ```.tsconfig``` as compared to ```tsconfig.json`` which was a little surprise for me at least.
3. I wanted to compile my templates using another approach, which made me have to install a local modified version of this library to turn it off.
4. I love having the whole ```ng``` object declared on window for easier debugging, and thus I can include the UMD version of angular. This seems impossible with this package.

Now I played around a little, trying to get 1. to work well, and I realized that the ```moduleResolution``` property of ```tsc``` is just supporting "standard" and "node" modes. And Angular 2 is expecting you to use "node". Now this is all fine and dandy, if node_modules was supported. And, as a matter of fact it will be for meteor 1.3. If not already on the roadmap, may I suggest you/we go the more standard Angular 2 route for meteor 1.3 and enforce/encourage the user to install angular 2 the normal way in node_modules. And enforce/create/read the ts config from ```tsconfig.json```. Thus it would be picked up by tools compatible with the typescript compiler (e.g. WebStorm) and completions would work just fine without any special typings or similar.

Regarding 2. and 3. it would be nice to be able to turn and off html and ts compilation. Either through package chains or configuration (don't know if it's possible, just read this https://meteor.hackpad.com/New-control-file-brainstorming-ZDBMiEQ6DZl). Maybe the whole cursor diff mechanisms can be refactored into its own library, and then I could reference that, and setup UMD inclusions and compilations through other means.

Regarding 4 - how about including the UMD version by default in non-productions builds? Again, maybe hidden behind some option.

**Comment by barbatus** [comment]
1. tsconfig.is is now legitimately supported (but keep in mind only `module: system` available). Check out README.
2. Angular2 NPM will come after Meteor 1.3 release, no earlier; unless somebody else will help us to move it before.
3. With Meteor 1.3, I expect System.js will be replaced by CommonJS, which is compatible with UMD. So you will be able to use Angular 2 UMD version.

**Comment by staeke** [comment]
thanks for the reply @barbatus . Some comments:

1. I was probably unclear. My question was around ```.tsconfig``` vs ```tsconfig.json```. Are you saying that ```tsconfig.json``` is not officially supported?
2. Totally reasonable. I could imagine helping with that though.
3. ok

**Comment by barbatus** [comment]
I meant that TypeScript is now configured by tsconfig.json in this package.

**Comment by staeke** [comment]
@barbatus ok

**Comment by barbatus** [comment]
With Meteor 1.3 and `angular2-compilers` package, `moduleResolution: node` is now by default.
You may try to play around with Angular2-Meteor NPM (check README for more info).
Also, if you want your own template compilation now - avoid installing `angular2-compilers`, and instead install you compiler. At the same time, if you still want to use ts-compiler that comes with `angular2-compilers` - just add `barbatus:typescript` separately to your project.

As for the version to be used with Meteor 1.2 (i.e., atmosphere package), It'll continue to have embedded TypeScript and HTML compilers for time being at least.

Otherwise, I consider this issue resolved. If you still have some info or troubles, consider commenting it here or even re-opening.
