### ISSUE TITLE
typings folder doesn't add automatically

### ISSUE THREAD

**Issue by mehdibalouchi** [Urigo/angular2-meteor#63]
I installed angular2-meteor a few days ago, as the tutorial says after first install it creates typings folder automatically.
recently I tried to add angular2-meteor on my friends PC and it does not create the folder automatically.
please do somthing!!!

**Comment by mehdibalouchi** [comment]
For now I am using version 0.3.5.
It seems that after this version the package does not creates the folder automatically.

**Comment by barbatus** [comment]
Update to the latest version, pls.

**Comment by mehdibalouchi** [comment]
It is fixed.
thanks
