### ISSUE TITLE
View Changes does not apply

### ISSUE THREAD

**Issue by mehdibalouchi** [Urigo/angular2-meteor#64]
I'm using anuglar2-meteor package and I have a problem with views.
when I change an html file in my IDE, changes does not apply in the browser (even after client refreshing).
clear cache in browser is helpful and after that I can see those changes I made. any solution for this?

**Comment by barbatus** [comment]
Yes, there seems to be no way currently to control caching in the @View annotation or any other way. But you can always turn off caching for a particular site today in most browsers with the help of development tools. I personally develop and test using Google Chrome Dev tools, and have no trouble with the caching.

**Comment by TrikinCurt** [comment]
Is there a point to the @View annotation?  I never use it, since template and templateUrl can go in @Comonent, is there any point to @View?

**Comment by barbatus** [comment]
@mehdibalouchi no, view metadata is added anyways though @Component if there is no @View. But my answer was not exactly right. You can always try something like:
@Component({
  templateUrl: devMode ? 'foo.html?v=' + Random.id() : 'foo.html'
})
```
It might help.

We also may consider adding some similar feature in the future.

**Comment by barbatus** [comment]
We recommend to use template as string in the components.
Check out https://github.com/Urigo/angular2-meteor#static-resources.
Thus, problem has dissolved itself for now.
In future, it's gonna be possible to import template URLs as well:
`import url from './foo.html!url'`, where url comes with a hash param.
