### ISSUE TITLE
Cannot find module 'angular2/common'

### ISSUE THREAD

**Issue by ujinv** [Urigo/angular2-meteor#69]
When I import something like NgFor using
```
import {NgFor} from "angular2/common";
```
Meteor shows in console errors like:
```
client/widget.ts (8,21): Cannot find module 'angular2/common'
```
Never the less my app is OK with that.

I can see that there are all needed files in typings dir that contain core, common, routing and bootstrap modules. All of them do have all the needed exports. All other modules (core, router, bootstrap) are imported just fine without errors in console.

**Comment by ujinv** [comment]
I have an update on that. Although this issue was solved as well as #47, but I still don't understand why some modules are imported OK and some still fail. I've made a test repo with sample meteor-angular2 project showing that issue: https://github.com/ujinv/meteor-import-test.git
Now I have issues importing `sprintf` module. It looks almost the same way as I described in issue:
without any imports code works ok, message is shown in console, but I have compiler error - no name `sprintf` found. If I try to import this function like `import {sprintf} from "sprintf"` compilation goes without errors, but in runtime there is an error in console saying no module `sprintf` found.

**Comment by barbatus** [comment]
@ujinv What's `sprintf`? If you read the tutorial you should be aware that imports in this package work though System.js.
Each random Meteor package can't be supported, unless authors decided to export API in System modules for some reason.
You'll need to use `liyu:sprintfjs` in the same way as it's designed to be used: directly through globally available API.

**Comment by ujinv** [comment]
Ok
