### ISSUE TITLE
Gulp with Angular2-meteor

### ISSUE THREAD

**Issue by ktarak** [Urigo/angular2-meteor#70]
Hi,
I want to use Gulp in Angular2-meteor, but I could not install gulp.
can u help me please and thank you

**Comment by dalcib** [comment]
Why use Gulp if we can use only tsc for the same job?

Insted 
  `"scripts": {
    "install": "./node_modules/.bin/gulp build"
`
we can use:
`  "scripts": {
    "install": " tsc"
`
with a `tsconfig.json` file

**Comment by dotansimha** [comment]
Hi @ktarak , can you explain why do you need Gulp? In the current version of Angular2-Meteor, the build process is part of Meteor's ecosystem and you should not need Gulp at all... am I missing something?

Thanks!

**Comment by ktarak** [comment]
hi thank you for your answers.
I am beginner with ANGULAR 2- METEOR and I look for how we created a workflow using jenkinz

**Comment by TrikinCurt** [comment]
Won’t gulp be a part of the process again in 1.3?  Perhaps I am wrong, I am
new as well, but I believe 1.3 will make Meteor “different” for meteor
users, but more common for us Angular users :)



Curt Fluegel
Trikin Properties - Your Twin Cities Landlord
Broker/Owner
2015 MHA Independent Owners Chair
2014 NARPM® MN Chapter President
Serving the Twin Cities Metro and Western Wisconsin
curt@trikinproperties.com
TwinCitiesLandlord.com
651.964.3812 x101
651.964.3814 fax

**Comment by Urigo** [comment]
@ktarak can you describe the workflow you are trying to achieve?

**Comment by ktarak** [comment]
hi thank you for your answear 
i like to add Angular2-Meteor into  my project however i want to use Gulp to export my dist Prod 
for that i can't find any description for this method.
Can i help me ?

**Comment by Urigo** [comment]
if you use Meteor build system you don't need to do that because Meteor build will do that for you,
can you share your code?

**Comment by ktarak** [comment]
i use Gulp to build Angular project and to export a prod distrubition , also i want to minifiey the Js into the meteor project.
the following the package.json of my Gulp dependencies
`  "devDependencies": {

    "angular2-hot-loader": "0.0.16",
    "async": "^1.4.2",
    "browserify": "^13.0.0",
    "chalk": "^1.1.1",
    "connect-livereload": "^0.5.3",
    "del": "^2.2.0",
    "event-stream": "^3.3.2",
    "express": "~4.13.1",
    "extend": "^3.0.0",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.5.2",
    "gulp-cssnano": "^2.0.0",
    "gulp-filter": "^2.0.2",
    "gulp-inject": "^1.3.1",
    "gulp-inline-ng2-template": "^0.0.7",
    "gulp-load-plugins": "^0.10.0",
    "gulp-plumber": "~1.0.1",
    "gulp-shell": "~0.4.3",
    "gulp-sourcemaps": "~1.5.2",
    "gulp-template": "^3.0.0",
    "gulp-tslint": "^3.3.0",
    "gulp-tslint-stylish": "^1.0.4",
    "gulp-typedoc": "^1.2.1",
    "gulp-typescript": "~2.8.2",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.2.4",
    "jasmine-core": "~2.3.4",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "~0.13.15",
    "karma-chrome-launcher": "~0.2.0",
    "karma-ie-launcher": "^0.2.0",
    "karma-jasmine": "~0.3.6",
    "karma-mocha-reporter": "^1.1.1",
    "karma-phantomjs2-launcher": "^0.3.2",
    "merge-stream": "^1.0.0",
    "open": "0.0.5",
    "protractor": "^3.0.0",
    "rimraf": "^2.4.3",
    "run-sequence": "^1.1.0",
    "semver": "^5.0.3",
    "serve-static": "^1.9.2",
    "slash": "~1.0.0",
    "stream-series": "^0.1.1",
    "tiny-lr": "^0.2.1",
    "traceur": "^0.0.91",
    "ts-node": "^0.5.4",
    "tsd": "^0.6.4",
    "typedoc": "^0.3.12",
    "typescript": "~1.7.3",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "yargs": "^3.25.0"
  }`

**Comment by Urigo** [comment]
Why is that better than Meteor's minification?

**Comment by ktarak** [comment]
thank you @Urigo 
i'm very sorry, just i would to ask you other question:
i create a project with Angular2 meteor and i have a Expression when i use more than 9 expressions 
i search in many Blogs and in stackoverflow but i don't have the repense
i see the same problem in stackoverflow but any person answear us 

http://stackoverflow.com/questions/34962707/angular2-exception-does-not-support-more-than-9-expressions

**Comment by barbatus** [comment]
This issue seems to be outdated now. Please, check it status with the latest Angular2-Meteor and Angular2 versions. if you have troubles - consider re-opening it. Closing it for now.

**Comment by anuragagarwal561994** [comment]
I feel gulp would be required mainly for linting or may be for injections (injecting front-end dependencies) in a meteor project. I am using [bbmoz:gulp](https://atmospherejs.com/bbmoz/gulp) for now to lint typescript and sass files.

There are some packages available in atmosphere for [eslint](https://atmospherejs.com/dburles/eslint) and [jshint](https://atmospherejs.com/meteor/jshint) but again there are no packages for jscs and other code quality tools.

The only problem I find with `bbmoz:gulp` package is that I have to run gulp as a second process in another terminal which doesn't seem to me a nice way.
