### ISSUE TITLE
Need some way to inject html meta tags into the default template

### ISSUE THREAD

**Issue by shmakes** [Urigo/angular2-meteor#72]
Putting the meta tags for using bootstrap (css library not the angular method) in an index.html at the mail client level works fine, if you enter the application from the root url. If you enter the app from another page url and navigate to the root, you get errors:

    EXCEPTION: Template parse errors:
    Unexpected closing tag "head" ("
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    [ERROR ->]</head>
    <body>
    
    "): CallCentersForm@108:0
    Unexpected closing tag "html" ("
    
    </body>
    [ERROR ->]</html>

(CallCentersForm is similar to PartiesForm in the tutorial)

If I do not have an index.html, I can start anywhere and navigate anywhere but the app looks junky because bootstrap does not apply correctly based on the screen size.

It would be nice if there was a way to inject tags into the <head> section of the generated template from code. This could be useful for SEO, special formatting for browsers on Apple devices, etc.

(Maybe similar to this Meteor Package for Blaze? https://atmospherejs.com/zucchinize/meta-tags)

Here is what I would like in my main template:

```html
<head>
  <title>My App Title</title>
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
  <app role="document"></app>
</body>
```

Maybe there is another way to accomplish what I need, but I have not found it yet.
Really waiting to see [Step 17] (http://www.angular-meteor.com/tutorials/socially/angular2/css-less-and-bootstrap) in the Tutorial when it is ready. :-)

**Comment by barbatus** [comment]
I still don't see why you are getting this error while navigation to the root page.
What's your other page's template look like?

**Comment by Urigo** [comment]
@shmakes can you share a reproduction for your bug in a repo?

**Comment by shmakes** [comment]
Buried at the moment, but I will try to get a repo out there tonight or
Monday night.
Thanks.

**Comment by shmakes** [comment]
I think I have found the origin of the problem.
It seems to be an issue between the initial loading of an HTML fragment template and subsequent reloading of the template.
The initial load seems to work fine and the text is loaded and apparently cleaned up into proper HTML.
On reload, something is having problem with the fragment and possibly interpreting it as some sort of XML which is why it hates the HTML "meta" tag.

So, this works fine for initial load and reloads:

```html
<head>
  <title>My App</title>
</head>
<body>
  <app role="document"></app>
</body>
```

This fails with the original error I reported:

```html
<head>
  <title>My App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <app role="document"></app>
</body>
```

If you try to make the parser happy by switching to valid XML or XHTML, it does not matter.
Something normalizes the "meta" tag, removing any sort of non-HTML end tag, and it fails with the same error (the end tag never makes it to the browser).

For example, theses options do not work, you get the same error:

```html
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
```

However, if you wrap the whole thing in a root "html" tag, everything starts working.
My guess is that the presence of that "html" tag cause the parser to repeat the original process "every time" instead of trying to merge the template into an existing model.

```html
<html>
  <head>
    <title>My App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <app role="document"></app>
  </body>
</html>
```

I am fine with this work-around, but not sure if there will be any ill effects I have not discovered yet.

If you want to try it out with my code, just "git clone" this repository and run it.
https://github.com/shmakes/hf_callcenter
You won't be able to use all the features of the app, as it relies on an external web service, but you can test this issue with the initial sample data.

- Create a user.
- Goto "April 2016"
- Click the "Back to Events" button - it works
- Goto "April 2016"
- Refresh the page or click in the address bar and hit enter - the page reloads.
- Click the "Back to Events" button - it fails with blank page and error in the console.

**Comment by shmakes** [comment]
Never checked the "work around" on a mobile device.  Turns out having the HTML tags in the template causes it to be ignored entirely so you just get the default tags from the code and it looks like crud on mobile.

Still need a reliable way to reliably specify meta tags either in the template or code.

**Comment by barbatus** [comment]
Ok, I checked out your code. You forgot to add front slash in the template address here https://github.com/shmakes/hf_callcenter/blob/master/client/call_centers-form/call_centers-form.ts#L10

**Comment by shmakes** [comment]
Thank you for looking into that.
I know it is probably Angular2 code in play here, but it would be nice if stuff like that failed "right away". If it had, I probably would have found the mistake myself. The fact that it works when starting the app from one URL but not when going to that same URL from another starting URL, is rather confusing. They must be holding onto some "default path" at startup.

**Comment by barbatus** [comment]
I agree, there have been few people who had this issue. Yes, it's related to Angular2, and I am not sure if overriding template loading or handling its errors are easy doable now. There exist similar issues related to the current (like https://github.com/Urigo/angular2-meteor/issues/64). So I'll likely look into templates loading in general about in the close future. It's worth mentioning though, that Meteor 1.3 will potentially have some solution that will allow to embed HTML in the code, so you won't need to use templateUrl (as described here https://github.com/Urigo/angular2-meteor/issues/156)
