### ISSUE TITLE
Meteor.logout()

### ISSUE THREAD

**Issue by piotr-gawlowski** [Urigo/angular2-meteor#75]
I've created small app with 2 routes.
However I have a problem, In my component I have a method logout() which executes

```javascript
logout(){
        Meteor.logout(()=>{
            this.router.navigate(['Auth']);
        });
    }
```
I am logged out, router navigates me to "Auth" component, Auth constructor is executed but ngOnInit is not. Also my view is not rendered.

But this works without problem - any reason why I have to do it?
```javascript
logout(){
        this.zone.runOutsideAngular(()=>{
            Meteor.logout(()=>{
                this.zone.run(()=>{
                    this.router.navigate(['Auth']);
                });
            });
        });
    }
}
```

**Comment by barbatus** [comment]
Meteor.logout's callback runs outside of the angualr2 zone, that's why changes to the UI not applied.
But what happens if you don't do this.zone.runOutsideAngular?

**Comment by piotr-gawlowski** [comment]
Thx, Alex
Yes - this.zone.runOutsideAngular - is not necessary here. Just after any Meteor method, call this.zone.run()
