### ISSUE TITLE
Something about 0.4.0 breaks @ViewQuery.changes.subscribe callbacks.

### ISSUE THREAD

**Issue by vangorra** [Urigo/angular2-meteor#77]
Prior to 0.4.0, this code would run fine.

``` typescript
@Component({
    selector: 'mycomponent'
})
@View({
    template: `
        <div *ngFor="#item of items">
            <div #field></div>
        </div>
    `
})
class MyComponent {
    items : number[];
    constructor(@ViewQuery('field', {descendants: true}) fieldList : QueryList<ElementRef>) {
        fieldList.changes.subscribe(_ => {
            console.log('Changed!');
        });
    }
}
```

You could change the "items" variable, new elements were created and the query list triggered the changed message.
Now however, the new elements are created and the query lit never triggers the changed message.

**Comment by Urigo** [comment]
@vangorra can you please share a reproduction in a repo?
also, have you tried the same behaviour with a plain Angular 2.0 app without Meteor?

**Comment by vangorra** [comment]
I created a test app and cannot reproduce the issue. There must be something wrong with my app code.
