### ISSUE TITLE
Create auto-changelog

### ISSUE THREAD

**Issue by drewlio** [Urigo/angular2-meteor#78]
This is a polite request to please keep release history updated. 

As a justification by example, I need to roll back to the last release on Beta 0. Atmosphere lists a history of release versions but no information for each (that I can find). The description links to CHANGELOG.md in Github but that file only lists versions 0.3.0 and 0.3.2. Even the description for those two is vague (ie, "Angular 2 upgraded to the last version").

By looking at commit history I think I need 0.3.7, but this seems like more effort than you want new adopters to go through. I think having dep versions in the CHANGELOG.md is reasonable. 

thanks, and thanks for the great work!

**Comment by Urigo** [comment]
I will change the title to make it a task, let me know if it makes sense.

Generate changelog automatically from commit messages.

**Comment by barbatus** [comment]
We'll  have a proper look on the change log from now on (auto log is added as well)
