### ISSUE TITLE
Formalize client side data strategy for the future reactive-graphql data layer

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#81]
Gather more thoughts on the best way to connect the future [Reactive-GraphQL Meteor layer](http://info.meteor.com/blog/reactive-graphql) to Angular 2.0.
Observables, Flux....

Random list of resources:

* [Introduction to Redux in Angular 2](https://docs.google.com/document/d/1M46J8HZgsuXw0Mr_e5fOvSBk4t7JtLwgiv0_dVT_EOs/edit#heading=h.nc7lcgxb5gp)
* [Meteor-Webpack-React-Redux](http://marmelab.com/blog/2015/11/27/meteor-webpack-react-redux.html)
* [Angular 2 — Introduction to Redux](https://medium.com/google-developer-experts/angular-2-introduction-to-redux-1cf18af27e6e#.a9pxyvsrj)
* [ReactEurope](https://www.youtube.com/channel/UCorlLn2oZfgOJ-FUcF2eZ1A/videos?flow=grid&sort=p&view=0)
* [Angular Air Episode 49: What's new in RxJS 5.0 with Ben Lesh](https://plus.google.com/events/c2ic6t5id964kdo47dr0of5d3ag)
* [Falcor](http://netflix.github.io/falcor/)

**Comment by barbatus** [comment]
Progress is happening here https://github.com/apollostack/angular2-apollo
