### ISSUE TITLE
Add SSR for fast loading times with Angular Universal

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#82]
Use Angular Universal to render Angular 2.0 views on the server for faster initial page load.

Add chapter to the Socially tutorial and example to the Angular Universal repo, and update here: https://github.com/angular/universal/issues/49#issuecomment-128811870

UPD:
link to the current version to be installed from a repo https://github.com/barbatus/angular2-meteor-universal

**Comment by manekinekko** [comment]
Hi @Urigo I'd be happy to take care of this issue. If you still looking for help just ping me ;)

**Comment by Urigo** [comment]
@manekinekko awesome!  what do you need to start?  want to have a chat?  my email is public on my Github profile

**Comment by manekinekko** [comment]
Great! Yep we can have a chat. What is your time zone ? I am in Paris BTW

**Comment by Urigo** [comment]
my timezone keeps changing ;)
send me an email and we'll schedule to whenever is good for you

**Comment by rvetere** [comment]
I'm not sure if could be a help but i'd like to contribute here too :)

**Comment by barbatus** [comment]
Follow activity here https://github.com/barbatus/angular2-meteor-universal
