### ISSUE TITLE
Remove logic that add default HTML file with BODY and <app>

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#83]
Remove logic that add default HTML file with BODY and <app> if there is not one and make the behaviour consistent with Blaze.

Also related to https://github.com/Urigo/angular2-meteor/issues/46

**Comment by Urigo** [comment]
@dotansimha please reference the commits.
@barbatus what do you think about it?

**Comment by barbatus** [comment]
@Urigo it doesn't matter much since a really small feature. We added this considering mostly that adding `<app></app>` each time is a repetitive task especially if you don't have main file with <head>, <body>. BTW, I don't see how it could prevent to use Blaze in that related bug, anyways...

**Comment by dotansimha** [comment]
https://github.com/Urigo/angular2-meteor/commit/66593685ac30cfd3734c11f152befb6536212395#diff-0a6909a3ffd1d537df13bc0bbb8ce73cL36
