### ISSUE TITLE
Rename "barbatus:ts-compilers" to "typescript-compilers"

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#89]

**Comment by dotansimha** [comment]
@barbatus

**Comment by barbatus** [comment]
@Urigo I started doing this. I guess we need a bunch of tests if it's going to be official?

**Comment by Urigo** [comment]
yessss

**Comment by barbatus** [comment]
New TypeScript compiler package located here https://github.com/barbatus/typesctipt-compiler.
Main issue about future Meteor TypeScript packages located here https://github.com/Urigo/angular2-meteor/issues/102
