### ISSUE TITLE
Remove "barbatus:typescript"

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#90]
Remove `barbatus:typescript` and instead just bring typescript from Npm and move it's logic to `typescript-compiler`

**Comment by barbatus** [comment]
There was new Meteor TypeScript package created https://github.com/barbatus/typescript with the same role and similar logic to Meteor's `ecmascript` package. Old stuff was moved to the different branch.
Follow main issue about the future TypeScript packages here https://github.com/Urigo/angular2-meteor/issues/102
