### ISSUE TITLE
Why "angular2-compilers" depends on "mongo"?

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#92]
If good reason, add comment

**Comment by dotansimha** [comment]
Tried to look in the source code and did not find any reason for that...
@barbatus what do you think?

**Comment by barbatus** [comment]
yes, this can be reoved

**Comment by Urigo** [comment]
@dotansimha can you please link to the commit?

**Comment by dotansimha** [comment]
https://github.com/Urigo/angular2-meteor/commit/b00a78add4cb5971fe55baba48a6f731d178f2d2
