### ISSUE TITLE
Why `angular2-compilers` depends on `ejson`?

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#93]

**Comment by Urigo** [comment]
If good reason, add comment

**Comment by barbatus** [comment]
It's used [here](https://github.com/Urigo/angular2-meteor/blob/master/modules/mongo_cursor_observer.ts#L109) to compare different types of IDs, i.e., string and MongoID

**Comment by dotansimha** [comment]
@barbatus Yeah but now we need to use `imply` in the compilers packages in order to add this... I think we can get the `ejson` package from NPM

**Comment by Urigo** [comment]
@dotansimha please reference the commits

**Comment by dotansimha** [comment]
Fixed in https://github.com/Urigo/angular2-meteor/commit/7852b8216914a13cf5a8ae89dc6f855ef5120e1d
