### ISSUE TITLE
Update to latest Meteor 1.3 Beta and Angular 2.0 Beta

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#94]
Ongoing until Meteor 1.3 release

**Comment by dotansimha** [comment]
Updated in 02/02. 
Angular version is 2.0-beta2
Meteor version is 1.3-beta5

**Comment by dotansimha** [comment]
Updated in 05/02. 
Angular version is 2.0-beta3
Meteor version is 1.3-beta6
Zone.js version is 0.5.11

**Comment by bjones6** [comment]
Any chance we could get an upgrade to 1.3-beta8? I heard it had some significant improvements to build time.

**Comment by barbatus** [comment]
not actual now.
