### ISSUE TITLE
Should we PR and add the file mixin functions to Meteor itself?

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#96]
Should we PR and add the file mixin functions in [ng2-compilers](https://github.com/Urigo/angular2-meteor/blob/feature/meteor1.3/ng2-compilers/utils/file_mixin.js) to Meteor itself?

**Comment by sebakerckhof** [comment]
+1 for adding to Meteor, you need at least some of these for almost every compiler plugin.

**Comment by Urigo** [comment]
@sebakerckhof can you find a similar issue on Meteor's repo or create one?
then maybe would you like to help with that PR?

**Comment by sebakerckhof** [comment]
@Urigo I created https://github.com/meteor/meteor/issues/6262 for this.

**Comment by Urigo** [comment]
@sebakerckhof cool.  my guess is that a PR will draw more attention than an issue..

**Comment by sebakerckhof** [comment]
Yeah, but as per the post of sashko here: https://github.com/meteor/meteor/pull/6238 , they'd prefer having a discussion before the PR.

**Comment by Urigo** [comment]
@sebakerckhof I think the best thing to do is to just create the PR and then see if they will merge.

Closing here but reference your PR if you do one here

thanks!
