### ISSUE TITLE
Change mixin in utils to underscore's "Assign"

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#97]
https://github.com/Urigo/angular2-meteor/blob/feature/meteor1.3/ng2-compilers/utils/mixin.js

**Comment by sebakerckhof** [comment]
Won't Object.assign be polyfilled anyway? So maybe we can use that.

**Comment by dotansimha** [comment]
Used `Object.assign`, thanks @sebakerckhof

**Comment by Urigo** [comment]
@dotansimha can you please link to the commit?

**Comment by dotansimha** [comment]
All compilers work are in : https://github.com/Urigo/angular2-meteor/commit/66593685ac30cfd3734c11f152befb6536212395
